### ISSUE TITLE
Click to open doesn't work with inline images

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#1000]
**Steps to reproduce**
*    receive an inline image
*    save it
*    click on it to open

**Expected behavior**
Saved image should open.

**Actual behavior**
Folder with uTox.exe is opened.

**Env**
Win 7 x64, uTox v.0.16.0.

It looks a lot like this one #794.

**Comment by uname2p** [comment]
@redmanmale  uTox(v0.16.0) Sent "inline image" to uTox(v 0.9.7), if the uTox(v 0.9.7)  saved it, the image size will be zero byte. uTox(0.16.0) sent to qtox or uTox(v 0.9.7) sent to me(v 
![2017-08-23_094720](https://user-images.githubusercontent.com/19523804/29595288-2990b5ea-87e9-11e7-854f-4b308c1f36d0.jpg)
0.16.0), it was work perfectly.
