### ISSUE TITLE
File picker doesn't open

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#1002]
**Env**
Ubuntu 16.04 x64, uTox v.0.16.0.

![utox](https://user-images.githubusercontent.com/6782721/29570462-327052b8-875f-11e7-81ca-74021d9dec55.gif)

**Comment by robinlinden** [comment]
Do you have GTK3 installed? If so, you can try reverting https://github.com/robinlinden/uTox/commit/aa7d971d7051a09854e06ddde172dd859dcda865

**Comment by redmanmale** [comment]
I'll check and try it.

**Comment by endoffile78** [comment]
Works for me with uTox 0.16.1 and GTK3 version 3.22.18

**Comment by redmanmale** [comment]
I've got `3.18.9-1ubuntu3.3`. Updating to `3.20.8-1ubuntu0~pp` doesn't help.
After reverting this https://github.com/robinlinden/uTox/commit/aa7d971d7051a09854e06ddde172dd859dcda865 it works.

**Comment by GrayHatter** [comment]
@robinlinden you wanna try to load without the `.0` file name, then fall back to the name with the `.0`

...fucking BSD

**Comment by redmanmale** [comment]
Fixed in #1009.
