### ISSUE TITLE
tox mostly static

### ISSUE THREAD

**Issue by mscarav** [uTox/uTox#1023]
I hope this is the right place to ask, but I could not find the information anywhere else.
Could somebody clarify what is the difference between utox as obtained and installed from the repository https://pkg.tox.chat/debian and the version which says "mostly static"?
What does "mostly static" mean?
Moreover, is it normal that the mostly static version (currently 0.15) uses about 100-200 MB of RAM memory on a 64-bit OS, whereas the version installed from repo uses up to 700 MB of RAM on the same system? With the version from repo the RAM usage grows constantly while the program is open/calling until it stabilizes when it reaches about 700 MB of RAM memory usage for utox alone. The OS in question is Ubuntu 16.04 with kernel 4.4.0.92.

**Comment by andoruB** [comment]
Static refers to which way the executable is linked. When an executable is statically linked, you don't need to have the required libraries installed, while conversely, dynamically linked executables require you to have the correct libraries installed, and them to have the correct versions. What they mean by "mostly static" is that the executables don't require all the libraries to be installed, but depending on your case, your app might not work if you're missing something.   
The excessive RAM usage is probably a bug.  
My copy of it (0.16) which I've compiled myself doesn't use more than 57MiB

**Comment by mscarav** [comment]
Thank you!

**Comment by robinlinden** [comment]
The RAM usage is absolutely a bug. On Windows, uTox is between 15 and 25 MiB of (private) RAM after having been running for a few hours with groupchats and stuff.

@mscarav Do you know how to use Valgrind? Is the memory usage that high consistently?

**Comment by GrayHatter** [comment]
asan could easily cause this
