### ISSUE TITLE
Human-readable settings file format (INI)

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#1037]
[INI format](https://en.wikipedia.org/wiki/INI_file).

Text format is better than binary and more usable to store string values (for some paths or whatever).
It has sections so we can organize different settings logically.

We don't even need to write our parser for it, just grab for example [this one](https://github.com/benhoyt/inih). It's one header, small and has tests.

**Settings file draft**
```ini
[system]
version = 0.16.1

[network]
ipv6 = true
udp = false
proxy = true
proxy_ip = 127.0.0.1
proxy_port = 9999
proxy_force = true

[ui]
language = en
close_to_tray = false
use_mini_flist = true

[notifications]
; some comment about it

[more_sections]

```

We should choose which settings in which sections are going to be.

**Comment by GrayHatter** [comment]
@redmanmale sound's good to me. the settings layout should match what's on the settings section of the UI.

if you're going to use the header you linked to, add it as a git submodule. (which is what we should be using for stbi)

**Comment by endoffile78** [comment]
I think this would be a lot better.
