### ISSUE TITLE
Chat messages can overlap the arrival timestamps.

### ISSUE THREAD

**Issue by robinlinden** [uTox/uTox#1057]
Reported on Windows 7 & 10.
![image](https://user-images.githubusercontent.com/8304462/30519982-3a8f8762-9ba4-11e7-9f12-ca1fe7dbd321.png)

**Comment by sebsu** [comment]
![capture](https://user-images.githubusercontent.com/1716091/30520076-9c056a4c-9ba5-11e7-87f9-0f9178823266.PNG)

Same issue, more overlap. Windows 7.

**Comment by redmanmale** [comment]
It was in #868 (second from end).
