### ISSUE TITLE
Submodules config updates

### ISSUE THREAD

**Issue by GrayHatter** [uTox/uTox#1059]
both need to be marked as 

* clone shallow
* add a 2nd url for a "local" clone of each submodule e.g. github.com/uTox/[submod]

consider 

* moving submodules to `include/` or `something_else/`

**Comment by fcore117** [comment]
perhaps folder ThirdParty/stb and in future it can be place for other libraries if needed? just a idea noting more.

**Comment by GrayHatter** [comment]
http://foonathan.net/blog/2016/07/07/cmake-dependency-handling.html

see case 1: header only libs

**Comment by avoidr** [comment]
Has this not been closed by #1104 now?
