### ISSUE TITLE
Filter audio always disabled in CMake

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#1081]
I don't quite get how CMake works and maybe I'm wrong but _it seems_ that forwarding CMake option to define (ENABLE_FILTERAUDIO -> AUDIO_FILTERING) was dropped here 3455481a6558fc9c0c4b65e27f417236a32e26c1. Or is it by design?

To enable audio filtering I added this option back (like [that](https://gist.github.com/redmanmale/358e8af61e2f353604d9c58be019defe)) and I can make a PR for it.

**Comment by GrayHatter** [comment]
confirm you're using cmake .. -DENABLE_FILTERAUDIO=ON or something very similar?

Then nuke your cmake build directory, and try again. Cmake caches a lot. very often WAY too much. and it's better to nuke the Build Dir and start over.

**Comment by redmanmale** [comment]
Yes, I use `cmake -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchain-win64.cmake" -DENABLE_FILTERAUDIO=ON -DTOXCORE_STATIC=ON ..`

And if I get it right `ENABLE_FILTERAUDIO` is `ON` by default.

I always delete my build folder.

**Comment by GrayHatter** [comment]
Ahh, I understand the problem now. Open a pull for that patch please sir!

Good catch @redmanmale
