### ISSUE TITLE
show used toxcore version on "Advanced" Tab in settings

### ISSUE THREAD

**Issue by zoff99** [uTox/uTox#1085]
show used toxcore version on "Advanced" Tab in settings

e.g. ->
"c-toxcore 0.1.4"

**Comment by GrayHatter** [comment]
toxcore exposes it's version, and if you compile in development mode this is the default.

there's no easy name exposed by toxcore to provide the upstream lib name, so open this issue upsteam, and then we can relook it if we need the name in addition to the version. 

Otherwise closed: invalid
