### ISSUE TITLE
Error: ALCcaptureAlsa_start: start failed: File descriptor in bad state

### ISSUE THREAD

**Issue by v2e** [uTox/uTox#1088]
Hello!
My uTox is constantly giving me this error message if I try to call someone or test the sound for the second time:
`AL lib: (EE) ALCcaptureAlsa_start: start failed: File descriptor in bad state`
So when I start uTox, everything seems fine. I go to settings to test audio, push the phone button and the sound works properly. After that I stop the test and try to start it again. I hear a short clip in the speakers and than silence. Also the error message above appears on the console. And after that it is impossible to call anyone or to test sound until I restart uTox.

**Comment by redmanmale** [comment]
What's your uTox version?

**Comment by redmanmale** [comment]
Error maybe from [here](https://github.com/kcat/openal-soft/blob/master/Alc/backends/alsa.c#L1141).

**Comment by v2e** [comment]
My current version is 0.16.1

**Comment by zugz** [comment]
I'm experiencing the same behaviour with current git master. I checked that alcCaptureCloseDevice in audio.c:audio_in_device_close() is returning true, which should mean the device is closed correctly. And yet it fails to open a second time.

**Comment by v2e** [comment]
I am sorry to bother with a non-informative message, but this bug really has been preventing me from using uTox for several months already. Is there any hope for it to be fixed? Or maybe there could be some work-around?
Thanks!

**Comment by endoffile78** [comment]
@zugz @v2e do you guys use pulseaudio. I'm thinking maybe the problem has to do with not using pulseaudio. I'm using it and it works every time, another use reported this issue on IRC and is not using pulseaudio.

**Comment by v2e** [comment]
@endoffile78 no, I do not use Pulseaudio. By the way, it is still not clear for me whether this is a bug in ALSA libs or in uTox. Could someone perhaps explain this?

**Comment by endoffile78** [comment]
@v2e So far it seems that everyone effected by this uses alsa so its either that openal doesnt handle alsa correctly, an issue with alsa, or an issue with uTox.

**Comment by GrayHatter** [comment]
Re conversation in IRC and per the suggestion from @mannol I want to replace openal with port audio. Because we already have an issue for that, all of these will either be fixed, or invalid once #529 fixed.
