### ISSUE TITLE
Garbage in clipboard when copy non ASCII characters

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#1107]
**Steps to reproduce**
* open chat and copy some text with non ASCII characters
* paste it anywhere; at the end there would be some garbage: `��煱뺺䤷`

If that's not working try to copy different parts at the end of message.

tags: unicode, utf-8

**Env**
Win 7, 8.1 x64, uTox v.0.16.1

**Comment by cebe** [comment]
Works fine on Linux: Debian 8, Gnome 3, uTox 0.13.0

**Comment by redmanmale** [comment]
![Windows.](https://puu.sh/y7xYW/ffa6bc5d51.jpg)
