### ISSUE TITLE
Add a "poll" feature to group chat

### ISSUE THREAD

**Issue by WPFilmmaker** [uTox/uTox#1121]
Facebook groupchat have it and I think it can be very useful if there are various options (say a day for a meeting). Basically you click the icon and a small menu where you can enter options name and then publish it in the group chat. People then can vote and everyone sees the results in real time. Am I the only person who thinks it would be useful?

**Comment by GrayHatter** [comment]
No, uTox is fast, lightweight optimized client. Not a bloated, unwieldily/unusable app.
