### ISSUE TITLE
Inconsistent behavior when sending messages to offline contact

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#1125]
When some contact is offine all chat buttons are disabled and you could not send messages by pressing `Send` button.
But you could do it by pressing `Enter`.

It's an inconsistent behavior and it's bad.
We should either enable `Send` button or disable sending by `Enter`. I prefer the first option.

**Comment by GrayHatter** [comment]
@redmanmale go with the first option. I'd leave the colors as gray/disabled, but enable mdown for the button.
