### ISSUE TITLE
Unable to initiate a file transfer

### ISSUE THREAD

**Issue by frankE** [uTox/uTox#1129]
I'm under Ubuntu 17.10 with XFCE Desktop with latest static linked uTox Binary 0.16.1 for x64.
Whenever I click on the file transfer button nothing happens. Drag and drop doesn't work either.
I'm completly able to accept incomming file transfers but unable to initiate one by myself.

**Comment by endoffile78** [comment]
Is the contact online?
If yes can you run utox from the terminal like this: `utox -vvvvvv` and post the output. It will probably ouptut your id so redact that.

**Comment by frankE** [comment]
The contact is online. Here is the output from utox -vvvvvv:
`XLIB MAIN:    Setting theme to:	2
uToxAv:       Toxav thread init
XLib Tray:    Create Tray Icon
XLib Tray:    Resolution 128 128
XLib Tray:    Draw Tray
XLib Tray:    Incoming tray window event (28)
XLib tray:    Reached end of function, this is bad juju!
Toxcore:      Using unencrypted save file
Toxcore:      Creating New Toxcore instance.
		IPv6 : 1
		UDP  : 1
		Proxy: 0  0
XLib Tray:    NoExpose
Toxcore:      Bootstrapping with node 104.223.122.15 udp: 33445, tcp: 3389
Toxcore:      Bootstrapping with node 2607:ff48:aa81:800::35eb:1 udp: 33445, tcp: 3389
Toxcore:      Bootstrapping with node 51.254.84.212 udp: 33445, tcp: 33445
Toxcore:      Bootstrapping with node 2001:41d0:a:1a3b::18 udp: 33445, tcp: 33445
Friend:       Initializing friend list.
Friend:       Initializing friend: 0
Chatlog:      Can't malloc that much, you'll probably have to move or delete your history for this peer.
		Friend number ..., count 27, actual_count 1, start at 0, error size 2314885643650621815.

Filesys:      Could not open /home/frank/.config/tox/....fmetadata
Friend:       Meta Data not found ....fmetadata
Friend:       Initializing friend: 1
Filesys:      Could not open /home/frank/.config/tox/avatars/....png
Avatar:       Could not read: avatars/....png
Avatar:       Unable to get saved avatar from disk for friend ...
Friend:       New Alias set for friend ....
Friend:       Friendlist sucessfully initialized with 2 friends.
Self INIT:    Tox ID: ...
Filesys:      Could not open /home/frank/.config/tox/avatars/....png
Avatar:       Could not read: avatars/....png
Avatar:       Unable to get saved avatar from disk for friend ...
uTox Audio:   frame size: 960
XLib Tray:    ReparentNotify
XEMBED Tray:  ClientMessage on display 42078944
XEMBED Tray:  Format (32) as long 0 0 parent window 0 proto version 20971630 18446744073709551615
XLib Tray:    Reposition Tray
XLib Tray:    New geometry x 0 y 0 w 128 h 128
XLib Tray:    Setting to square
XLib Tray:    Draw Tray
Video:        desktop: 3200 1080
uToxVideo:    native_video_init() failed for desktop
XLib Tray:    NoExpose
XLib Tray:    Tray configure event
Tray:         Tray resized w:20 h:20

XLib Tray:    Draw Tray
XLib Tray:    MapNotify
XLib Tray:    Expose
XLib Tray:    Draw Tray
XLib Tray:    NoExpose
XLib Tray:    NoExpose
XLib Tray:    Expose
XLib Tray:    Draw Tray
XLib Tray:    Expose
XLib Tray:    Draw Tray
XLib Tray:    Tray configure event
Tray:         Tray resized w:22 h:22

XLib Tray:    Draw Tray
XLib Tray:    Expose
XLib Tray:    Draw Tray
XLib Tray:    NoExpose
XLib Tray:    NoExpose
XLib Tray:    NoExpose
XLib Tray:    NoExpose
uTox Audio:   input device list:
uTox Audio:   	G330 Headset Analog Mono
uTox Audio:   	Monitor of G330 Headset Analog Stereo
uTox Audio:   output device list:
uTox Audio:   	G330 Headset Analog Stereo
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: [fe80::c679:1893:8f14:d730]
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Updater:      Download size: 72
Updater:      Current version 4097, newest version version 4097.
Updater:      Running the latest version of uTox [0.16.1]
uTox:         Connected to DHT!
Toxcore:      Unencrypted save data written
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: [fe80::c679:1893:8f14:d730]
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Filesys:      Could not open /home/frank/.config/tox/...00.ftoutfo
FileTransfer: Loading outgoing 0, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...00.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...01.ftoutfo
FileTransfer: Loading outgoing 1, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...01.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...02.ftoutfo
FileTransfer: Loading outgoing 2, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...02.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...03.ftoutfo
FileTransfer: Loading outgoing 3, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...03.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...04.ftoutfo
FileTransfer: Loading outgoing 4, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...04.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...05.ftoutfo
FileTransfer: Loading outgoing 5, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...05.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...06.ftoutfo
FileTransfer: Loading outgoing 6, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...06.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...07.ftoutfo
FileTransfer: Loading outgoing 7, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...07.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...08.ftoutfo
FileTransfer: Loading outgoing 8, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...08.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...09.ftoutfo
FileTransfer: Loading outgoing 9, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...09.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...10.ftoutfo
FileTransfer: Loading outgoing 10, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...10.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...11.ftoutfo
FileTransfer: Loading outgoing 11, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...11.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...12.ftoutfo
FileTransfer: Loading outgoing 12, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...12.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...13.ftoutfo
FileTransfer: Loading outgoing 13, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...13.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...14.ftoutfo
FileTransfer: Loading outgoing 14, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...14.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...15.ftoutfo
FileTransfer: Loading outgoing 15, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...15.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...16.ftoutfo
FileTransfer: Loading outgoing 16, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...16.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...17.ftoutfo
FileTransfer: Loading outgoing 17, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...17.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...18.ftoutfo
FileTransfer: Loading outgoing 18, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...18.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...19.ftoutfo
FileTransfer: Loading outgoing 19, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...19.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...20.ftoutfo
FileTransfer: Loading outgoing 20, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...20.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...21.ftoutfo
FileTransfer: Loading outgoing 21, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...21.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...22.ftoutfo
FileTransfer: Loading outgoing 22, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...22.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...23.ftoutfo
FileTransfer: Loading outgoing 23, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...23.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...24.ftoutfo
FileTransfer: Loading outgoing 24, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...24.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...25.ftoutfo
FileTransfer: Loading outgoing 25, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...25.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...26.ftoutfo
FileTransfer: Loading outgoing 26, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...26.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...27.ftoutfo
FileTransfer: Loading outgoing 27, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...27.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...28.ftoutfo
FileTransfer: Loading outgoing 28, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...28.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...29.ftoutfo
FileTransfer: Loading outgoing 29, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...29.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...30.ftoutfo
FileTransfer: Loading outgoing 30, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...30.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/...31.ftoutfo
FileTransfer: Loading outgoing 31, deleting origin file.
Filesys:      removing file /home/frank/.config/tox/...31.ftoutfo
Filesys:      Could not open /home/frank/.config/tox/avatars/....png
Avatar:       Could not read: avatars/....png
Avatar:       Unable to get out avatar data to send to friend.
Tox Callbacks: Friend	0	--	Online (TCP)
Tox Callbacks: Friend	0	--	Name:	...
Tox Callbacks: Friend	0	--	Status Message:	Toxing on qTox
Tox Callbacks: Friend	0	--	State:	0
Tox Callbacks: Friend	0	--	Typing:	0
XLIB:         ButtonEvent: 16 1
XLIB:         ButtonEvent: 272 1
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: [fe80::c679:1893:8f14:d730]
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Tox Callbacks: Friend	0	--	Online (UDP)
XLIB:         ButtonEvent: 16 1
XLIB:         ButtonEvent: 272 1
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: [fe80::c679:1893:8f14:d730]
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
Toxcore:      TOXCORE LOGGING ERROR (2): Found node in LAN: 192.168.0.2
Toxcore:           in: /home/jenkins/workspace/libtoxcore-toktok_build_linux_x86-64_static_release/toxcore/toxcore/LAN_discovery.c:359
uTox:         Writing uTox Save
uTox:         Clean exit.
`
