### ISSUE TITLE
Aliases should be locally controlled

### ISSUE THREAD

**Issue by fare** [uTox/uTox#1136]
This utox blindly accepts the friend's alias, even after the friend was accepted.
I can change my name from "Mallory" to "Bob" after having been accepted as "friend" by Alice.
Or to "ABCDEF....", which is Bob's key.

This is very poor security.
Declared names should be in a different font from local names, and/or should always be preceded by the full ID, which should come first.

Full ID should only be elided if the alias is set by the local user.

**Comment by fare** [comment]
NB: I was using utox 0.16.1 from nixpkgs on Linux x64.

**Comment by redmanmale** [comment]
> utox blindly accepts the friend's alias

I don't see any problem with this behavior.

Users should be able to change their nicks at wish. And local alias won't change when user changes its nick.
When in doubt you could always check the ToxID in friend settings.

**Comment by fare** [comment]
There was no way to even set a local nick.

Users *should* be able to change their nicks, but their nicks should NEVER be remotely confusable with a local nick. They should be in a DIFFERENT font, and/or preceded by the ToxID.

**Comment by fare** [comment]
I don't see any way to change a local alias on Linux using utox 0.16.1, either. No right clicking available anywhere.

**Comment by fare** [comment]
If Mallory changes name to "Bob", the name should NEVER be shown the same way as the "*Bob*" I added as a local alias. It should say "*BAD7041D...* Bob" or "*Mallory* Bob"

**Comment by endoffile78** [comment]
To change a frieind's alias you right click on the friend and then choose friend settings. There will be an option to set an alias for the friend there.

**Comment by fare** [comment]
On Linux, there is no right click. On repeatedly trying, there seems to be a "midde click" that can be emulated on some mice by clicking both buttons at once, though it interferes with dragging. That's one bug.

Still, not distinguishing at the font level between aliases set locally or remotely is a SERIOUS SECURITY BUG. That's a MAJOR SECURITY ISSUE.

**Comment by fare** [comment]
Recommendation: the local alias (or if none, the ToxID or at least a few select digits from it) should ALWAYS be displayed, whatever the remote alias is. The remote alias should probably also always be displayed, *in a clearly distinguishable font*.

**Comment by fare** [comment]
Also, if the ToxID is not displayed in full, and if there are collisions on the parts displayed, a big fat security warning should be part of the displayed name if and when there is such a collision.

**Comment by redmanmale** [comment]
> Still, not distinguishing at the font level between aliases set locally or remotely is a SERIOUS SECURITY BUG. That's a MAJOR SECURITY ISSUE.

Nicks have nothing to do with security.

> if the ToxID is not displayed in full, and if there are collisions on the parts displayed

What collisions are you talking about? ToxID collisions with what?

**Comment by fare** [comment]
Collision between ToxID fragments if you don't display the entire painful thing.
Collision between whatever part of the ToxID you'd display, and whatever alias Mallory uses to social engineer Alice.

How you identify the party they discuss with to users has EVERYTHING to do with security. If Alice user can't distinguish between Bob and Mallory, you have failed Alice, badly.

**Comment by fare** [comment]
I repeat, if all it takes for Mallory to fool Alice is /nick Bob, your UI is pure trash.

**Comment by GrayHatter** [comment]
Take a breath, and search the issues. This has already been discussed before, and uTox is not meant to be the be all, end all of perfect security. Nor do I have any plans to try to force users into that broken mentality.

uTox will not require it's users to set an alias when adding friends. As @endoffile78 said, you can right click, and set an alias that will replace the one provided by your contacts. If you're unable to right click on a contact to get a context menu, we can see if that's a bug we can fix, otherwise there's no other fixable issue in this thread.

If this is a problem, you'll need to find another Tox client.

Wontfix

**Comment by GrayHatter** [comment]
I'm not going to unlock this issue or fix this issue. But if you can't right click, you're welcome to open a new issue.
