### ISSUE TITLE
Focus message input field when starting to type

### ISSUE THREAD

**Issue by avoidr** [uTox/uTox#1142]
There is no way that I see to set focus to the message input field with the keyboard. One has to use the mouse and click on the field.
I propose to set focus on keypress, so you never have to bother and typing just works.

**Comment by avoidr** [comment]
Actually, this program could use some keyboard accessibility in general. There is nothing as of yet, and I think it would increase comfort by a lot.

**Comment by GrayHatter** [comment]
👍 

This is the most annoying thing about uTox. Clicking anywhere shouldn't put the focus into the text box. But single clicking on the chat history of a friend absolutely should.
