### ISSUE TITLE
uTox (0.16.1) doesn't automatically create .config/tox

### ISSUE THREAD

**Issue by ThierryIT** [uTox/uTox#1156]
Hello,
No able to use uTox with my Mac.
I have installed it on Windows, Linux and Mac, seems to work (didn't fully test it yet) but not with my Mac.
It doesn't keep any of my settings including my uTox username, Tox ID etc.
Any ideas ?
Thx

**Comment by publicarray** [comment]
Strange, thanks for reporting. Can you run the following in the terminal and attach the output?

```sh
$ ls -l ~/.config/tox/
[...]
drwx------  5 seb  staff    160 16 May  2017 avatars
-rw-r--r--  1 seb  staff  11585 28 Dec 22:00 tox_save.tox
-rw-r--r--  1 seb  staff    344 28 Nov 20:45 utox_save
-rw-r--r--  1 seb  staff    721 28 Nov 21:16 utox_save.ini
-rw-r--r--  1 seb  staff      0 30 Apr  2017 utox_theme.ini
$ /Applications/uTox.app/Contents/MacOS/utox -vvvvv
```

Feel free to remove any Tox IDs from the output.

**Comment by ThierryIT** [comment]
Hi,

.config/tox doesn't exist:

imac:~ thierry$ /Applications/utox.app/Contents/MacOS/utox -vvvvv
Settings:     Unable to open utox_save.
Settings:     unable to load utox_save data
uToxAv:       Toxav thread init
OSX Drawing:  Using .HelveticaNeueDeskInterface-Regular fontfamily
OSX:          339104
Filesys:      Could not open /Users/thierry/.config/tox/tox_save.tox
Filesys:      Could not open /Users/thierry/.config/tox/tox_save.tox.atomic
Filesys:      Could not open /Users/thierry/.config/tox/tox_save.tmp
Filesys:      Could not open /Users/thierry/.config/tox/tox_save
Toxcore:      Creating New Toxcore instance.

Thx

**Comment by endoffile78** [comment]
@ThierryIT Create .config/tox and try and again.

**Comment by ThierryIT** [comment]
Hi,

I have created by hands all files who where suppose to be in the folder
"tox".
Seems now to work.

Thx


On 28/12/2017 18:35, Endoffile wrote:
> @ThierryIT Create .config/tox and try and again.
> 



--

**Comment by endoffile78** [comment]
Ok cool this folder should be create automatically so I'm going to change this issue to that.

**Comment by redmanmale** [comment]
@publicarray Are you willing to take this?

**Comment by publicarray** [comment]
Yea I'll look into it soon. Thanks for reminding me :)
