### ISSUE TITLE
Announcing Fedora package

### ISSUE THREAD

**Issue by eclipseo** [uTox/uTox#1160]
Hey,

I packaged uTox for Fedora, it is available on Fedora 27 and the development version Rawhide.

Simply type as root:
```
dnf install utox
```

to get it.

**Comment by robinlinden** [comment]
That's awesome! Thank you so much for packaging it!
Look at the [utox.spec](https://github.com/eclipseo/packaging/blob/master/utox.spec), I guess you'll have to manually update it every time there's a release?

**Comment by eclipseo** [comment]
Yes, I'll update it at every release. It should be monitored by Fedora Release monitoring tool: https://release-monitoring.org/project/13739/
