### ISSUE TITLE
Implement correcting the last message

### ISSUE THREAD

**Issue by endoffile78** [uTox/uTox#1168]
A message correction type was recently added to toxcore. https://github.com/TokTok/c-toxcore/pull/685

**Comment by redmanmale** [comment]
* Context menu item
* Editing by pressing `Arrow-Up` while empty text edit is in focus

**Comment by endoffile78** [comment]
Message correction was reverted: https://github.com/TokTok/c-toxcore/pull/748. Closing this issue until it is readded.
