### ISSUE TITLE
uTox don't save settings if the Windows user account contains diacritics

### ISSUE THREAD

**Issue by SupremeAMS** [uTox/uTox#1178]
### Overview

1. uTox version: 0.16.1
2. Operating system: Windows 7 64 bit SP1

### Issue

-Create a Windows account with diacritics (é è ë ê ç ...) in the name (for example _Joëlle_).
-Start uTox under this account. 
-Modify any setting to force the save data creation.

uTox create the data directory (for example _C:\Users\Joëlle\AppData\Roaming\Tox_) correctly but failed to create _tox_save.tox_ and _utox_save_.

**Comment by GrayHatter** [comment]
@robinlinden @redmanmale

**Comment by redmanmale** [comment]
Same as #733.
