### ISSUE TITLE
Reconsider Android support

### ISSUE THREAD

**Issue by endoffile78** [uTox/uTox#1183]
The android version isn't really maintained, it's often forgotten about when adding features and fixing bugs.

**Comment by GrayHatter** [comment]
It's experimental at best. I agree it should be deprecated, but I'd VERY much like to keep the code base in the repo. For those days when I hate myself enough to interact with the JVM in native C.

Thoughts on ignoring it when adding features, etc. If it goes out of date, I'll just have to update it when/if I want to hack around in it?

**Comment by endoffile78** [comment]
Yeah I think we should just ignore it, its ignored most of the time anyways.

**Comment by avoidr** [comment]
Yup, we're ignoring it.
