### ISSUE TITLE
uTox as AppImage

### ISSUE THREAD

**Issue by Nokia808** [uTox/uTox#1188]
Hi. I would like to suggest on kind developer - if can - making uTox available as AppImage. 

I suggesting this because I noticed - correct to me - that Tox applications have deficiency in packaging & packagers. So, instead of making special package for each distros. (for Debian, for Ubuntu, for Fedora, for openSUSE, .........) it will be much easier to make a single AppImage which run on almost all Linux distros, isn't it?

It seem to me that AppImage will be very good option to uTox taking in mind that uTox is lightweight application with minimum dependencies .......

If uTox remain not available unless by building it from source code, then it will be limited in use ......

Best.

**Comment by phd21** [comment]
Hi GrayHatter and uTox,

+1 for providing an AppImage package, although downloading the archive file, extracting it and running the utox executable program file is pretty good too..

Best regards,
Phil
phd21mint@gmail.com

**Comment by avoidr** [comment]
Please use your distro's repository. And if your distro doesn't package uTox, please request it there. It enables uTox for many more users in a standard and distro-supported way.

Thank you.
