### ISSUE TITLE
Crashes after selecting the file location at receivers end

### ISSUE THREAD

**Issue by zero-master** [uTox/uTox#1194]
### Overview

1. uTox version: 0.16.1
2. Operating system:  4.15.11-1-ARCH #1 SMP PREEMPT  x86_64 GNU/Linux
3. Desktop Environment/Window Manager (Linux/BSD only): GNOME

The sender sends a file -> Message arrives with the file at receiving end -> Receiver select the folder, just after selecting the folder, utox abruptly exits.

**Comment by redmanmale** [comment]
Looks like a problem with GTK in uTox which was fixed in #1009, but wasn't released yet.
You could try build from `develop` branch.

**Comment by zero-master** [comment]
Building from source is outside my expertise.

I installed it from here: 
https://www.archlinux.org/packages/community/x86_64/utox/
