### ISSUE TITLE
Empty third-party/minini in 0.17.0 tarball

### ISSUE THREAD

**Issue by cwilling** [uTox/uTox#1204]
### Overview

1. uTox version: 0.17.0
2. Operating system: Linux
3. Desktop Environment/Window Manager (Linux/BSD only):

### Issue

Tarball uTox-0.17.0.tar.gz has an empty third-party/minini directory resulting in cmake failure:
```
CMake Error at CMakeLists.txt:324 (add_executable):
  Cannot find source file:

    third-party/minini/dev/minIni.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
```
From CMakeLists.txt, it looks like empty thrid-party/qrcodegen will also be a problem.

**Comment by cwilling** [comment]
I gather there's no way to include submodules in the source tarball of a project release on github. To work around this problem I made a separate tarball of the contents of the third-party directory and unpack that into the unpacked release tarball at build time.

While this would work well enough for the uTox build script which I maintain at SlackBuilds.org, it's not ideal that a second _unofficial_ tarball needs to be downloaded from somewhere to complete the build (especially for a security conscious project). Could I suggest that you add a uToxThirdParty-0.17.0.tar.gz to your release page? That would make it official.

To make the tarball, I just cloned the project and then ran `git submodule update --recursive` in it to populate the third-party directory; then `tar zcvf uToxThirdParty-0.17.0.tar.gz --exclude=".git*" third-party` to make the tarball. You could then edit your release page and drag & drop the tarball into the area where it says ` Attach binaries by dropping them here or selecting them`, thus making it downloadable along with the standard release tarball.

Is something like that a possibility?

**Comment by GrayHatter** [comment]
@endoffile78 @robinlinden anyone still using the build->tag->deploy scripts for signing releases?

Perhaps this is something that should be added to the "official script"?

**Comment by robinlinden** [comment]
I went ahead and attached a .tar.gz with the uTox source and the required 3rd-party submodules to the release. We'll have to do something cleaner for next release.

**Comment by cwilling** [comment]
Thanks, that works.

Note that unpacking the -full tarball creates a plain "uTox" directory rather than uTox-$VERSION. It's not a big problem but perhaps something to consider for the cleaner fixes for future releases.

**Comment by GrayHatter** [comment]
that's something that probably should be handled by the packager software.
