### ISSUE TITLE
Unable to change avatar.

### ISSUE THREAD

**Issue by fling-** [uTox/uTox#1221]
### Overview

1. uTox version: 0.16.1
2. Operating system: Debian sid in lxd
3. Desktop Environment/Window Manager (Linux/BSD only): none

### Issue
Not sure how to change the avatar.
Tried clicking on the head where the avatar should be but nothing happened.
Am I missing a file selection dialog because of some dep missing?

**Comment by endoffile78** [comment]
Do you have gtk installed?

**Comment by fling-** [comment]
@endoffile78 not sure. Which package do I need exactly?

**Comment by endoffile78** [comment]
gtk version 3 is required for changing icons linux, it's needed for the file picker.  Run this to install it:

```
sudo apt-get install libgtk3-bin libgtk3-dev
```

**Comment by fling-** [comment]
@endoffile78 installing libgtk-3-dev fixed the issue.

**Comment by fling-** [comment]
What is the proper place for documenting this dependency?

**Comment by endoffile78** [comment]
The dependencies are listed [here](https://github.com/uTox/uTox/blob/develop/docs/INSTALL.md#unix-like) but there might be better place for them.
