### ISSUE TITLE
Updater thinks 0.16.1 is the latest version

### ISSUE THREAD

**Issue by fling-** [uTox/uTox#1223]
### Overview

1. uTox version: 0.16.1
2. Operating system: Debian sid
3. Desktop Environment/Window Manager (Linux/BSD only): none

### Issue
Enabling 'Automatically Update uTox' switch will not update past 0.16.1 as no more newer builds available https://github.com/uTox/uTox/issues/1220#issuecomment-390106853

```
Updater:      Download size: 72
Updater:      Current version 4097, newest version version 4097.
Updater:      Running the latest version of uTox [0.16.1]
```

**Comment by avoidr** [comment]
The updater has been removed in v0.17.2 (3d1b1df7b557b29d470f9d8af790f00159582dda).
