### ISSUE TITLE
Possible move to gitlab?

### ISSUE THREAD

**Issue by colt0** [uTox/uTox#1235]
Im not going to state the obvious reasons here why you should move away from github but just asking if you have any intentions of moving to Gitlab or another platform?
thanks

**Comment by redmanmale** [comment]
Personally I don't see any _obvious_ reasons to do that.

**Comment by GrayHatter** [comment]
Yeah, I'm with @redmanmale there are no obvious reasons, however. We've already been using gitlab for a long time. We also have additional private repos hosted else where as well.

https://gitlab.com/uTox/uTox/

uTox will be staying on github until it starts adding additional work to maintaining the repo.

**Comment by GrayHatter** [comment]
Or there's a better alternative, related to features and function.
