### ISSUE TITLE
uTox 0.17.0 ASAN:DEADLYSIGNAL

### ISSUE THREAD

**Issue by sagax** [uTox/uTox#1237]
### Overview

1. uTox version: 0.17.0
2. Operating system: x86 openSUSE
3. Desktop Environment/Window Manager (Linux/BSD only): Xmonad

---

1. <b>git clone --recursive git://github.com/uTox/uTox.git && cd uTox</b>
2. <b>git checkout v0.17.0</b>
3. <b>mkdir build && cd build</b>
4. <b>cmake -DTOXCORE_STATIC=ON ..</b>  [link to report 1](http://susepaste.org/75861455) and [link to report 2](http://susepaste.org/82679549)
5. <b>make</b> [link to report 1](http://susepaste.org/56443046) and [link to report 2](http://susepaste.org/55398112)
6. <b>./utox</b>

and i got [this](http://susepaste.org/16441568). and with <b>strace</b> [this](http://susepaste.org/60988172)

[this](http://susepaste.org/65847959) <b>ldd ./utox</b> output

**Comment by endoffile78** [comment]
You can turn ASAN off run:

`cmake -DTOXCORE_STATIC=ON -DENABLE_ASAN=OFF ..`

**Comment by sagax** [comment]
Yes, it's helped me. But, what "libasan" doing?

**Comment by endoffile78** [comment]
It's for debugging, it doesn't add anything of value for the regular user.
