### ISSUE TITLE
Can't save files

### ISSUE THREAD

**Issue by ArcticFox930** [uTox/uTox#1242]
### Overview

1. uTox version:  Latest
2. Operating system:  Android 4.4.2
3. Desktop Environment/Window Manager (Linux/BSD only):

### Issue

No matter what I do or what setting I change, I can't save any files that I receive on the android client.

**Comment by redmanmale** [comment]
I fear this feature is unsupported on Android for now.

It shouldn't be to hard to fix it though (just write one function https://github.com/uTox/uTox/blob/master/src/android/main.c#L233).

**Comment by GrayHatter** [comment]
> shouldn't be too hard

The NDK on android has been more or less deprecated by android. if anyone want's to TRY to do this. I'd be very happy to provide support. But it's likely to be difficult.

**Comment by avoidr** [comment]
Android hasn't been touched for a long time and there are much better clients for Android out there these days.
