### ISSUE TITLE
Unintuitive behaviour of home key

### ISSUE THREAD

**Issue by avoidr** [uTox/uTox#1245]
### Overview

1. uTox version: 65309e3711c8c8a4d29140aa8eb568b8415eee3b
2. Operating system: GNU+Linux
3. Desktop Environment/Window Manager (Linux/BSD only): dwm

### Issue

The current behaviour of the `pos1` key is that it always makes the cursor go to the beginning of the whole input field. The intuitive (and usual) thing is to have the cursor go to the beginning of *the current line*.

Compare that to the behaviour of the `end` key, which currently (and correctly) makes the cursor go to the end of the current line.

**Comment by GrayHatter** [comment]
what's `pos1` ?

**Comment by avoidr** [comment]
Sorry, I probably mean the `home` key, which opposes the `end` key. I have a german keyboard.
