### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by lottery2018** [uTox/uTox#1246]
/cygdrive/c/projects/utox/src/flist.c: In function ‘find_item_shown_index’:
/cygdrive/c/projects/utox/src/flist.c:239:27: warning: comparison between signed and unsigned i                                                                     nteger expressions [-Wsign-compare]
         if (shown_list[i] == it - item) { // (it - item) returns the index of the item in the                                                                      full items list

**Comment by avoidr** [comment]
That is only a warning. Does compilation actually fail?

**Comment by lottery2018** [comment]
Compilation will not fail,However, running exe will abort,i sys x32

**Comment by avoidr** [comment]
What is your operating system?
Which version/commit are you on?
What do you do to make the program abort? When does it happen?
Is it only the 32-bit version that fails?

**Comment by lottery2018** [comment]
@avoidr 

 

![Uploading QQ截图20180616165546.png…]()





 my target is x32 not x64

**Comment by lottery2018** [comment]
![image](http://chuantu.biz/t6/329/1529140241x-1404793573.png)

![image](http://chuantu.biz/t6/329/1529140270x-1404795780.png)


 you can see my img

**Comment by lottery2018** [comment]
Sorry, I found the reason, the compiled 32-bit can't run on a 64-bit system

**Comment by avoidr** [comment]
Very good. You can close this issue, then.

**Comment by GrayHatter** [comment]
> Sorry, I found the reason, the compiled 32-bit can't run on a 64-bit system

This should be incorrect, perhaps there was a library arch mismatch?
