### ISSUE TITLE
Impossible to pick dropdown list items, if whole list doesn't fit on screen

### ISSUE THREAD

**Issue by avoidr** [uTox/uTox#1247]
### Overview

1. uTox version: 7bbe82b34ae7fb1c2114e6bd5b0451826fee0c11
2. Operating system: GNU+Linux
3. Desktop Environment/Window Manager (Linux/BSD only): dwm

### Issue

The language dropdown list easily doesn't fit on my screen if I pick the bottommost item. Then, to pick the topmost item again, I have to "climb" up the list, picking the top items a few times.

**Comment by redmanmale** [comment]
This is an intentional behavior (see #465 and https://github.com/uTox/uTox/issues/789#issuecomment-291206659).

Personally I also don't like it but couldn't fix it myself.

**Comment by GrayHatter** [comment]
closed as dup for #465
