### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by lottery2018** [uTox/uTox#1249]
### Overview

1. uTox version:0.17
2. Operating system:win10

### Issue

How do I remove the console that displays the logs

**Comment by GrayHatter** [comment]
for anyone following, cmake needs a WIN GUI option set, otherwise you'll get a console window at launch

**Comment by ArkYk** [comment]
> 对于任何关注者，cmake需要一个WIN GUI选项集，否则你将在启动时获得一个控制台窗口

How to do it?Please Elaborate
