### ISSUE TITLE
utox requested i send bug report after friend went offline

### ISSUE THREAD

**Issue by scallyob** [uTox/uTox#1251]
### Overview

1. uTox version: 0.16.1
2. Operating system: Qubes OS 4.0/ Whonix 13 VM
3. Desktop Environment/Window Manager (Linux/BSD only): i3wm/xfce

### Issue

Told me to file a bug report. This happened when one of my friends went offline. Here's what it said:
Toxcore:      Error sending message... 3
get_group:     index: 0 is out of bounds.
Group callback: gid 0 pid 0 change 0
Group callback: gid 0 pid 0 change 2
Group callback: gid 0 pid 1 change 0
Group callback: gid 0 pid 1 change 2
Group callback: gid 0 pid 2 change 0
Group callback: gid 0 pid 2 change 2
Group callback: gid 0 pid 2 change 2
XLib Event:   Type UTF8_STRING || Prop TARGETS 
Group callback: gid 0 pid 1 change 2
Group callback: gid 0 pid 0 change 2
XLIB:         X11 err:	X11 tried to kill itself, so I hit him with a shovel.
XLIB:             err:	Resource: 0 || Serial 5432875
XLIB:             err:	Error code: 3 || Request: 4 || Minor: 0
uTox:         This would be a great time to submit a bug!
uToxAV:       Change state with an error, this should never happen. Please send bug report!
XLIB:         X11 err:	X11 tried to kill itself, so I hit him with a shovel.
XLIB:             err:	Resource: 0 || Serial 5434549
XLIB:             err:	Error code: 3 || Request: 4 || Minor: 0
uTox:         This would be a great time to submit a bug!
Group callback: gid 0 pid 2 change 1

**Comment by redmanmale** [comment]
Dup of #1224.
