### ISSUE TITLE
uTox won't connect wirelessly on xubuntu 16.04

### ISSUE THREAD

**Issue by mlnease** [uTox/uTox#1254]
### Overview

1. uTox version:
2. Operating system:
3. Desktop Environment/Window Manager (Linux/BSD only):

### Issue

Hello,

I'm sorry that I don't know my uTox version and don't know how to determine it.  

My OS is xubuntu 16.04 and my DE is xfce4

I installed uTox from an old download I had called 'utox_linux_i686'.  I don't remember where I got it.  It always worked fine for messaging, though I never got audio or video.  I would be content to restore the messaging function.

Presently it opens normally and recognizes my Tox ID and that of my sole correspondent--but I can't get it to connect to my wireless router.

Any help would be greatly appreciated--thanks in advance. 

p.s.  I couldn't get uTox to work at all on xubuntu 18.04 and reinstalled 16.04 on a separate partition partly in hopes of keepin uTox.

**Comment by GrayHatter** [comment]
Is it JUST uTox that doesn't connect via wifi? Where other applications work as expected?

**Comment by mlnease** [comment]
Thanks for the response.  Yes, only uTox--everything else connects normally.

**Comment by GrayHatter** [comment]
what version of uTox are you using?

**Comment by GrayHatter** [comment]
you can find out by running uTox from a terminal with `utox -vvvv` and pasting the output here

**Comment by mlnease** [comment]
```
mn@mn-OptiPlex-745:~$ utox -vvv
Read 16 bytes (/home/mn/.config/tox/utox_save)
new tox object ipv6: 1 no_udp: 1 proxy: 0  0
Read 17145 bytes (/home/mn/.config/tox/tox_save)
File not found (/home/mn/.config/tox/C14849FA2D21CA1046F2778BF356083109081D9E6945929D8E289E68DF499B04.txt)
Tox ID: B839C2095B64E4BDF6A3E3CDF1988BAAAA33E070B4B81168BAF963D4DE90DC4C1862CC1E4AAB
frame size: 960
desktop: 1280 1024
Loaded font /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf 0 30 -7
Input Device List:
Built-in Audio Analog Stereo
Monitor of Built-in Audio Analog Stereo
expose
Output Device List:
Built-in Audio Analog Stereo
AL lib: (WW) alcCloseDevice: Releasing context 0xf5f05270
AL lib: (WW) FreeContext: (0xf5f05270) Deleting 16 Source(s)
Saved data
av_thread exit, tox thread ending
clean exit
mn@mn-OptiPlex-745:~$ 

```

**Comment by mlnease** [comment]
Even I can see I've made a mess of the installation.  I wonder if I should just delete all my uTox files and start from scratch>

**Comment by mlnease** [comment]
I created C14849FA2D21CA1046F2778BF356083109081D9E6945929D8E289E68DF499B04.txt and moved it to /home/mn/.config/tox/.  The output of utox -vvvv is now

```
mn@mn-OptiPlex-745:~$ utox -vvvv
Read 16 bytes (/home/mn/.config/tox/utox_save)
new tox object ipv6: 1 no_udp: 0 proxy: 0  0
Read 17145 bytes (/home/mn/.config/tox/tox_save)
Read 69 bytes (/home/mn/.config/tox/C14849FA2D21CA1046F2778BF356083109081D9E6945929D8E289E68DF499B04.txt)
loaded backlog: 46F2778BF356083109081D9E6945929D8E289E68DF499B04.txt
: 
Tox ID: B839C2095B64E4BDF6A3E3CDF1988BAAAA33E070B4B81168BAF963D4DE90DC4C1862CC1E4AAB
frame size: 960
desktop: 1280 1024
Input Device List:
Built-in Audio Analog Stereo
Monitor of Built-in Audio Analog Stereo
Loaded font /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf 0 30 -7
Output Device List:
Built-in Audio Analog Stereo
Loaded font /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf 0 30 -7
expose
AL lib: (WW) alcCloseDevice: Releasing context 0xf5f09a58
AL lib: (WW) FreeContext: (0xf5f09a58) Deleting 16 Source(s)
Saved data
av_thread exit, tox thread ending
clean exit
mn@mn-OptiPlex-745:~$ 
```

Thanks for your time and attention.

**Comment by GrayHatter** [comment]
@uTox/devs anyone else have thoughts? I'm completely lost as to why uTox wouldn't connect...

**Comment by mlnease** [comment]
Thanks for the continued interest GH--did my output look right?

**Comment by avoidr** [comment]
Does uTox work when you connect with a cable?
Does uTox work when you connect to a different wifi?

**Comment by publicarray** [comment]
Is there a firewall on the machine? tox needs outbound and inbound connections.
Is there a firewall on the router blocking inbound connections?
Do other peer-to-peer protocols work? (I assume NAT environment)

**Comment by publicarray** [comment]
>  Is utox_linux_i686.tar.xz the package I should be using? 
That depends on your CPU architecture. you can check with `uname -p`

**Comment by mlnease** [comment]
Thanks All -- replies in order:
I haven't tried connecting by cable as to do so would require dismantling my desktop, moving it downstairs to the other end of the house and reassembling it there.  I'll do this as a last resort but will try other remedies first.  I only have one wifi connection here so can't test this.  Thanks for your response.

There is a firewall on the machine (ufw); I disabled it and still can't connect.
There's no firewall on the router (that I'm aware of--not sure how to check)--I haven't noticed any other inbound connections being blocked.

Output of `uname -p` is `x86_64`

Thanks, all!

**Comment by publicarray** [comment]
Hm if you can't change the network can you try a different machine? If you have a phone you can try using it's hotspot functionality temporarily to test if the problem is with the computer or the network. I'm also at a loss at what is wrong.

NAT is just means that you are behind a router and share an IP address. uTox will still work fine when inbound connections are blocked. It just means you are not a peer. Sorry about my earlier firewall questions. They don't matter as much as I thought they did.

> Output of uname -p is x86_64

Than you probably want `utox_linux_x86-64.tar.xz`. It should not impact connectivity though. You might get better performance thats all.

**Comment by mlnease** [comment]
Thanks for this.  My android tablets and my wife's laptop both connect fine via the wireless router--in fact, anTox works fine on the tablets and uTox works fine on Herself's laptop.  And yes, we're all behind a router and do share an ip address.  

I think it's clear there was something wrong with my initial installation this time.  Besides the connection problem, uTox has never show up in my xfce4 Applications Menu.  It did when I had it working before.

I think I'll try once again deleting all my uTox files and reinstalling using `utox_linux_x86-64.tar.xz` with the directions at https://www.linux.com/learn/tox-your-new-secure-chat-application.  I'll of course report my results here.

Thanks again for your time and attention.

**Comment by avoidr** [comment]
>Will it suffice just to extract the files into my Download directory?

Yes, it will suffice. Where you extract it, doesn't matter.

>I think the problem is that the installation has a bad Tox ID--it doesn't match that on my anTox. But I can't see how to change my uTox ID on my...bad install. Each time I've reinstalled uTox (on 16.04), it appears with the ID I think is wrong. Any ideas?

The ID can't be "wrong". It can only be different. The Tox ID is randomly generated with each time you create an account. And the ID is done by all Tox programs separately. It is just a random very large number. You cannot pick it. You can only generate another random number. Of course if you delete your old account and create a new one, you will also have a new number, and a different one for sure.

Tox IDs aren't created from anything persistent that would make them reproducible. They are random on purpose, and there is no "wrong" ID. If you could pick a number at will, that would also mean that you could find any encryption key of other users and break their security. That is not what you want. You want unpredictable and unguessable numbers (keys).

**Comment by mlnease** [comment]
Thanks--I understand now about the ID.
