### ISSUE TITLE
Web-based portable utox and toxcore

### ISSUE THREAD

**Issue by username1565** [uTox/uTox#1258]
### Overview

1. uTox version: 0.7.0 - stable version, isotoxin.im
2. Operating system: Windows XP

### Issue

Hi developers! Can you add web-interface to the tox or portable utox, like this: https://raw.githubusercontent.com/codedust/WebTox/master/screenshot.png
Here is source code: https://github.com/codedust/WebTox
and there is server-side code, writed as .go files.
This must to be compiled and this is a different server.
Go installer have over 100 MB size
Tox is P2P but this is not web-based chat,
and there is, inside the tox, already exists server-side soft.

That means this web-interface can be integrated inside the each peer.
In this case utox communication between users
can be really p2p, through WebRTC, WebSockets, XHR-requests, etc,
and can working in LAN,
if ONLY 1 tox-node there is in Network, as server.

No need any servers in this case.
All info can be encrypted, using SSL, or HTTP + NaCl encryption.
Only JS+HTML there is decrypted shared files, and after generate toxID or import
the keys data can be decrypted and give full communications with the node peer.

Also, if web-user was been connected to the node, he can receive DHT,
then save this in cookies or temporary files,
and through keep-alive connection he can share this to another web-peers,
or come back to the node.
If he do sharing DHT to another peers, then node can working as simply relay or STUN-server.
This significantly offloads the node.

For example, this chat https://github.com/ScaleDrone/webrtc-text-chat-tutorial/
working like web-based p2p chat, but when Internet connection exists.
Else this not working, and in script.js you can see this:
stun:stun.l.google.com:19302

This is just a STUN server for making peer exchange through NAT:
https://gist.github.com/mondain/b0ec1cf5f60ae726202e

Also you can add import/export Private key NaCl.

Best regards and have a nice day.

**Comment by GrayHatter** [comment]
Not possible by design. The tox protocol dosen't allow for this, and never will.

Anyone who says different is lying to you, and possibly trying to break the security of your tox keys.
