### ISSUE TITLE
Cannot build µTox 0.17.0 on Gentoo

### ISSUE THREAD

**Issue by TheChymera** [uTox/uTox#1263]
### Overview

1. uTox version: 0.17.0
2. Operating system: Gentoo Linux
3. Desktop Environment/Window Manager (Linux/BSD only): GNOME

### Issue

Will not build, see [log](https://bpaste.net/raw/d674d14064da).
This issue does not occur with 0.16.1

**Comment by robinlinden** [comment]
uTox now contains a bunch of git submodules, so when cloning it, you have to pass the `--recursive` flag to get all of the source code.

Like so: `git clone --recursive git://github.com/uTox/uTox.git`

**Comment by robinlinden** [comment]
I'm not sure how we're meant to handle GitHub archives leaving things out. Last release, I uploaded the result of a `git clone --recursive` here: https://github.com/uTox/uTox/releases/download/v0.17.0/uTox-0.17.0-full.tar.gz but I'm not sure what the plan for the future is.

**Comment by TheChymera** [comment]
It would be cool if the source archive for the release would contain all the data needed to build the release. Else you should maybe list the multiple source archive addresses.

In any case this seems to have helped with cpmpilation, but [it still fails](http://bpaste.net/show/44a5a4acfda1). Apparently some tox-core incompatibility?

**Comment by eclipseo** [comment]
`error "Unable to compile uTox with this Toxcore version. uTox expects v0.2.*!"`

Yeah you need an up-to-date toxcore.

**Comment by TheChymera** [comment]
@eclipseo - you mean from here? https://github.com/TokTok/c-toxcore/releases

**Comment by robinlinden** [comment]
Yeah, anything after 0.2.0 will work.
