### ISSUE TITLE
APPCRASH when checking or unchecking boxes under Advanced menu.

### ISSUE THREAD

**Issue by zellchristensen** [uTox/uTox#1266]
### Overview

1. uTox version: 0.16.1
2. Operating system: Windows 7

### Issue

Under the Advanced options tab, for any of the first four options, clicking the checkbox too often or too fast causes the program to crash.  The options are "IPv6", "UDP", "Proxy (SOCKS 5)", and "Force uTox to always use proxy". None of the other checkboxes under Advanced or the other tabs seem to have issues.

It also crashed once when unchecking "Force uTox to always use proxy" after a proxy was set and force was turned on.  It doesn't seem to happen consistently all of the time though.

**Comment by avoidr** [comment]
Related to infamous #1252
Thank you for your report.
