### ISSUE TITLE
Fix snprintf

### ISSUE THREAD

**Issue by avoidr** [uTox/uTox#1282]
```
$ ack 'snprintf' | wc -l
102
```

That's how much duplicate code there is in uTox. That's how many bugs there are.

I'm tired of seeing the same shit wrong pasta all over the fucking program, and I'm not fixing every single instance of this bug. This needs to be put into a function or a macro.

**Comment by GrayHatter** [comment]
> This needs to be put into a function or a macro.

No, people need to be less shit. Myself included obviously

**Comment by avoidr** [comment]
There is either fixing up to 102 instances of this bug and producing different pasta, or making a function or macro and trivially fixing those bugs and preventing code bloat and pasta.

This isn't only about people being shit.

**Comment by avoidr** [comment]
Actually reopening because this needs fixing, but not in the way I proposed.

**Comment by avoidr** [comment]
I checked now, and I see most of the `snprintf`s being used with one or the other wrong assumption.
I don't see verifying of the return value all that often. But `strnlen` is all that it takes, and it is more explicit and reading it flows easier.
In almost all cases `snprintf` is passed a string length, not the buffer length.

Here is one example:
```C
char buf[TOX_MAX_NAME_LENGTH];
int  text_length = snprintf((char *)buf, TOX_MAX_NAME_LENGTH, "%.*s, ", (int)peer->name_length, peer->name);
```
If `TOX_MAX_NAME_LENGTH == peer->name_length`, then `text_length == TOX_MAX_NAME_LENGTH+2` and `buf == [peer->name with last character \0'd]`.

So the output is more like `"avoid🖕🖕"` rather than `"avoidr, "`.

**Comment by avoidr** [comment]
```
$ ack 'snprintf' | grep -i 'length' | wc -l
69
```
