### ISSUE TITLE
Exported QR code image is way too small

### ISSUE THREAD

**Issue by avoidr** [uTox/uTox#1295]
The image is currently: `PNG image data, 37 x 37`
The image file should be scaled up and sharp like in the uTox UI.
Perhaps it can be exported as SVG.

uTox version: 0.17.0, a57b23864f71de2fad33c341f3b83ea1c607a63f

**Comment by redmanmale** [comment]
It could be zoomed in any image viewer.
I tried it on Windows and some Ubuntu.
