### ISSUE TITLE
Windows: send file size bug

### ISSUE THREAD

**Issue by Vityacv** [uTox/uTox#1298]
### Overview

1. uTox version: 0.16 -> master
2. Operating system: windows

### Issue

If file size is larger than 0x7FFFFFFF conversion between size_t to uint64_t results to this (![t](https://user-images.githubusercontent.com/20649019/46664197-d353cd00-cbaf-11e8-8a74-6d8683e91177.png)) bug - file size became negative number.
i suggest to change size_t size = ftello(file); -> uint64_t size = ftello64(file); in file_transfers.c

**Comment by redmanmale** [comment]
> i suggest to change size_t size = ftello(file); -> uint64_t size = ftello64(file); in file_transfers.c

It сould be a great PR from you.

**Comment by avoidr** [comment]
To my understanding, this would not be a great PR.

Here is my understanding (I've read about it for a bit now):

- The OP's operating system is 32-bit, so ftello() return value is 32-bit (signed).

- ftello64() is platform-specific.

- ftello() is 64-bit on 64-bit platforms. 32-bit platforms can set a macro to make ftello() 64-bit.

**Comment by redmanmale** [comment]
It could be done like all other platform-specific stuff:
* declaration in ```native/filesys.h```
* platform-specific implementations in ```filesys.c``` for each platform

And, speaking of this possible PR, I didn't mean a specific implementation, just general cheer up.

**Comment by Vityacv** [comment]
i found out that mingw have _FILE_OFFSET_BITS constant set to 32 by default (sizeof(off_t) is 4). GCC is 64
so to fix this just add after #define FILE_TRANSFERS_H:
#define _LARGEFILE_SOURCE
#define _FILE_OFFSET_BITS 64
to src/file_transfers.h
