### ISSUE TITLE
Cross client uTox Id migration request

### ISSUE THREAD

**Issue by vlc33** [uTox/uTox#1303]
Hello, sorry if this is not the place to ask for this, but I'm new, thank you.

May I ask uTox project to allow cross-client uTox-Id (and maybe contacts) load/save say, be able to transmit my Id through different devices and uTox clients.

I know it is possible to do so in PC-PC and in Android-Android scenarios but obviously cross device/OS would be perfect.

**Comment by redmanmale** [comment]
There's no limit to/from which device/OS you could copy-paste your tox save file.
All clients use the same save file format by Tox standart.

**Comment by vlc33** [comment]
Thank You,

My problem was that I used DropBox to transfer tox_save.tox between Win and Android, but in Android DropBox doesn't had write permissions, so it saved empty files, so there was an error.

Now it works thank you.
