### ISSUE TITLE
build utox on windows

### ISSUE THREAD

**Issue by ArkYk** [uTox/uTox#1305]
### Overview

1. uTox version:
2. Operating system:windows 10
3. Desktop Environment/Window Manager (Linux/BSD only):cygwin

### Issue
hello
can you help me?
there are some problem about build utox on windows:

/cygdrive/c/projects
$ git clone --recursive git://github.com/uTox/uTox.git
Cloning into 'uTox'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 26340 (delta 0), reused 3 (delta 0), pack-reused 26334
Receiving objects: 100% (26340/26340), 11.49 MiB | 866.00 KiB/s, done.
Resolving deltas: 100% (20372/20372), done.
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `dashless
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `USAGE
Submodule 'third-party/minini' (https://github.com/compuphase/minIni.git) registered for path 'third-party/minini'
Submodule 'third-party/qrcodegen' (https://github.com/nayuki/QR-Code-generator.git) registered for path 'third-party/qrcodegen'
Submodule 'third-party/stb' (https://github.com/nothings/stb.git) registered for path 'third-party/stb'
Cloning into '/cygdrive/c/projects/uTox/third-party/minini'...
remote: Enumerating objects: 61, done.
remote: Total 61 (delta 0), reused 0 (delta 0), pack-reused 61
Cloning into '/cygdrive/c/projects/uTox/third-party/qrcodegen'...
remote: Enumerating objects: 846, done.
remote: Counting objects: 100% (846/846), done.
remote: Compressing objects: 100% (215/215), done.
remote: Total 3948 (delta 481), reused 797 (delta 453), pack-reused 3102
Receiving objects: 100% (3948/3948), 890.79 KiB | 438.00 KiB/s, done.
Resolving deltas: 100% (2413/2413), done.
Cloning into '/cygdrive/c/projects/uTox/third-party/stb'...
fatal: unable to access 'https://github.com/nothings/stb.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
fatal: clone of 'https://github.com/nothings/stb.git' into submodule path '/cygdrive/c/projects/uTox/third-party/stb' failed
Failed to clone 'third-party/stb'. Retry scheduled
Cloning into '/cygdrive/c/projects/uTox/third-party/stb'...
remote: Enumerating objects: 5929, done.
remote: Total 5929 (delta 0), reused 0 (delta 0), pack-reused 5929
Receiving objects: 100% (5929/5929), 4.07 MiB | 385.00 KiB/s, done.
Resolving deltas: 100% (3934/3934), done.
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `sha1
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `displaypath
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `displaypath
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `sha1
Submodule path '': checked out ''
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `sha1
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `displaypath
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `displaypath
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `sha1
Submodule path '': checked out ''
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `sha1
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `displaypath
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `displaypath
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `sha1
Submodule path '': checked out ''
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `sha1
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `displaypath
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `displaypath
': not a valid identifierMinGW/bin/gettext.sh: line 88: export: `sha1
Submodule path '': checked out ''

**Comment by ArkYk** [comment]
$ cmake -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchain-win64.cmake" -DTOXCORE_STATIC=ON ..
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc.exe
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- checking for C compiler flag: -Wall
-- checking for C compiler flag: -Wextra
-- checking for C compiler flag: -Wpointer-arith
-- checking for C compiler flag: -Wimplicit-fallthrough=5
-- checking for C compiler flag: -Werror=implicit-function-declaration
-- checking for C compiler flag: -Wformat=0
-- checking for C compiler flag: -Wno-misleading-indentation
-- checking for C compiler flag: -fno-strict-aliasing
-- checking for C compiler flag: -fPIC
-- checking for C compiler flag: -static
-- checking for C compiler flag: -DAUDIO_FILTERING=1
-- Found PkgConfig: /usr/bin/pkg-config.exe (found version "0.29.1")
CMake Error at /usr/share/cmake-3.6.2/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find libtox (missing: LIBTOX_LIBRARY LIBTOX_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/Findlibtox.cmake:26 (find_package_handle_standard_args)
  CMakeLists.txt:272 (find_package)


-- Configuring incomplete, errors occurred!
See also "/cygdrive/c/projects/uTox/build/CMakeFiles/CMakeOutput.log".

**Comment by ArkYk** [comment]
I see the problem :) the "toolchain-win64.cmake"have some problem.I will printscreen about it.

**Comment by ArkYk** [comment]
![image](https://user-images.githubusercontent.com/36286944/47415228-8a9e3580-d7a5-11e8-84e4-d4e35b40d887.png)

**Comment by ArkYk** [comment]
![image](https://user-images.githubusercontent.com/36286944/47415339-c5a06900-d7a5-11e8-8106-e1c5e7589bb8.png)

**Comment by ArkYk** [comment]
![image](https://user-images.githubusercontent.com/36286944/47415505-2af45a00-d7a6-11e8-94ca-dcb2b8ccbaab.png)

**Comment by ArkYk** [comment]
this is the old file from github about utox.
![image](https://user-images.githubusercontent.com/36286944/47415575-5119fa00-d7a6-11e8-8a33-0cafa6697f51.png)

**Comment by ArkYk** [comment]
this is I changed it,and it's ok.
![image](https://user-images.githubusercontent.com/36286944/47415623-76a70380-d7a6-11e8-8974-2473da2ffa58.png)

**Comment by redmanmale** [comment]
@ArkYk 
Folder `libs` has to be inside `uTox` folder, not beside it.

**Comment by ArkYk** [comment]
> @ArkYk
> 文件夹`libs`必须位于`uTox`文件夹内，而不是旁边。

your right,but build.mdhttps://github.com/uTox/uTox/blob/develop/docs/BUILD.md#cygwin-setup tell me this.I follow you,move the Folder libs.hope you can change the build.md  quickly.thanks.

**Comment by redmanmale** [comment]
There was a mistake in build guide which was fixed in #1301.

**Comment by ArkYk** [comment]
> 在[＃1301](https://github.com/uTox/uTox/pull/1301)中修复了构建指南中的错误。

thank you!
