### ISSUE TITLE
static build is very old

### ISSUE THREAD

**Issue by pizdjuk** [uTox/uTox#1308]
the static build for Linux x86_64 is more then one half year old. And compile a new version isn't a five minutes walk...

**Comment by avoidr** [comment]
Please use your distro's repository. If your distro doesn't package uTox, please request it there. It enables uTox for many more users in a standard and distro-supported way.

And sorry that nobody reacted to you for two years.

**Comment by fcore117** [comment]
avoidr: Do you know someone who has built uTox for Windows distro(pun intended) that has TCP on/off crash fix included? Perhaps something to consider as it is most biggest breaking feature in release binary now, especially for newcomers who download and test uTox.

**Comment by avoidr** [comment]
Yes, robinli will attach an exe for the 0.18.0 release shortly.

Windows binaries are still provided, just for Linux distros please use the distro's repository.

Thanks for asking.

**Comment by avoidr** [comment]
robinli just attached an exe! Thanks, @robinlinden!
