### ISSUE TITLE
utox.io certificate is expired

### ISSUE THREAD

**Issue by avh-on1** [uTox/uTox#1315]
The HTTPS certificate for [utox.io](https://utox.io) expired on 10/30/2018. It looks like the site uses HSTS, so it's impossible to visit the site (or download binaries from it) unless you add an exception.

**Comment by cebe** [comment]
fixed, thanks for reporting!

**Comment by darkman088** [comment]
The problem has reappeared again. When I open the site tox.im, my browser immediately shows that the certificate is invalid

**Comment by GrayHatter** [comment]
utox.io was just fixed, tox.im is unrelated
