### ISSUE TITLE
Can't download utox, SSL certificate expired

### ISSUE THREAD

**Issue by useribs** [uTox/uTox#1329]
### Overview

 Connected to utox.io (45.79.101.7) port 443 (#0)
 Initializing NSS with certpath: sql:/etc/pki/nssdb
   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
 Server certificate:
       subject: CN=utox.io
       start date: Nov 22 06:55:12 2018 GMT
       expire date: Feb 20 06:55:12 2019 GMT
       common name: utox.io
       issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
 NSS error -8181 (SEC_ERROR_EXPIRED_CERTIFICATE)

**Comment by redmanmale** [comment]
Fixed.
