### ISSUE TITLE
Windows XP build is broken again

### ISSUE THREAD

**Issue by palikacska** [uTox/uTox#1333]
### Overview

1. uTox version: **0.16.1**
2. Operating system: **Windows XP**

### Issue

It always starts with a crash and won't even run normally.
It's the same with first start (no profile directory).

![utox-crash](https://user-images.githubusercontent.com/19628069/53434784-a174c300-39f7-11e9-8c9d-7103780c7160.png)

Tox ID also seems to be problematic. It's displayed with invalid character marks.

Lot of people - who don't want companies to spy on them with telemetry and cloud services - still use Windows XP. People who can't upgrade because of missing device drivers for their computers or peripherials don't have other choice. XP has still more users on NetmarketShare than all Linux distributions combined. Please pay more attention to providing a stable version for Windows XP with automated testing.

**Comment by GrayHatter** [comment]
> XP has still more users on NetmarketShare than all Linux distributions combined. Please pay more attention to providing a stable version for Windows XP with automated testing.

You and @irungentoo would get along well. That's the statistic that convinced me to maintain XP support the last time I suggested we drop XP support.

That said, according to stat counter, Windows XP has around 2% of all *Windows* usage, which, when compared vs Linux (36% to 0.8%) comes out to 0.72%. Thus there are more Linux users than XP users. 

So with that I'm officially ending XP support. All the previous reasons stand (from the last time I've had this discussion). Windows XP is not secure; and using any Tox client on Windows XP only provides a false sense of security, which (IMO) is worse than so security at all. I'd also assert that there's no hardware or software (without an exist better alternative) that'll will run on windows XP, and not Linux. (Excluding some purpose built systems/infrastructure that shouldn't be running any Tox client at all)

http://gs.statcounter.com/os-market-share/desktop-mobile-tablet/worldwide/#monthly-201901-201901-bar
http://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide#monthly-201901-201901-bar

**Comment by palikacska** [comment]
Mixing up usage statistics of classical desktop operating systems with Android and other mobile platforms is simply comparing apples to pears. Lots of people have a mobile device beside their desktop computer and not in place of it.

The right statistics you were looking for is this one below.
http://gs.statcounter.com/os-market-share/desktop/worldwide#monthly-201901-201901-bar

If there are one billion desktop users worldwide, we have **754 million** users on Windows from which **16,3 million are on Windows XP**. Only **16,1 million** are on Linux, regardless of what distribution they use. So maintaining a Windows XP port has at least the same importance as supporting Linux.

> Windows XP is not secure; and using any Tox client on Windows XP only provides a false sense of security, which (IMO) is worse than so security at all.

No, they're not. It can still be secure if you use it wisely and there is no false sense because you do know you're on an unsupported system, so you need to pay more attention to browse the web wisely and not to expose your system to potential harms by visiting malicious websites and automatically running downloaded EXE files. What really gives us the false sense of security are updated systems because users can think that they're completely secure if they just install all updates automatically so they can do whatever they want without paying attention to behave securely while browsing the web and using various applications. In addition, Tox users on Windows don't necessarily want to be secure by staying up-to-date with Microsoft's patches but rather use services that are more secure than popular cloud services (Tox vs. Facebook Messenger). Nowadays staying up to date to Microsoft's updates can mean opt-in telemetry, web elements in the Start menu, advertisements in the file explorer. These literally flout the classical principle of privacy and security, especially on Windows 10. So it's quite understandable if someone, who is willing to keep the Windows ecosystem while being concerned about security, won't upgrade to newer versions.

So @GrayHatter I'm asking you to change your mind and continue supporting Windows XP.

**Comment by im-grey** [comment]
Holy heck, someone still on XP.

**Comment by username1565** [comment]
uTox 0.7.0/utox_winXP.exe working on Windows XP. Also, [Isotoxin](https://github.com/isotoxin/isotoxin/releases)

**Comment by tumagonx** [comment]
^ so anything after 0.7 is broken? or thats what you tested?
me too still use XP, have been erased W10 installation last year from my xeon quadcore and never look "back".

**Comment by username1565** [comment]
Yes. Something is wrong, with backward compatibility, after v0.7.0.
I see [this official compiled binary, uTox_winxp.exe](https://github.com/uTox/uTox/releases/tag/v0.7.0) is woking on XP.
But all another compiled binaries for all versions higher than v0.7.0 (XP versions) are not working stable.
I don't know why.
I cann't compile v0.7.0 from the source code, to compare this, because there is no any libraries and dependencies. This is deprecated, and links to download it is inactive.

So, I just did try to compile the latest version of uTox v0.17.1, and I got success.
But this XP-version is not working stable.
I did creat the [separate branch for XP](https://github.com/username1565/uTox_winXP).
and load there all libraries.

Also, you can see here https://github.com/username1565/uTox_winXP/releases
the already compiled binaries, without any viruses (virustotal links and hashes you can find inside), and all this binaries are working on Windows XP.

If you know `C Lang`, you can find errors and fix it.
Have a nice day.

**Comment by username1565** [comment]
See this comment: https://github.com/username1565/uTox_winXP/issues/4#issuecomment-616855644
and check our repositaries.
