### ISSUE TITLE
libcheck missing?

### ISSUE THREAD

**Issue by Quix0r** [uTox/uTox#1335]
I currently try to build 55c40ce9d38a34ab55b52d30fa0b84b0734a5cdd and it doesn't find libcheck (no Debian package either). Also the README.md is not mentioning it. I have turned of build tests (which should prevent it from requiring?).

**Comment by avoidr** [comment]
Yes, turning off tests should make the dependency unneeded.
Dependencies are documented in [docs/DEPENDENCIES.md](https://github.com/uTox/uTox/blob/develop/docs/DEPENDENCIES.md).
The package you need to install is likely called simply "check".
Here it is: https://github.com/libcheck/check

**Comment by Quix0r** [comment]
I have now installed it to `/opt` and `FindCheck.cmake` seem not to look there for it.

**Comment by avoidr** [comment]
Why don't you just install it with your package manager?

**Comment by Quix0r** [comment]
I cannot find the proper package under Debian for it.

**Comment by avoidr** [comment]
https://libcheck.github.io/check/web/install.html
https://packages.debian.org/buster/check

The package name is simply "check".
