### ISSUE TITLE
tox_callback_conference_connected

### ISSUE THREAD

**Issue by slackjeff** [uTox/uTox#1337]
[ 61%] Linking C static library libutox-test-mock.a
/home/slackjeff/Downloads/uTox/src/tox_callbacks.c: In function ‘utox_set_callbacks_groups’:
/home/slackjeff/Downloads/uTox/src/tox_callbacks.c:312:5: error: implicit declaration of function ‘tox_callback_conference_connected’; did you mean ‘tox_callback_conference_invite’? [-Werror=implicit-function-declaration]
     tox_callback_conference_connected(tox, callback_group_connected);

**Comment by GrayHatter** [comment]
@endoffile78

**Comment by endoffile78** [comment]
Make sure you are on the latest version of toxcore from the toktok version: https://github.com/toktok/c-toxcore conference connected was recently added as a callback.
