### ISSUE TITLE
Utox doesn't appear on Lumina Desktop panel.

### ISSUE THREAD

**Issue by FrostKnight** [uTox/uTox#1340]
This version: 0.17.0-2 
This operating system: Hyperbola GNU/Linux-Libre
Lumina Desktop (works on BSD and GNU/Linux)
When I go to load it, it gives me this error in Lumina Desktop:

XLib Tray:    Incoming tray window event (28)
XLib tray:    Reached end of function, this is bad juju!

The odd thing is, it works with XFCE Desktop just fine.   Would love it if you fixed this bug. :)

**Comment by FrostKnight** [comment]
In a word, no. Nothing shows up.  I had to use the xfce4-panel to load it finally. Weird right?

**Comment by GrayHatter** [comment]
seems like Lumina doesn't' have a tray by default

**Comment by FrostKnight** [comment]
It does have a system dashboard though.  I wonder if you could make that work.

**Comment by GrayHatter** [comment]
Not until they improve their documentation... I have no idea where to even begin...

**Comment by FrostKnight** [comment]
Hmm, well, there is another Lumina desktop out there.  (It is a fork) let me know if you would consider this instead but only once its stable of course. (It is in alpha still.)
