### ISSUE TITLE
want to compile utox in windows but an error shows

### ISSUE THREAD

**Issue by victordesfe** [uTox/uTox#1353]
### Overview

1. uTox version: 0.17.0
2. Operating system: W7 x64
3. Desktop Environment/Window Manager (Linux/BSD only): cygwin

### Issue

hi i wanted to compile utox last version but an error showed up in the last step, when you run the make command. i'm not really sure whats wrong but is seems like dependencies versions aren't compatible or something. I've done all steps without errors (i extracted the 6 dependencies on the said folder). building for x86 and x64 seem to throw the same errors. i've downloaded all dependencies from the given links in your build guide, and all from the same architecture (to be concrete x86)

```
Usuario@Usuario-PC /home/cygdrive/c/projects/uTox/build
$ make
[  6%] Built target utoxAV
[ 19%] Built target utoxLAYOUT
[ 32%] Built target utoxUI
[ 53%] Built target utoxNATIVE
[ 54%] Linking C executable utox.exe
/usr/lib/gcc/x86_64-w64-mingw32/7.4.0/../../../../x86_64-w64-mingw32/bin/ld: skipping incompatible /home/cygdrive/c/projects/uTox/libs/windows-x64/lib/libOpenAL32.a when searching for -lOpenAL32
/usr/lib/gcc/x86_64-w64-mingw32/7.4.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lOpenAL32
/usr/lib/gcc/x86_64-w64-mingw32/7.4.0/../../../../x86_64-w64-mingw32/bin/ld: skipping incompatible /home/cygdrive/c/projects/uTox/libs/windows-x64/lib/libopus.a when searching for -lopus
/usr/lib/gcc/x86_64-w64-mingw32/7.4.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lopus
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/utox.dir/build.make:961: utox.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:71: CMakeFiles/utox.dir/all] Error 2
make: *** [Makefile:106: all] Error 2
```

thanks in advance

**Comment by Philosoph228** [comment]
That type of error on linking stage points to binary incompatibility.
As seen by path, you probably using x86_64 gcc toolchain. It may be confusing, but x86_64 is not x86 - it is 64bit instruction set with bridge to 32bit instructions. 
In this case, you would switch to i686 toolchain, or get x64 libraries to get things work.

**Comment by Philosoph228** [comment]
Have you tried to build that libraries by yourself? Libraries built with differ gcc versions may be binary incompatible.

**Comment by redmanmale** [comment]
It should be work now.

Note: For x86 all these libs should be placed in `windows-x32` folder.
I'll update build docs.
