### ISSUE TITLE
uTox won't compile on windows

### ISSUE THREAD

**Issue by blueclouds8666** [uTox/uTox#1361]
### Overview

1. uTox version: lastest
2. Operating system: windows 7 sp1 64-bit

### Issue

Hi, i've followed the guidelines on /blob/develop/docs/BUILD.md to compile utox for win32. I did everything as described, but when running the cmake command, this error shows up:

```
$ cmake -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchain-win32.cmake" -DTOXCORE_STATIC=ON ..
-- The C compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/i686-w64-mingw32-gcc.exe
-- Check for working C compiler: /usr/bin/i686-w64-mingw32-gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- checking for C compiler flag: -Wall
-- checking for C compiler flag: -Wextra
-- checking for C compiler flag: -Wpointer-arith
-- checking for C compiler flag: -Wimplicit-fallthrough=5
-- checking for C compiler flag: -Werror=implicit-function-declaration
-- checking for C compiler flag: -Wformat=0
-- checking for C compiler flag: -Wno-misleading-indentation
-- checking for C compiler flag: -fno-strict-aliasing
-- checking for C compiler flag: -fPIC
-- checking for C compiler flag: -static
-- checking for C compiler flag: -DAUDIO_FILTERING=1
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.0")
CMake Error at /usr/share/cmake-3.3.2/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find libtox (missing: LIBTOX_LIBRARY LIBTOX_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.3.2/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/Findlibtox.cmake:26 (find_package_handle_standard_args)
  CMakeLists.txt:272 (find_package)


-- Configuring incomplete, errors occurred!
See also "/uTox/build/CMakeFiles/CMakeOutput.log".
```

I've also tried with older versions of uTox: 0.17.0 and 0.16.0, but they show up the same error. Wether i set it up to compile 32 or 64 bit, it does the same. It seems as if the error came from an incompatibility with libtoxcore as i've been reading on #1172. Thread which by the way, didn't explained any possible solution to the problem.

I've been looking for older build versions of libtoxcore (TokTok fork) so maybe with an older version, utox can compile, but i can't make them to work, or neither compile them, since windows compiling instructions are very badly described (they just tell you to install visual studio express and get by your own). They also mention a cross compiling from linux but neither instructions are clear enough.

At this point i don't know what to do, i've been investigating on it for long hours but it always thorws the same error. I've done all the steps as described (cloned from the lastest git version, downloaded the 6 zip from the links mentioned on build.md, and extracting here all 6 zips on /utox/libs/widows-x64/, creating /utox/build/ folder and building from there, i also installed all the cygwin addons required). It would be enough for me if i could compile 0.16.1, but in the instructions for building, there isn't any indication on which version of the libraries should you use or which are the proper ones to use, neither there is any place to download older builds of the libraries (jenkins just has only the lastest), so i can't go any far.

Looking forward to hear your response.
thanks for your time.

**Comment by username1565** [comment]
Hey, dude. if this say you `Could NOT find libtox`, this means maybe something wrong.
What is wrong? Maybe I know! `/utox/libs/widows-x64/`! `widows` is not `windows`. xD

**Comment by blueclouds8666** [comment]
> Hey, dude. if this say you `Could NOT find libtox`, this means maybe something wrong.
> What is wrong? Maybe I know! `/utox/libs/widows-x64/`! `widows` is not `windows`. xD

that was just a typo in the reply. the folder is called as it should, and still gives me the same error as today:

```
Usuario@Usuario-PC /projects/uTox/build
$ cmake -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchain-win64.cmake" -DSTATIC_TOXCORE=ON ..
-- The C compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc.exe
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- checking for C compiler flag: -Wall
-- checking for C compiler flag: -Wextra
-- checking for C compiler flag: -Wpointer-arith
-- checking for C compiler flag: -Wimplicit-fallthrough=5
-- checking for C compiler flag: -Werror=implicit-function-declaration
-- checking for C compiler flag: -Wformat=0
-- checking for C compiler flag: -Wno-misleading-indentation
-- checking for C compiler flag: -fno-strict-aliasing
-- checking for C compiler flag: -fPIC
-- checking for C compiler flag: -static
-- checking for C compiler flag: -DAUDIO_FILTERING=1
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.0")
CMake Error at /usr/share/cmake-3.14.5/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find libtox (missing: LIBTOX_LIBRARY LIBTOX_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.14.5/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Findlibtox.cmake:33 (find_package_handle_standard_args)
  CMakeLists.txt:277 (find_package)


-- Configuring incomplete, errors occurred!
See also "/projects/uTox/build/CMakeFiles/CMakeOutput.log".
```
