### ISSUE TITLE
Can't paste ID

### ISSUE THREAD

**Issue by cws999** [uTox/uTox#1363]
### Overview

1. uTox version:0.8.2
2. Operating system:andrid
3. Desktop Environment/Window Manager (Linux/BSD only):

### Issue

When I add a friend,Can't paste friend' ID

**Comment by GrayHatter** [comment]
Which ID can't you paste?

**Comment by GrayHatter** [comment]
Ahh, nevermind, That's a known bug with how android works, there's no estimated fix

**Comment by cws999** [comment]
> Which ID can't you paste?

my friend's tox id.Similar to this“F7DC2017DC32B6A45860BC4CB88A016C6D1B3D2FD9643D96E2C88CD4640FED3D0EEBF3844E10”
