### ISSUE TITLE
Run from source? / TailsOS

### ISSUE THREAD

**Issue by Ub3rZ4cH** [uTox/uTox#1365]
Okay so I was wondering if you could run uTox from source? after building I noticed the excutable, and it opens but I get errors which I will get to in a moment.

Also the same errors I get when opening the installed dpkg/.deb on Tails.

1. uTox version: Latest git
2. Operating system: Tails
3. Desktop Environment/Window Manager (Linux/BSD only):  Gnome

```
Settings:     Unable to parse utox_save.ini.
Settings:     Unable to open utox_save.
Settings:     Unable to load uTox settings. Use defaults.
XLib Tray:    Incoming tray window event (28)
XLib tray:    Reached end of function, this is bad juju!
flsit:        Index out bounds. Too many items have been created.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
```

Once I run it once, and its created some files it no longer gives errors about the settings, but the rest of the errors, but it also does not want to connect?

I remember somehow running it in portable mode, but I have tried `-p` and get the same results, and if running from source would it save / check the config files in the source directory or still check the .config/tox directory?

**Edit:** 

I see that running ./utox -p now creates the tox folder with the configs in but it still doesnt want to connect? and I get that old bug where changing any settings in the program crashes it, but I have to instead edit the config file. Here is the errors I get;

```
XLib Tray:    Incoming tray window event (28)
XLib tray:    Reached end of function, this is bad juju!
flsit:        Index out bounds. Too many items have been created.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
```

**Comment by avoidr** [comment]
Regarding the connection, try disabling UDP. I think Tails blocks UDP, doesn't it? I'd have to check.

```
flsit:        Index out bounds. Too many items have been created.
```
This is a real bug, thank you!

>I remember somehow running it in portable mode, but I have tried -p and get the same results, and if running from source would it save / check the config files in the source directory or still check the .config/tox directory?

The behaviour of `-p` is documented in the man page; the profile data is saved `tox/` in the current working directory. No other location is checked.

**Comment by avoidr** [comment]
See if this fixes your problem.

**Comment by avoidr** [comment]
You may also try if the `item_heap` branch works for you.

**Comment by Ub3rZ4cH** [comment]
I will test for you at some point soon, before you replied I changed OS.
But I will try replicate on a VM.
