### ISSUE TITLE
segfault on setting proxy settings

### ISSUE THREAD

**Issue by yangfl** [uTox/uTox#1376]
### Overview

1. uTox version: 0.17.1 777ab94
2. Operating system: Linux (Debian)
3. Desktop Environment/Window Manager (Linux/BSD only): mate

### Issue

Forwarded from https://bugs.debian.org/942081

Attempting to turn on the proxy settings results in a segfault
1) navigate to advanced settings
2) put ip address for localhost into settings field, port in port field
  (can't confirm whether or not proxy is working since...it crashes)
3) click on the enable toggle..
boom segfault

Not sure if #1252 is related.

**Comment by avoidr** [comment]
Hey, thanks for your report.
A workaround is editing the config file with a text editor: `~/.config/tox/utox_save.ini`.
