### ISSUE TITLE
uTox.apk for Android

### ISSUE THREAD

**Issue by username1565** [uTox/uTox#1379]
### Overview

1. uTox version: v0.15.0
2. Operating system: Android 9
3. Desktop Environment/Window Manager (Linux/BSD only): ZTE Blade A7 2019 (Smartphone).

### Issue

Write your issue here.

Hello. I see android version of uTox, here: https://apkpure.com/utox/tox.client.utox
this is `.apk`-file, this have version v0.15.0, and I have already successfully runned it on `ZTE Blade A7 2019` with Android 9. But something incorrect there.
So, which version of uTox for Android is latest?
Is this still developing? Is there any open source code + instruction for compilation?
Now, I using Antox, but I want to use utox, with minimal functions and size + ability to change toxID, by entering PrivateKey.

**Comment by avoidr** [comment]
uTox for Android has been obsolete for a long time.
