### ISSUE TITLE
Complete list of all available commands

### ISSUE THREAD

**Issue by destroyglasscastles** [uTox/uTox#1380]
Please provide a complete list of available commands. The only ones I've stumbled upon are: ">" for quoting stuff; and "/me" for so-called actions. What about spoilers or perhaps commands for pasting some code chunks? Neither "/spoiler" nor "/code" commands seem to be working.

If there are more than these two commands, please state them somewhere. Thanks.

**Comment by avoidr** [comment]
Hey, thanks for your issue!
/spoiler and /code aren't working because they simply haven't been implemented! The complete list of commands so far is in the man page.
Just out of interest; what commands did you expect other than /spoiler and /code?

**Comment by avoidr** [comment]
And welcome to github!

**Comment by destroyglasscastles** [comment]
Hello avoidr.

My bad, should've read the manual beforehand. By the way, I couldn't find the greater-than sign's usage in the manual, so may I ask what other symbols/whatever uTox supports for text manipulation that are not shown anywhere?
As for `/spoiler` and `/code`, I bet these two commands would definitely be a great addition to uTox. However, [this](https://utox.io/images/utox_image.png) picture implies that uTox has syntax highlighting support, but how do I enable it? My uTox version is 0.17.0.

**Comment by avoidr** [comment]
Hey!
There is "greentext" '>' and "redtext" '<' (less-than sign at the end of the line). I think that's all already.
I think `/code` is something that has its place in uTox, definitely.
The picture is just an inline image. It just happens to look like it's part of the program.

May I know what keeps you from 0.17.1, btw?

**Comment by destroyglasscastles** [comment]
So that was just an image, I see now. Thank you for telling me about the less-than sign, though! I hope you will implement the `/code` command in the near future.

Yes you may; utox 0.17.0 is the latest uTox version that is included in Debian packages as of now, and I'm too lazy to compile it from source. I know I can also download a pre-compiled binary of uTox, but the time has not come yet I guess.

**Comment by avoidr** [comment]
>I hope you will implement the /code command in the near future.

I hope so, too ☺
In my imagination it is done with backticks, but let's see.

**Comment by avoidr** [comment]
I've started working on this in #1381.

**Comment by avoidr** [comment]
It turns out that this needs a different approach and will take more time than I hoped. I'll close this now, but I'll make sure to mention you when it's done.
