### ISSUE TITLE
XP version is missing on utox.io

### ISSUE THREAD

**Issue by Vomitlord** [uTox/uTox#1389]

**Comment by avoidr** [comment]
Hello!

The XP version is not officially supported anymore, due to XP being considered insecure these days.
See also this: #1341.

Sorry for that.

**Comment by Vomitlord** [comment]
So why is there an option to download legacy version which is actually a dead link? If you dont want to support XP even as a specific fork, please remove it since this is disappointing.

**Comment by avoidr** [comment]
You make a good point, sorry :/

**Comment by avoidr** [comment]
I have actually fixed the dead link now, @Vomitlord.

**Comment by username1565** [comment]
Anyone have old source code from venom_win32.exe, which can be compiled to win32 exe?
I see many links here: https://www.google.com/search?q=venom_win32%2FlastSuccessfulBuild%2Fartifact%2Fprefix%2FVenom.zip
but noone not working...
