### ISSUE TITLE
How to compile XP version of uTox_v0.7.0?

### ISSUE THREAD

**Issue by username1565** [uTox/uTox#1390]
### Overview

1. uTox version: v0.7.0
2. Operating system: Windows XP.
3. Desktop Environment/Window Manager (Linux/BSD only): Windows XP.

### Issue

Write your issue here.

How to compile XP version of uTox_v0.7.0?
I see some `.exe`-file here: https://github.com/uTox/uTox/releases/tag/v0.7.0
uTox_winxp.exe
How to build it from the source code? Can you write this step by step, please?

**Comment by avoidr** [comment]
Hello, have you seen the file [docs/BUILD.md](https://github.com/uTox/uTox/blob/develop/docs/BUILD.md#windows)?

**Comment by avoidr** [comment]
If that helps you, you can download a more up-to-date version Windows XP exe from [utox.io](https://utox.io/#downloads) now.

**Comment by username1565** [comment]
Thanks! I don't see any official installer of Cygwin for Windows XP,
but I found [this mirror](http://cygwin-xp.portfolis.net/cygwin), and this seems like working.
Now, I'lll make the mirror of this mirror to save all binaries and source code.
This is not easy, because so many checkbox need to change there, but I wrote the macros for **Easy Macro Recorder Portable**.

I did test all XP versions on Windows XP earlier, but not all working correctly,
and the best version, which working is v0.7.0.
So I want to compile this, and, maybe rewrite something.

If you have free fime, and enough fun, can you add import-export NaCl privkey in the future?

This issue is closed. Have a nice day.

**Comment by username1565** [comment]
Hi, again, @avoidr!
I'll reopen this issue, because I did still cann't compile uTox, which is working on Windows XP.
I did sucessfully compile some win32 exe, and see some differences in BUILD.md, which you provided here: https://github.com/uTox/uTox/issues/1390#issuecomment-549990961
For example, windows-x64 folder.

I did write this `.sh`-file to automatize compilation, and download libraries.
[cygwin_clone_and_build_uTox_win32.zip](https://github.com/uTox/uTox/files/3821781/cygwin_clone_and_build_uTox_win32.zip)
Now, minimal requirements is: cygwin + packages(sh and lynx, and maybe something else).
You can read the source code, and test it yourself, just for fun.

But... After compilation, I got x86-win32 exe, and this cann't be runned on XP.
I don't know how to compile XP version. And also, uTox v0.7.0 I cann't compile.
I did try this code:
```
cd /cygdrive/c
mkdir projects
cd projects/
git clone --recursive -b 'v0.7.0' --single-branch https://github.com/uTox/uTox.git uTox-0.7.0
cd uTox-0.7.0/
mkdir libs
cd libs/
mkdir windows-x86
cd ..
sh tools/cygwin-compile.sh 32 win
```
but see an errors there. So this issue is re-opened.

Can you help with this?

**Comment by username1565** [comment]
I just saw [this file](https://github.com/uTox/uTox/blob/develop/src/windows/main.XP.c),
then [search it](https://github.com/uTox/uTox/search?q=main.XP.c&unscoped_q=main.XP.c)
then [try to search it](https://github.com/uTox/uTox/search?q=WIN_XP_LEGACY&unscoped_q=WIN_XP_LEGACY), and found [this commit](https://github.com/uTox/uTox/commit/61c738b9baf5b2b324b809cfc3e3a315589e314a).
After this I did try:
```
cmake -D __WIN_LEGACY=1 -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchain-win32.cmake" -DTOXCORE_STATIC=ON ..
```
But no any results. I still get win32 exe, but this cann't be runned on XP.
This want RegDeleteKeyValueW in DLL ADVAPI32.dll.

**Comment by username1565** [comment]
Try to build uTox 0.7.0 for Windows XP, using cygwin:

```
cd /cygdrive/c/projects/
git clone --recursive -b 'v0.7.0' --single-branch https://github.com/uTox/uTox.git uTox-0.7.0
cd uTox-0.7.0
sh tools/cygwin-compile.sh 32 win
```
And see the following errors:
```
$ sh tools/cygwin-compile.sh 32 win
Building 32bit version of uTox
Building from a ~Unix environment within windows
Git version: v0.7.0
i686-w64-mingw32-gcc: error: ./*.c: No such file or directory
i686-w64-mingw32-gcc: error: ./png/png.c: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/toxcore/lib/libtoxcore.a: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/toxcore/lib/libtoxav.a: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/toxcore/lib/libtoxdns.a: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/toxcore/lib/libtoxencryptsave.a: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/libsodium/lib/libsodium.a: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/vpx/lib/libvpx.a: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/opus/lib/libopus.a: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/openal/lib/libOpenAL32.a: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/filter_audio/filter_audio.c: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/filter_audio/aec/*.c: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/filter_audio/agc/*.c: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/filter_audio/ns/*.c: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/filter_audio/other/*.c: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/filter_audio/vad/*.c: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/filter_audio/zam/*.c: No such file or directory
```
So, as I see, need to download something else.
Do you have the links for additional packages, with versions, corresponding with uTox v0.7.0?

**Comment by username1565** [comment]
Also, you can upload the package archives to github, in comments, and download it using wget or git by direct link, like this link: https://github.com/uTox/uTox/files/3821781/cygwin_clone_and_build_uTox_win32.zip
from [this comment](https://github.com/uTox/uTox/issues/1390#issuecomment-551276992).

**Comment by username1565** [comment]
If will be possible to compile latest version from the source code to win32 version for Windows XP, I think we can fix some bugs, make utox compatible with more platforms, and add all this functions: https://wiki.tox.chat/clients#features

**Comment by avoidr** [comment]
Hello, @username1565.
When it comes to Windows, I really have no idea, so I probably can't help. But I really appreciate the effort you're doing here - it may help others.

>But... After compilation, I got x86-win32 exe, and this cann't be runned on XP.

Do you *want* to compile as 32-bit binary? Have you tried 64-bit? What does it mean that it can't be run on WinXP?

>This want RegDeleteKeyValueW in DLL ADVAPI32.dll.

Ok, so I searched for what this `ADVAPI32.dll` is: https://www.file.net/process/advapi32.dll.html

>Advanced API Services Library is an essential Windows system process that is designed to support several API's including security and registry calls. The 32-bit version of this file is responsible for restarting and shutting down the system, Windows registry, managing user accounts and starting and stopping and creating Windows services.

Especially:
>starting and stopping and creating Windows services

That sounds a lot like "start uTox on boot" feature. That's not an essential feature, which tells me that if you *really* can't figure out how to make the whole thing work, you could try by deleting that feature as a last resort.

Next, I checked `RegDeleteKeyValueW` and found this: https://www.geoffchappell.com/studies/windows/win32/advapi32/api/index.htm

It tells you the Windows version that functions from this library apply to. For our function it says: "6.0 and higher". Wasn't version 6 actually Win7, or something? Yup: https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions
It was Vista, 6.1 was 7, XP was still 5.x. Grepping that function in the sources confirms this.

So what happened is that somehow it tried to compile the Win7 version instead of WinXP.

**Comment by avoidr** [comment]
But now I am a little bit confused about your progress. Have you managed to make that "`RegDeleteKeyValueW` in `ADVAPI32.dll`" problem go away?

**Comment by avoidr** [comment]
>But I cann't do compilation of this version, using your guide. Only last version.

So why don't you compile the latest version and try to fix that? Wouldn't that make more sense?

**Comment by avoidr** [comment]
>Where need to put base_emoji??

Nowhere. base_emoji is not a dependency anymore. `docs/BUILD.md` is wrong. Feel free to send a PR ☺

**Comment by username1565** [comment]
Hi, @avoidr!
>Do you want to compile as 32-bit binary?

Yes. I want to get x86 win32.exe for Windows XP, [like this](https://github.com/uTox/uTox/releases/download/v0.14.0/uTox_winXP.exe), but after compilation from the source code.
And this `exe`, must to working in Windows XP, without any errors.

>Have you tried 64-bit?

Yes, this is working on Windows 8.1 Pro x64, and this can be compiled from the source code, but this not working on Windows XP.

>What does it mean that it can't be run on WinXP?

This must working on Windows XP. Maybe someone know how to make that executable from the source code.

>Ok, so I searched for what this ADVAPI32.dll is: https://www.file.net/process/advapi32.dll.html
>starting and stopping and creating Windows services
>RegDeleteKeyValueW
>Windows version that functions from this library apply to. For our function it says: "6.0 and higher".

Ok. Thanks! Maybe this because my advapy32.dll is too old.
I have this file there, on Windows XP: 
С:\WINDOWS\system32\dllcache\advapi32.dll
С:\WINDOWS\system32\advapi32.dll
And I try to compile this on Windows XP.

>So why don't you compile the latest version and try to fix that? Wouldn't that make more sense?

As you can see, I did try, and I don't understand there anything. 

>But now I am a little bit confused about your progress.
>Have you managed to make that "RegDeleteKeyValueW in ADVAPI32.dll" problem go away?

No. That .sh file, which I did posted, can compile win32 executable (for x86 platform),
but this cann't be runned on windows XP.
So I just did try to compile uTox-0.7.0 because that XP-version is stable, and working good on XP.

>Nowhere. base_emoji is not a dependency anymore. docs/BUILD.md is wrong. 

Yeap, I saw this for [uTox-0.7.0](https://github.com/uTox/uTox/tree/v0.7.0). Only in Build.md i see the link about **base_emoji**.

I did fix one more error, when I try to compile utox-0.7.0.
```
i686-w64-mingw32-gcc: error: ./png/png.c: No such file or directory
```
This I don't see, after copy `png`-folder [from this branch](https://github.com/notsecure/uTox).
I'll play with that source code, when I'll have free time.
Also, I want to test the building an android-version of utox.

Best regards.

**Comment by username1565** [comment]
I see in this [BUIILD.md](https://github.com/uTox/uTox/blob/develop/docs/BUILD.md)
the [following x86-package of toxcore](https://build.tox.chat/view/libtoxcore/job/libtoxcore-toktok_build_windows_x86_static_release/lastSuccessfulBuild/artifact/libtoxcore-toktok_build_windows_x86_static_release.zip)
And there is contains `.a` files in the `/lib/`-folder.
But there is not found the following `.a`-files:
```
lib/libtoxcore.a
lib/libtoxdns.a
lib/libtoxav.a
lib/libsodium.a
lib/libvpx.a
lib/libopus.a
```
Maybe, this is main reason, why https://github.com/notsecure/uTox/ cann't be compiled too.
Where I can find this files? And... Maybe you can fix this!

**Comment by avoidr** [comment]
>Ok. Thanks! Maybe this because my advapy32.dll is too old.

Yes, the way I understand is that your advapi is too old. Too old for the version of uTox you are compiling, which seems to *not* be the XP version, but the Win7 version. `RegDeleteKeyValueW` doesn't exist on WinXP.

>And there is contains .a files in the /lib/-folder.
>But there is not found the following .a-files:

I think you should try and compile the latest uTox for WinXP. Find out why it doesn't take main.XP.c (That's what I think happens, since that file doesn't use `RegDeleteKeyValueW` function…). Maybe try using `#warning` preprocessor directive in the main.*.c files, to see which files are being processed. Just an idea. I'd use the latest versions of everything, otherwise things are probably going to get messy.
If uTox v0.7.0 works, try to slowly go up and see what breaks.

**Comment by username1565** [comment]
I just try to compile this version: https://github.com/notsecure/uTox/
With utox lib/folder, but I see only two errors: 
```
i686-w64-mingw32-gcc: error: ./lib/toxcore/lib/libtoxdns.a: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/toxcore/lib/libtoxav.a: No such file or directory
```
After this errors, compilation was been terminated.
As you can see, there is not found two files in toxcore folder.
Maybe, you have this files, or I can build it?

**Comment by avoidr** [comment]
Again, if those files are missing, it's probably because current toxcore doesn't have them anymore. So you need to dig old version of toxcore, too. Which is what I meant with it being messy. Just try to get the latest version to work. From what I understand, the latest version doesn't run on Windows XP, because the wrong API is being used. That is not the API used in main.XP.c, though. So why isn't main.XP.c being used? That's what you have to find out. (Or that's how I understand the situation, anyway.)

**Comment by username1565** [comment]
I don't know. This seems like all files are compiling. `main.c`, `mainXP.c`, and `main7.c` in one process.
I did try to manipulate some values [CMakeLists.txt](https://github.com/uTox/uTox/blob/37dba1af57b0b615abd1c649ba551b21e796a9d0/CMakeLists.txt#L441)
But no any results.

Also, I did try to add `-m32` flag for `gcc`, here "tools\cross-compile-windows.sh",
to get win32 executable, when I try to compile it on windows XP, but the same result.

After this all, I did not reach any progress,
so if anyone have source code of utox for Windows XP, which can be compiled on windows XP, please tell me.

**Comment by avoidr** [comment]
readme.txt:
```
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
```
Do you have `pkgconfig` installed?

```
-- Platform Options --------------
- Windows Legacy:          OFF
```
This looks wrong.

Well, all you seem to be missing is `cmake -DWIN_XP_LEGACY ..`.

local_projects.sh:
```
cmake __WIN_LEGACY=1 -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchain-win32.cmake" -DTOXCORE_STATIC=ON ..     #maybe for XP, and this is linked. I saw XP-files.
```
This is your line. And it seems that you have forgotten the `-D` before `__WIN_LEGACY=1`. And in either case, I am not sure if that would still work like that (I don't know cmake), but in any case, it seems that what you are actually supposed to use instead is `-DWIN_XP_LEGACY`.

So, try to replace your `__WIN_LEGACY=1` with `-DWIN_XP_LEGACY`.

**Comment by avoidr** [comment]
>As you can see, mainXP.c was been compiled sucessfully, but after this was been compiled main.7.c:
>```
>[ 24%] Building C object src/windows/CMakeFiles/utoxNATIVE.dir/main.XP.c.obj
>[ 26%] Building C object src/windows/CMakeFiles/utoxNATIVE.dir/main.7.c.obj
>```

In `src/windows/CMakeLists.txt`:
```
    ## The following two have ifdef's for __WIN_LEGACY
    #  We include them both here even though only one will compile with content
    main.XP.c
    main.7.c
```
So yes, both compiling seems to be correct.

**Comment by username1565** [comment]
Thanks! Finally I did compile this, and got unstable version for latest uToxXP, like this [uTox_winXP.exe](https://downloads.utox.io/stable/uTox_winXP.exe).
from this site: https://utox.io/#downloads

I got his version, after do this in `windows/CmakeLists.txt`:
```
#option(WIN_XP_LEGACY "Compile Legacy code for Windows XP" OFF)
option(WIN_XP_LEGACY "Compile Legacy code for Windows XP" ON)
```

I see, this uTox can be runned on XP, but after some time program is closed automatically.
Visual Studio 2010 say about violation of access to the memory.
![изображение](https://user-images.githubusercontent.com/39200328/68613395-52a88400-04c7-11ea-8174-2708a1875a7d.png)

Also, I see incorrect pathways, in the black debug-window.
This try to read
```
WinFilesys:   Could not open file:
disk:\Documents and Settings\USER\Application Data\Tox\utox_save
```
not local folder. And when USER has cyrillic symbols, there is incorrect encoding.
Maybe after this, there is violation about access to memory, and maybe I can fix this myself.

I'll test it and try to fix something. If I'll get success, I'll open Pull Requests. 

Have a nice day!

**Comment by username1565** [comment]
I think, all libs must be uploaded to github, and downloaded using git or wget even by using `http`/`https` links. Because wihout depencencies, this code will be full and complete.
In this case downloading and compilation can be possible using one `.sh` file, and debugging and this source code will be more easy, than using updated libraries or try to downoading this by inactive links.

**Comment by avoidr** [comment]
>Finally I did compile this, and got unstable XP-version for latest uTox v0.17.1.

Yay! 🎉

>Something, like this uTox_winXP.exe,
>from this site: https://utox.io/#downloads
>but hashes not match.

What are you saying? What you compiled and the uTox_winXP.exe from utox.io are two different files. Naturally the hashes do not match. Hashes match only if the files are exactly the same.

>Visual Studio 2010 debugger say about some violation of access to the memory:

I can't tell from this screenshot what the problem is, but it looks terrible :P

>And when USER has cyrillic symbols, there is incorrect encoding.
>Maybe after this, there is violation about access to memory,

Maybe, I remember something about cyrillic path in Windows version being problematic. Search the issues for "cyrillic", maybe you'll find something helpful.

>maybe I can fix this myself, but I tell this for you, because you can fix this faster.

Understandable, but unfortunately I have to disappoint you a little. I don't know anything about Windows and I don't have any Windows computer, and I already have little time fixing other things. Basically, uTox has very little resources currently, and zero resources for WinXP especially. So I am afraid you are on your own here. But if you do find fixes, feel free to send PRs. But please don't expect anything.

**Comment by username1565** [comment]
Can you create the branch for Windows XP from your current "develop branch"? I can push there a pull requests, because I'll fix the bugs for WinXP.

**Comment by avoidr** [comment]
No, I can't create that branch for you, but you can for yourself. And you can create fixes and open PRs. Nothing beyond that is guaranteed. Simply because uTox has very limited resources currently, and zero for WinXP. Sorry about that.

**Comment by username1565** [comment]
If I'll open some Pull Requests, this will be fixes for windows XP, and this changes and modification can be not compatible with linux, unix, android, and many another platforms.
That was the reason to create the new branch.
And this branch can evolve faster, than all your branches together.

Anyway, if someone have working uTox for windows XP, and have source code, and can compile this, I'll still wait for this with instruction to compile this.

Best regards.

**Comment by username1565** [comment]
I just found the oldest version of uTox for Windows XP - this is `wintox.exe`!
`249 KB` only, standalone exe, seems like portable executable,
and this only p2p chat, encrypted with NaCl, which is working in LAN.
No any video, and audio calls. 
Here it is: [wintox_win32.zip](https://github.com/uTox/uTox/files/3874143/wintox_win32.zip)

Maybe, anyone already have the source code from this,
to compile this exe, and build from this source code.

Anyway, this executable can be decompiled into the source code,
because nacl-library, as I understanding, already contains there, in that 249 kBytes.

Have a nice day.
