### ISSUE TITLE
Cann't build on Debian

### ISSUE THREAD

**Issue by AAAnikeev** [uTox/uTox#1398]
### Overview

1. uTox version: 0.17.0-1
2. Operating system: Debian 
3. Desktop Environment/Window Manager (Linux/BSD only):

### Issue

Can't build your application
Make dir build then 
cmake ..
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- checking for C compiler flag: -Wall
-- checking for C compiler flag: -Wextra
-- checking for C compiler flag: -Wpointer-arith
-- checking for C compiler flag: -Wimplicit-fallthrough=5
-- checking for C compiler flag: -Werror=implicit-function-declaration
-- checking for C compiler flag: -Wformat=0
-- checking for C compiler flag: -Wno-misleading-indentation
-- checking for C compiler flag: -fno-strict-aliasing
-- checking for C compiler flag: -fPIC
-- checking for C compiler flag: -flto
-- checking for C compiler flag: -fsanitize=address
-- checking for C compiler flag: -fno-omit-frame-pointer
-- checking for C compiler flag: -DAUDIO_FILTERING=1
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Found libtox: /usr/lib/x86_64-linux-gnu/libtoxcore.so  
-- Found libsodium: /usr/lib/x86_64-linux-gnu/libsodium.so  
-- Found libvpx: /usr/lib/x86_64-linux-gnu/libvpx.so  
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found DBUS: /usr/include/dbus-1.0;/usr/lib/x86_64-linux-gnu/dbus-1.0/include  
-- checking for C compiler flag: -DHAVE_DBUS=1
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.9.1") 
Found Freetype version 2.9.1
Freetype include: /usr/include/freetype2
Freetype library: /usr/lib/x86_64-linux-gnu/libfreetype.so
-- Found libfontconfig: /usr/lib/x86_64-linux-gnu/libfontconfig.so  
FontConfig include: /usr/include
FontConfig library: /usr/lib/x86_64-linux-gnu/libfontconfig.so
X include:         /usr/include
X library:         /usr/lib/x86_64-linux-gnu/libSM.so;/usr/lib/x86_64-linux-gnu/libICE.so;/usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
Xrender include:   /usr/include
Xrender library:   /usr/lib/x86_64-linux-gnu/libXrender.so
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find libv4lconvert (missing: LIBV4LCONVERT_LIBRARY
  LIBV4LCONVERT_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Findlibv4lconvert.cmake:26 (find_package_handle_standard_args)
  src/xlib/CMakeLists.txt:65 (find_package)

-- Configuring incomplete, errors occurred!

Then i install package: dv4l, libv4l-0, libv4lcovert0, v4lutils.
And that doesn't help. All pacakges from official debian repo.
How build your application and what i need install?

**Comment by avoidr** [comment]
Generally you need to install the `-dev` packages. They include the headers for the libraries, and maybe other stuff that is needed for compilation. On Ubuntu (taken from `docs/BUILD.md`) the right package seems to be `libv4l-dev`. Try installing that.
