### ISSUE TITLE
uTox 0.16.1 on WinXP SP3 issue

### ISSUE THREAD

**Issue by Vomitlord** [uTox/uTox#1399]
After I close the app, all the settings reset to default, including nickname, avatar and contacts.

**Comment by Vomitlord** [comment]
Tried out 0.14 - same thing. I also want to specify that it's not just cuz XP, a friend of mine have zero problems with uTox alpha on XP.

**Comment by avoidr** [comment]
I'm just guessing, but is your profile in a path with Unicode characters? E.g. does your username contain cyrillic or something?

**Comment by Vomitlord** [comment]
No, latin & numbers

**Comment by Vomitlord** [comment]
Ah, yes, you was right, sorry for it! Just haven't noticed.

**Comment by avoidr** [comment]
No problem!
