### ISSUE TITLE
Libraries to compile uTox v0.16.1

### ISSUE THREAD

**Issue by username1565** [uTox/uTox#1402]
### Overview

1. uTox version: v0.16.1
2. Operating system: Windows XP
3. Desktop Environment/Window Manager (Linux/BSD only): none.

### Issue
>Write your issue here.

I just try to compile uTox v0.16.1, from this source code: https://github.com/uTox/uTox/tree/v0.16.1

[Here](https://github.com/uTox/uTox/blob/v0.16.1/docs/BUILD.md) I see, the following info:

_________
### Compiling for Windows

Dependencies:

|   Name       | Required |
|--------------|----------|
| cmake >= 3.2 |   yes    |
| filter_audio |   no     |
| libvpx       |   yes    |
| openal       |   yes    |
| opus         |   yes    |
| toxcore      |   yes    |

The dependencies can be downloaded from here: https://build.tox.chat/ (Make sure you grab the right bit version.) All the libraries should be place in $UTOX_ROOT/libs/windows-x64/.

You will need a working Cygwin environment or Unix desktop to compile windows.

For 32 bit:
```bash
git clone https://github.com/uTox/uTox.git
cd uTox/
mkdir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchain-win32.cmake" -DTOXCORE_STATIC=ON ..
make
```

For 64 bit:
```bash
git clone https://github.com/uTox/uTox.git
cd uTox/
mkdir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchain-win64.cmake" -DTOXCORE_STATIC=ON ..
make
```

_________
But I cann't find libraries on https://build.tox.chat/. There is so many libraries.
Can you tell me the links to libraries, with compatible with that version?
I want to get after compilation, the working portable executable (x86, win32) for windows,
which is working on Windows XP without any bugs.
I see this file: https://downloads.utox.io/stable/uTox_win32.exe
is working on Windows XP, but if pathways contains only latin characters.

I want to get this file from the source code, and fix this, but there is no any link to the source code and libraries, compatible with this uTox version.

**Comment by g4jc** [comment]
The libraries are linked directly from the [Compiling](https://github.com/uTox/uTox/blob/develop/docs/BUILD.md#windows) page and have the latest versions. I made a quick video tutorial that should help you out : https://ufile.io/glkaxl54 (WMV format)

**Comment by g4jc** [comment]
Here's an extra quick cheat sheet as well from my notes:
```
Cygwin Packages Required (Use View -> "FULL" to install latest versions):

cmake
git
make

# If you have 32bit use i686 here
mingw64-x86_64-gcc-core
mingw64-x86_64-gcc-g++
# these are optional but highly recommended tools for the Cygwin environment
unzip
wget
nano
patch

From Cygwin terminal:
mkdir ~/projects
cd ~/projects
git clone --recursive git://github.com/uTox/uTox.git
cd uTox
git checkout window_coord_debug # See bug #1400
mkdir -p libs/windows-x64
cd libs
wget https://build.tox.chat/view/libtoxcore/job/libtoxcore-toktok_build_windows_x86-64_static_release/lastSuccessfulBuild/artifact/libtoxcore-toktok_build_windows_x86-64_static_release.zip
wget https://build.tox.chat/view/libopenal/job/libopenal_build_windows_x86-64_static_release/lastSuccessfulBuild/artifact/libopenal_build_windows_x86-64_static_release.zip
wget https://build.tox.chat/view/libsodium/job/libsodium_build_windows_x86-64_static_release/lastSuccessfulBuild/artifact/libsodium_build_windows_x86-64_static_release.zip
wget https://build.tox.chat/view/libvpx/job/libvpx_build_windows_x86-64_static_release/lastSuccessfulBuild/artifact/libvpx_build_windows_x86-64_static_release.zip
wget https://build.tox.chat/view/libopus/job/libopus_build_windows_x86-64_static_release/lastSuccessfulBuild/artifact/libopus_build_windows_x86-64_static_release.zip
wget https://build.tox.chat/view/libfilteraudio/job/libfilteraudio_build_windows_x86-64_static_release/lastSuccessfulBuild/artifact/libfilteraudio.zip
unzip -o '*.zip'
mv bin include lib share windows-x64/
cd ~/projects/uTox
mkdir build
cd build

## Prepare Debug Winx64
cmake -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchain-win64.cmake" -DTOXCORE_STATIC=ON ..

## OR Prepare Release Winx64
cmake -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchain-win64.cmake" -DTOXCORE_STATIC=ON -DCMAKE_BUILD_TYPE=Release ..

make

uTox.exe will be in ~/projects/uTox/build when finished.
```

**Comment by username1565** [comment]
Hello, @g4jc. Thanks for your answer.
But I wanted x86 libs to compile uTox v0.16.1 and earlier, in to `uTox_winXP.exe`.
I cann't find this libraries, because old links not working, 
and I cann't compile this libraries, because so many commits was been after stable XP-version `uTox v0.7.0`.
So [here, on this branch](https://github.com/username1565/uTox_winXP),
I just used the already pre-compiled XP-binaries,
with ability to modify the binary data inside Portable-Executable,
by editing hex-data of default ports and nodes, using javascript.
But I cann't decompile this into the source code, to edit this and fix some bugs.

**Comment by GrayHatter** [comment]
>  by editing hex-data of default ports and nodes, using javascript.

interesting... I mean I knew javascript **could** do that, but never thought anyone actually *would*...

But anyways there's zips and tarballs for every published version. If you have a working copy that you want to edit, you can get the version from the title bar and download the source for that version of uTox... As far as libraries, you can find the source for all of them, and then compile them from their current or old versions just as you would compile uTox. The travis build scripts from the older version of uTox will tell you the last verified version for each library. 

ProTip: you don't actually have to do that, if you're able to connect to the DHT at all, toxcore will save new peers you can connect to in the tox save file. If you don't have ANY valid peers (I doubt that) you can start up another working copy on your local network, add them both as a friends, then when the local network goes looking for your friends, it'll download a new list of peers from them. Just make sure you trigger a save of the tox profile before you close, and you'll have an updated peer list. No recompiling needed.... But really, install Linux, or a newer version of windows. You don't need to use XP

**Comment by username1565** [comment]
Here is this libraries, but still without source codes: https://github.com/blueclouds8666/uTox_XP/blob/develop/COMPILE32.md
Maybe, by versions, you can find the source codes, and maybe you can provide the instructions to compile this into binary-libraries, which will be compatible to build utox for XP.

_best regards_
