### ISSUE TITLE
Provide a macOS build for 0.17.1

### ISSUE THREAD

**Issue by ddobrev** [uTox/uTox#1410]
There's also the unpleasant issue of µTox not remembering the size and position of the main window and always going full screen instead. But I'd like to test 0.17.1 first before reporting a separate bug.

**Comment by ddobrev** [comment]
Hello, will there be a release of 0.17.1 for macOS? [Your build for macOS is healthy](https://travis-ci.org/uTox/uTox/jobs/628202727), is there any trouble preventing you from uploading a DMG?

**Comment by GrayHatter** [comment]
We don't like to ship binaries we don't control. If you want to clone the repo, and have travis upload the binary somewhere, you're more than welcome to do that. But that's not something any of the devs are willing to do, officially

**Comment by ddobrev** [comment]
@GrayHatter thank you for your reply. I don't understand, however, what you mean by saying you don't control these binaries. They are your code built by your scripts so what exactly is out of your control? In addition, 0.17.0 has a DMG, why would 0.17.1 not?

**Comment by ddobrev** [comment]
@GrayHatter in addition, what do I need to do in order to have the DMG generated and uploaded?

**Comment by ddobrev** [comment]
@GrayHatter I have found a reliable way to reproduce a crash on macOS. I would like to check if your latest code still has it before I report a bug. But I can't. So let me ask you again: how can I easily obtain a DMG for µTox 0.17.1?
