### ISSUE TITLE
turning IPv6 off on windows 10 causes a crash and settings are reset to defaults

### ISSUE THREAD

**Issue by ghost** [uTox/uTox#1416]

**Comment by avoidr** [comment]
Hello, could you please test the linked PR? Thanks.

**Comment by goleo108** [comment]
@avoidr I am no longer running windows :/

**Comment by avoidr** [comment]
Oh, oops. No problem then, someone else will see.
How about some BSD?

**Comment by goleo108** [comment]
@avoidr I can only test on Void Linux with musl libc, I gave up on *BSD

**Comment by avoidr** [comment]
You can do that, although I'm running Void with musl, too :P
