### ISSUE TITLE
typing password floods the log with "Toxcore: Couldn't decrypt, wrong password?"

### ISSUE THREAD

**Issue by goleo108** [uTox/uTox#1418]
why not be intelligent and simply wait when user presses Enter?

**Comment by GrayHatter** [comment]
Because then you'd need to press enter.

Why do you think that's more intelligent?

You're probably right about the log level though... perhaps it shouldn't be `LOG_ERR`

**Comment by goleo108** [comment]
because it's ridiculous to always try to decrypt especially when password is long

**Comment by GrayHatter** [comment]
I don't think it's ridiculous, I like that's faster.

**Comment by avoidr** [comment]
I don't know if it should be something other than `LOG_ERR` — decryption fails, that's an error. And I don't think it's a big deal anyway, as it's debug output and does not impair usage of the program, or even debugging.
