### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Valinwolf** [uTox/uTox#1419]
### Overview

1. uTox version: 0.17.1
2. Operating system: Arch Linux
3. Desktop Environment/Window Manager (Linux/BSD only): Cinnamon

### Issue

utox.io is currently down. is utox.org replacing utox.io? If so, it should be reflected in the project page and docs.

**Comment by avoidr** [comment]
utox.org is not replacing utox.io. The website is down for now and may stay down.
Thanks for bringing this up.

**Comment by Valinwolf** [comment]
Is it a funding issue?

**Comment by avoidr** [comment]
It is not a funding issue. Rather, it is a resource issue. The most up-to-date source of information on uTox is this repo anyway, and I don't think uTox will be negatively affected by not having a website.
