### ISSUE TITLE
integration with vim 

### ISSUE THREAD

**Issue by OrionRandD** [uTox/uTox#1423]
### Overview

1. uTox version:
2. Operating system:
3. Desktop Environment/Window Manager (Linux/BSD only):

### Issue

Could you make utox area text to be integrated with vim? It would bring lots of power to it. Like spellchecking...

**Comment by avoidr** [comment]
Can you give an example of how you envision this to work?

**Comment by OrionRandD** [comment]
I thought about something like withexditor server where we install the server and the plugin, for example in firefox. Then we can edit text areas with gvim by clicking the right mouse button and choosing edit with gvim. It is very handy. You can test the setup from here:
https://github.com/asamuzaK/withExEditor
https://github.com/asamuzaK/withExEditorHost
https://addons.mozilla.org/en-US/firefox/addon/withexeditor/
Perhaps asamuzaK can give you good ideas about it. 
He is very responsive and helpful...

**Comment by avoidr** [comment]
Thanks, that sounds very interesting, I'll give it a look.

**Comment by OrionRandD** [comment]
I hope things work for utox. I also asked it on github qtox.
You can install it on some browsers now. The setup will give you a list of supported browsers: firefox, chromium, vivaldi and, I think, others....

**Comment by avoidr** [comment]
Is that something like editing git commit messages with an external editor, or is it different?

**Comment by OrionRandD** [comment]
You can edit any text area with gvim using that setup.
For example, I am writing to you now inside gvim which I fired up as I told you before.
The best way to see it working is installing it yourself.
Also, as I said, contact withexditor developer. 
He, perhaps, can help you to bring gvim into utox...

**Comment by avoidr** [comment]
That's out of scope for uTox and its resources now, however nice that might have been, sorry to disappoint you.
But I did want to improve message composing, but it's further in the future for now.
Thank you for showing this to me, though!

**Comment by OrionRandD** [comment]
That's ok.
The reason why I asked these features to you - knowing that vim can bring the whole pack of its native features and installed plugins - is because English is not my
motherlangue and I know many people, like me, who would like to use it
to give English - and other language classes - so that uTox could be a
replacement for comercial Skype. So that, teachers should not depend upon 
on a Micro$oft closed source product so much. 
One of the main features for giving language classes on line is, of course,
having spellchecker on the chosen app. Otherwise, the students can
dismiss teachers automatically, thinking that if he/her cannot even
spell the taught language correctly, how can they be their students?
I will search for other opensource options...
Thx a lot anyway.

-----------------------

**Comment by avoidr** [comment]
So isn't a spellchecker enough for your use-case, though?

**Comment by OrionRandD** [comment]
It can be a starter, but vim brings lots of things in the pack - TAB autocompletion e.g. for speeding the work and other goodies...

**Comment by avoidr** [comment]
This is out of scope for uTox and doesn't align with its goals.
