### ISSUE TITLE
How to delete groups

### ISSUE THREAD

**Issue by OrionRandD** [uTox/uTox#1424]
### Overview

1. uTox version:
2. Operating system:
3. Desktop Environment/Window Manager (Linux/BSD only):

### Issue
I cannot see an option to delete groups that I have created or rename them.
How can I do that?

**Comment by avoidr** [comment]
Have you tried right-clicking the group in the roster?

**Comment by OrionRandD** [comment]
Yes. But, it shows no options. 
Perhaps knowing the file where that sits will be easier. 
I am on debian...

**Comment by avoidr** [comment]
What version of uTox are you using?

**Comment by avoidr** [comment]
>Perhaps knowing the file where that sits will be easier.

What do you mean? The source file where the relevant code is?

**Comment by OrionRandD** [comment]
uTox version: 0.17.1
I mean. There must be a file where it is set to read/write permission where the groupchat0(1...) is written when it is created using uTox GUI... So, opening a terminal, accessing that file and removing the groupchat bit name, saving the file, should delete the groupchat upon opening the uTox GUI again...

**Comment by avoidr** [comment]
I don't understand the issue. I right-click the group and then click "Remove Group" or "Change Topic". You don't get the context menu when you right-click the group?

**Comment by OrionRandD** [comment]
I do not get that option. But, perhaps it is because I am using stumpWM
https://archive.org/details/TheStumpWMExperience
 and not a DM like xfce4, gnome or kde...
I will see...

**Comment by OrionRandD** [comment]
Ok. I will see. 
I tested in xfce4 and the delete/change groupname worked. 
So, the issue in not from utox itself...
Thx a lot.
But, still hoping gvim integration.

**Comment by OrionRandD** [comment]
Yeah. Right click does not work in stumpWM for utox.
Even using -vvvvvv option.

**Comment by avoidr** [comment]
Using `-v` is not supposed to fix anything. If it were so, that would be the default ☺ Have you checked the man page? The manual explains everything about a program, and what the options mean.
