### ISSUE TITLE
Friend request improvements

### ISSUE THREAD

**Issue by NicoHood** [uTox/uTox#143]
I just got a friend request from someone unknown.

However I didnt noticed that for a long time. It just appeared in my friendlist suddenly. I expected that linux adds a trigger to the chat (like on qtox). **However a friend request should be highlighted more.**

Also the guy put a long "story" inside the friend request. This text is only shown in the headline. So you better move it into a normal text message. Because otherwise you need to make the windows lager. But there is a limit of the window size, especially for laptops. So you ware not able to read all. Putting it into a normal message would make it better readable and can be logged, so you can look this up afterwards. I always have people asking me things already in the friend request (cause i set tox as my main contact address), and this is quite annoying.

A sound would also be nice. On linux you also have those popups, but i guess that is a bit complicated for now, idk?
##

**Comment by GrayHatter** [comment]
these are all good ideas, and simple-ish to implement

**Comment by tsudoko** [comment]
Moving the FR item to the top of the list might be a good idea

**Comment by NicoHood** [comment]
Also I cannot see who added me. There is only a cryptic name displayed.

**Comment by tsudoko** [comment]
@NicoHood I don't understand, do you mean the ID? Friend requests don't contain names by default, but one can include theirs in the message if they want to.

**Comment by NicoHood** [comment]
yes, that would make totally sense. Because i got a "Hey :) " message from a random number. However I could expect who that is, but i still do not know.

**Comment by GrayHatter** [comment]
We should also prepend the current name to the friend message if the user
leaves it as the default.

**Comment by NicoHood** [comment]
* It is reallt annying that friend requests are at the bottom.
* The icons are too big
* If i reorder the contacts they will be unsorted after reopening. always!
* Online contacts should be moved to the top automatically. This should avoid most sorting problems anyways.
* Something like favorites would be cool.

**Comment by tsudoko** [comment]
> The icons are too big
Which icons?

**Comment by NicoHood** [comment]
The icons of the buddies on the friend list.

If utox doesnt save the order, why can i change it at runtime? That is really annoying and should be fixed, for example by sorting via online status and name a-Z
