### ISSUE TITLE
Windows binaries unavailable

### ISSUE THREAD

**Issue by atgote** [uTox/uTox#1430]
### Overview

1. uTox version: 0.17.1
2. Operating system: Windows
3. Desktop Environment/Window Manager (Linux/BSD only):

### Issue

Cannot find where to download precompiled Windows binaries/installer. Some links are already dead, some binaries doesn't work at all...

Windows link at utox.org - utox_runner.zip - cannot download binaries.
Links at utox.chat are dead...

I think these should be updated at least with every new release. 

The 0.17.1 at first sight works very good. I think it deserves a working link...

**Comment by avoidr** [comment]
Yes, there are no recent binaries available. The issue is that development slowed down and all the platform devs are not active anymore, except for one Linux dev. And currently there is already enough to do in the Linux version. I wish someone helped with the other platforms, too.

Sorry it is like that for now, but things will be better.

**Comment by jasonbrown1965** [comment]
few things :)

1. same probs as @atgote, with screenshots and descriptive text, available for future searches?
2. won't bother opening new issue if no work being done ~ simple _!_
3. will post link to [qTox 64bit](https://github.com/qTox/qTox/blob/master/README.md#qtox) which seems to work on Win10 pro upgraded from clean install, or [32 bit](https://github.com/qTox/qTox/releases/download/v1.16.3/setup-qtox-i686-release.exe) 
4. option / suggestion / workaround: Could Windows Subsystem* Linux offer a new path for tox ?     ~ mybad if already raised.

 *?! Memory lapse: the inter-decadal DPE sleep-deprivation-experiment continues. 

. . .

**Comment by avoidr** [comment]
>with screenshots and descriptive text, available for future searches?

What do you mean? Is that a feature request?

>won't bother opening new issue if no work being done ~ simple !

:<

>will post link to qTox 64bit which seems to work on Win10 pro upgraded from clean install, or 32 bit

What do you mean? Is that a threat? :D

>    option / suggestion / workaround: Could Windows Subsystem* Linux offer a new path for tox ? ~ mybad if already raised.
>
>*?! Memory lapse: the inter-decadal DPE sleep-deprivation-experiment continues.

ㅇ一ㅇ
I would like to help you… but I'm not sure I can :D

I am not familiar with WSL.

**Comment by robinlinden** [comment]
I've built and attached a 64-bit Windows binary (and a signature for it) to the 0.17.2 release now. Please give it a try to see if everything works. :D
https://github.com/uTox/uTox/releases/download/v0.17.2/utox_x86_64.exe

**Comment by fcore117** [comment]
> I've built and attached a 64-bit Windows binary (and a signature for it) to the 0.17.2 release now. Please give it a try to see if everything works. :D
> https://github.com/uTox/uTox/releases/download/v0.17.2/utox_x86_64.exe

https://github.com/uTox/uTox/issues/1441

**Comment by atgote** [comment]
Thanks!
