### ISSUE TITLE
Crash, UDP or ipv6 off

### ISSUE THREAD

**Issue by fcore117** [uTox/uTox#1441]
1. uTox version: 0.17.2
2. Operating system: Win 10 x64

Switching UDP or ipv6 off causes instant crash.

**Comment by robinlinden** [comment]
uTox is hitting this assert:
https://github.com/TokTok/c-toxcore/blob/7f9f8045cd6f8d92559cdc9f7d297cf92e960e49/toxcore/tox.c#L612

**Comment by avoidr** [comment]
Yeah, this has been happening for a long time, and I'll try to fix this very soon.

**Comment by zoff99** [comment]
@avoidr  https://github.com/TokTok/c-toxcore/blob/7f9f8045cd6f8d92559cdc9f7d297cf92e960e49/toxcore/tox.c#L612
that assert will be removed soon in toxcore master.
so it will be more dangerous then if utox is not fixed.

**Comment by avoidr** [comment]
@zoff99 thanks for the heads up, it's really the next thing I wanna fix.
