### ISSUE TITLE
How to compile uTox for Windows without cmd.exe showing every time uTox is opened?

### ISSUE THREAD

**Issue by rwinist** [uTox/uTox#1443]
### Overview

1. uTox version: 0.17.1
2. Operating system: Windows 7

### Issue

I successfully compiled uTox 0.17.1 on Windows 7 several times following this [guide](https://github.com/uTox/uTox/blob/develop/docs/BUILD.md#windows), but I can't find the setting/argument/parameter that needs to be changed/omitted to skip showing the console window every time the built utox.exe is executed.

Every hint is appreciated! Thank you!

**Comment by avoidr** [comment]
Does this help? https://github.com/uTox/uTox/issues/1415#issuecomment-579503201

Btw, there is v0.17.2 now!

**Comment by redmanmale** [comment]
Try configure build with this command:
`cmake -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchain-win64.cmake" -DSTATIC_TOXCORE=ON -DCMAKE_BUILD_TYPE=Release -DSTATIC_ALL=ON -DENABLE_ASAN=OFF -DENABLE_TESTS=OFF ..`

**Comment by rwinist** [comment]
I was looking into the makefiles but couldn't find the answer...
With the new configure build command it works now! 

Now I'm running a slightly modified portable uTox 0.17.2 on Windows 7. I'm happy so far.

Thank you both for helping and contributing to the project - appreciated.

**Comment by avoidr** [comment]
>I'm happy so far.

I'm glad ☺
