### ISSUE TITLE
Add support for the ToxMe https lookup api

### ISSUE THREAD

**Issue by subliun** [uTox/uTox#145]
toxme will be dropping dns support on the 1st of January, 2016. Please transition to the https api [documented here](https://github.com/subliun/toxme/blob/master/doc/api.md) as soon as possible.

**Comment by cebe** [comment]
should be pretty easy to port this over: https://github.com/JFreegman/toxic/blob/master/src/name_lookup.c

**Comment by GrayHatter** [comment]
@cebe I may drop toxme support rather than use https. Currently working on adding that as a toxcore API.

**Comment by LittleVulpix** [comment]
@GrayHatter, the dns is turned off indeed. Antox, qtox and toxic are able to do the lookup over the https api.

**Comment by SkyzohKey** [comment]
@LittleVulpix No point in implementing this, we need a proper decentralized name resolution service (DHT based would be a must).

**Comment by GrayHatter** [comment]
You can't do distributed naming in a reasonable way, (please prove me wrong). 

@LittleVulpix I'm unlikely to write in support for https myself (you're welcome to open a PR if you need the feature). But only because I'm working on a way to do lookups inside the Tox network.

**Comment by GrayHatter** [comment]
tox-named will replace this.
