### ISSUE TITLE
Sometimes uTox config cuts off

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#1457]
### Overview

1. uTox version: 0.17.2
2. Operating system: Win 10

### Steps to reproduce

* get fresh uTox instance
* run it in portable mode
* close after sometime (doesn't really matter, just give it enough time to init properly)

In the Tox folder will be three files:
* tox_save.tox - OK
* utox_save.in~ - temp save file created by minIni
* utox_save.ini - cuts off like this:

```
[general]
save_version=3
utox_last_version=4354
send_version=false
update_to_develop=false
```

Sometimes there are fewer (1-2) or more lines (10-15).
Next time (run and close) there could be a little more lines or no file at all.

But once config would be successfully saved there won't be any further issues.

**Comment by redmanmale** [comment]
After some experimenting it looks like OS [Windows] terminates uTox before it could save whole config.
We should probably save config first time after launch. I'll look into it.

**Comment by avoidr** [comment]
Yes, I just checked, and the same problem exists on Linux. I always guessed it had to do with the SIGABRT when the Tox threads get killed in the wrong order.
Thanks for looking at this.
