### ISSUE TITLE
sharing screen

### ISSUE THREAD

**Issue by OrionRandD** [uTox/uTox#1472]
### Issue

It is not really an issue.
But a request: 
Is there a way of allowing utox to be able to share
the screen computer with the other user?
It would be great for teachers to teach students elsewhere
through using the internet and would be an alternative to ZOOM.
At least in a small scale chat, say, creating a Groupchat

**Comment by avoidr** [comment]
Well yes, that should be possible. You need to select the "Video Input Device" in "Audio & Video" settings. You select "Desktop" there.
