### ISSUE TITLE
live session - is it possible?

### ISSUE THREAD

**Issue by OrionRandD** [uTox/uTox#1474]
Does qtox allow me to share my screen? Say, to show me typing a Vim/Emacs live session to my students?

**Comment by avoidr** [comment]
You're in the wrong repo.

**Comment by OrionRandD** [comment]
Sorry. My question if for uTox....
Does uTox allow me to share my screen? Say, to show me typing a Vim/Emacs live session to my students?

**Comment by redmanmale** [comment]
Yes, you should select "Desktop" as "Video Input Device" in "Audio & Video" settings.

**Comment by OrionRandD** [comment]
@redmanmale Thx I lot  :)

**Comment by zoff99** [comment]
@OrionRandD if you want to share your screen to a large group of other persons, then this will be difficult

**Comment by OrionRandD** [comment]
@zoff99 Nope. Not for many people.
By the way, how many people do you think can be hold in the uTox sharing-screen?
