### ISSUE TITLE
Trying to disable IPv6 causes crash

### ISSUE THREAD

**Issue by bshouse** [uTox/uTox#1478]
### Overview

1. uTox version: 0.17.2
2. Operating system: Windows 10 Home 2004
3. Desktop Environment/Window Manager (Linux/BSD only):

### Issue

When I attempt to disable IPv6 in the settings, uTox crashes immediately. After restarting uTox, the IPv6 slider is still enabled. Not a critical problem as I really do not care if it tries, but uTox should probably not crash.

**Comment by bshouse** [comment]
May be relevant: There was a file transfer active when I attempted to turn off IPv6 and it crashed.

**Comment by bshouse** [comment]
Confirmed that it crashes even when a download is not running.

**Comment by avoidr** [comment]
Ok, this is getting embarrassing. I'll do my best to fix it this week.

**Comment by bshouse** [comment]
I love uTox. It works well. I just wanted to make sure you know. Thank you @avoidr !

**Comment by avoidr** [comment]
♥♥♥ 😊 Thank you! Very very much. We're all happy that you like uTox ☺

**Comment by redmanmale** [comment]
@bshouse 
As workaround you could disable IPv6 in `~/Tox/utox_save.ini` by setting `enableipv6=false` (when uTox is not running).

**Comment by bshouse** [comment]
This does work-around the issue. Note: the settings file for Windows is at `C:\Users\XXXX\AppData\Roaming\Tox\utox_save.ini` where XXXX is the windows username. Thanks again!

**Comment by eclipseo** [comment]
This happens in Fedora 32 too.

```
Steps to Reproduce:
1. Open uTox
2. Go to the 'Advanced' tab in settings
3. Enable/disable any of the options 'IPv6', 'UDP', or 'Proxy'
```

https://bugzilla.redhat.com/show_bug.cgi?id=1830275

**Comment by fcore117** [comment]
This is very old bug, devs please update a patched binaries when you have found best way to patch it.

**Comment by avoidr** [comment]
Hello everyone, could you please test the linked PR if it fixes the issue for you? Kind thanks.

**Comment by fcore117** [comment]
avoidr: hello, do you have x64 binary to test lastest changes? ...or if it already works then maybe consider releasing emergency update that represents uTox more stable for newcomers who download uTox.

**Comment by avoidr** [comment]
If you're involved in packaging for the distro you use, you can send this patch to the package:

https://raw.githubusercontent.com/void-linux/void-packages/67ca22b91375b91ab885647a4a31fbb87f1d5aa2/srcpkgs/utox/patches/0001-Fix-crash-when-changing-toxcore-related-settings.patch

I've already done so for Void Linux.

@yangfl, you still maintain the package on Debian, right?

Thanks.

**Comment by avoidr** [comment]
@yangfl, please update the packages on Ubuntu. The latest release contains the fix for this crash. Thanks a lot.

P.S.: The homepage in this package can be deleted, that domain has expired and uTox does not have a website anymore.
