### ISSUE TITLE
Just saying I'm done.

### ISSUE THREAD

**Issue by Tcll** [uTox/uTox#1497]
regarding the [last issue](https://github.com/uTox/uTox/issues/1323) I wasn't allowed to end on, I'm ending it here.
(and will not be responding to any further commentary)

@avoidr you were well on your final steps towards peacefully ending this issue,
but that load of ignorant, incompetent dribble you've decided to excrete in a bucket and dump on me will be your undoing.

> My binary is mine. Go make your own.

you've just proven you can't be competent by this statement alone.

I don't take kindly to being told to build it myself by an irresponsible dev who can't do their job for everyone else.
(yes it's YOUR job to build (and test) your source for everyone else, just like any other sane developer on any other OS)

once I'm done releasing an appimage of this (once finished): (which I guarantee WILL work for you)
![pending_title](https://user-images.githubusercontent.com/773959/100937358-e842f700-34c0-11eb-9e51-e45649bd1903.png)
I'll be working on my own tox client as well and effectively replace every client but (if not even) qtox,
because apparently nobody else can do a decent job to even try.

I'll certainly make sure nobody else is forced to build my source unless they want to.
and I'm not hindering anything either, I'm moving things along and making things easy for everyone else.
(it's their choice if they want to code, not yours, not mine, nor the repo owner's)

if you can't get any appimage to work for you, then you're doing something wrong (like running as root)
don't blame everyone else because you can't do something right.

I'm sick of this disgusting, incompetent, elitist, "F you, build it yourself" attitude from the linux community.
unless you guys are actually trying not to have a community, and actually want linux to die.
if you want traditional package managers to fail, then by all means, keep doing what you're doing and keep hindering everyone else.

I'm not the only one you've P'd off.

also, if you can't trust [this page](https://github.com/uTox/uTox/releases) to provide binaries on
then you can't trust the repos either.
otherwise, if you can do such a stupid thing to provide an \*.exe, then you can also do such a stupid thing to provide an \*.appimage.
gotta be consistent with trust in downloading untrusted binaries from random websites like https://github.com/uTox/uTox ;D

I'm sorry to anyone else further reading this, but avoidr is not on the side of the users.
I will no longer be supporting this project unless a major apology is given.

**Comment by avoidr** [comment]
No apology will be given and no AppImage will be provided.

You are not welcome here.

Goodbye.

**Comment by GrayHatter** [comment]
@Tcll I just redacted a bunch of your OP because you can't open an issue just to bad mouth devs... upset or not, that crosses a line. 

Other than that, y'all play nice now!
