### ISSUE TITLE
utox default build using 32 terabytes of VIRT - caused by asan?

### ISSUE THREAD

**Issue by clort81** [uTox/uTox#1531]
1. uTox version:  git master, 2021-02-13
2. Operating system: linux aarch64
3. Window Manager: openbox
gcc-10
tox 3.21.4-1
python 3.9.1

After build and running utox it reserves a lot of ram.

```
PID    PR    VIRT    SHR S  %CPU     TIME+    DATA COMMAND
22945  20   32.0t   2236 S   1.0   7:17.10   28.0t utox
```
Build options are:
```
Build options:
- CMake Module Path:        /pr/tox/uTox/cmake/
----------------------------------
- Add ASAN:                ON
- Link-Time Optimization:  ON
- Error on Warning:        OFF
- Filter Audio:            ON
- Static uTox:             OFF
- Static Toxcore:          OFF
- Static DBus:             OFF
- Static Filteraudio:      OFF
- Static Opus:             OFF
- Static Sodium:           OFF
- Static VPX:              OFF
-- Platform Options --------------
- Enable DBus:             ON
- Enable Tests             ON
* CMake system is 'Linux'
* CMake build type is ''
* C Compiler is '/usr/bin/cc' with the following flags:
* C flags for Debug:       -g
* C flags for Release:     -O3 -DNDEBUG -Os
* C flags for all types:   -O2 -march=native -mcpu=native -mtune=native -funsafe-math-optimizations -Wall -Wextra -Wpointer-arith -Wimplicit-fallthrough=5 -Werror=implicit-function-declaration -Wformat=0 -Wno-misleading-indentation -fno-strict-aliasing -fPIC -fno-common -flto -fsanitize=address -fno-omit-frame-pointer -DAUDIO_FILTERING=1
```
I didn't build with debug flags.  I notice -fsanitize=address is enabled for the default cmake builds.  Here's output from the address sanitizer:
[asanout.txt](https://github.com/uTox/uTox/files/5975572/asanout.txt)

Trying a barebones build:
```
 Build options:
 - CMake Module Path:        /pr/tox/uTox/cmake/
 ----------------------------------
 - Add ASAN:                OFF
 - Link-Time Optimization:  OFF
 - Error on Warning:        OFF
 - Filter Audio:            OFF
 - Static uTox:             OFF
 - Static Toxcore:          OFF
 - Static DBus:             OFF
 - Static Filteraudio:      OFF
 - Static Opus:             OFF
 - Static Sodium:           OFF
 - Static VPX:              OFF
 -- Platform Options --------------
 - Enable DBus:             OFF
 - Enable Tests             OFF
 * CMake system is 'Linux'
 * CMake build type is 'Release'
 * C Compiler is '/usr/bin/cc' with the following flags:
 * C flags for Debug:       -g
 * C flags for Release:     -O3 -DNDEBUG -Os
 * C flags for all types:   -O2 -march=native -mcpu=native -mtune=native -funsafe-math-optimizations -Wall -Wextra -Wpointer-arith -Wimplicit-fallthrough=5
 -Werror=implicit-function-declaration -Wformat=0 -Wno-misleading-indentation -fno-strict-aliasing -fPIC -fno-common
```
This configuration yields a normal looking VIRT:
```
    PID  PR    VIRT    SHR S  %CPU     TIME+ COMMAND
  83452  20  485024  19752 S   2.0   0:00.97 utox
```
I haven't seen this behavior before recent builds.   Is there anything I should do to identify the cause?

**Comment by zoff99** [comment]
thats normal for ASAN. it's not really using all that memory.

**Comment by zoff99** [comment]
@clort81 ```On 64-bit platforms AddressSanitizer maps (but not reserves) 16+ Terabytes of virtual address space. This means that tools like ulimit may not work as usually expected.```

https://clang.llvm.org/docs/AddressSanitizer.html#id14

**Comment by clort81** [comment]
Thanks zoff99!  Maybe  -fsanitize=address should be disabled for default build?

**Comment by avoidr** [comment]
> Thanks zoff99!  Maybe  -fsanitize=address should be disabled for default build?

In my opinion it definitely should, why is it even enabled? That's a
developer tool. But actually with uTox being so broken, maybe it's
better enabled… I don't know.

Same as LTO. It doesn't do anything, it just makes the linking stage
take forever.


Thanks, zoff99, for the hint.

**Comment by zoff99** [comment]
@avoidr another hint: LTO is not what makes linking take so long. its the optimizer. ```-O3``` or ```-O2```
try to compile with ```-O0``` that links almost instantly on my system.
