### ISSUE TITLE
Direct APK MD link is broken

### ISSUE THREAD

**Issue by Sondro** [uTox/uTox#1536]
This one works (Google requires you to have a Google account): https://apkpure.com/utox/tox.client.utox

I read uTox for Android is obsolete in another issue, but it was still fun to set the DPI @ 250% after a 2 minute tap battle & get something viewable. It's also only 1.5mb vs aTox's 13+mb.

Maybe you could archive & redirect it under 0.15 releases if it's not already there?

**Comment by avoidr** [comment]
>It's also only 1.5mb vs aTox's 13+mb.

But aTox actually works and uTox Android is really old and while it's cool, it's nothing that would be useful to any user.

Please use aTox. It has the youngest and cleanest code and is in very active and sane development. And 13 MB is on the low end for nowadays' standards. The dev takes great care, even to require as few Android permissions as possible. Personally I trust aTox so much, I even run it on my own phone!
