### ISSUE TITLE
Where is history stored on macOS?

### ISSUE THREAD

**Issue by viertelb** [uTox/uTox#1547]
I know it is currently not maintained. But does anybody know where the history file is located on macOS?

**Comment by GrayHatter** [comment]
It should be in your home directory ~/.config/tox there's also an export to plain text button in friend settings that you can access by right clicking on a friend.

**Comment by viertelb** [comment]
There is no such option in version 0.17.0 on macOS (although I am sure I saw it somewhere else), but I was able to access the plain files per user, thanks!
