### ISSUE TITLE
Windows 11 uTox shutting when opened

### ISSUE THREAD

**Issue by HillGnur** [uTox/uTox#1562]
### Overview

1. uTox version: v0.18.1
2. Operating system: Windows 11
3. Desktop Environment/Window Manager (Linux/BSD only):

### Issue

uTox just keep closing when I open it, no action is made on the program, it just shuts without any errors.

**Comment by HillGnur** [comment]
Also, tried with admin permissions.

**Comment by PsilonOdoo** [comment]
Did You have OBS installed?
Check Your system event log.
Maybe same issue
https://github.com/uTox/uTox/issues/1563

**Comment by HillGnur** [comment]
Uninstalled OBS and it worked fine! Thx @PsilonOdoo
