### ISSUE TITLE
sharing PNG or any other image doesn't have a preview 

### ISSUE THREAD

**Issue by DeerSpotter** [uTox/uTox#169]
if i do a screen shot a image appears. but if save the same file and drag into chat to share it will only look like a file is being shared, no preview. Windows 10
##

**Comment by GrayHatter** [comment]
I think I know what you mean, but just in case, can I get a little more information here?

**Comment by DeerSpotter** [comment]
Attaching images doesn't generate any previews. That was a big reason we went with this client over other chats is when you took a screenshot it showed the full image. 

It would be nice when you shared a file that is a image it show to full preview of it.

**Comment by cebe** [comment]
We could maybe reuse the gtk file selector preview code to add inline preview for files.

**Comment by benwaffle** [comment]
wouldn't work inline, unless utox switched to gtk

**Comment by GrayHatter** [comment]
@cebe @benwaffle I means he want's image files to be sent inline instead of as a normal file. That's something that utox should be able to do without gtk.

It's also not a bad idea to reuse the same preview code for selecting files when using GTK file chooser
