### ISSUE TITLE
video/audio device hotplug support

### ISSUE THREAD

**Issue by sylware** [uTox/uTox#201]
With pulseaudio, we have a kind of hotplug, but it does not work with v4l devices (I did not check with alsa).
In audio/video parameters, the "lists" of available devices should be updated each time we want to select a device.
I did not check hot removal.
##

**Comment by GrayHatter** [comment]
I'm aware of this issue, solution pending!

**Comment by sylware** [comment]
stale, and have not been a tox user for ages.
