### ISSUE TITLE
No emojis in Windows Client

### ISSUE THREAD

**Issue by func0der** [uTox/uTox#211]
Am I stupid or those missing?

I got those missing character rectangles from an OS X client.

I am on Windows 7. Might that be the problem?
##

**Comment by redmanmale** [comment]
If they are Unicode-characters they are system-wide. It's likely they from new Unicode standart and Win7 just haven't updates for this (yet). On Windows 8.1 and above most of them works just fine.

Otherwise ping me and I'll reopen this.
