### ISSUE TITLE
webcam video resolution selection

### ISSUE THREAD

**Issue by sylware** [uTox/uTox#217]
The webcam video resolution is important where bandwidth becomes narrow. We should be able to select the video resolution in the client in order to get a kind of coarse grained bandwidth control.
##

**Comment by GrayHatter** [comment]
Why do you want to control video resolution? Is it just to gain bandwidth control?

**Comment by sylware** [comment]
On Sat, Feb 27, 2016 at 09:04:13AM -0800, GrayHatter wrote:
> Why do you want to control video resolution? Is it just to gain bandwidth control?

For me, the primary use would be bandwidth control indeed.

I use tox almost every day, from one side of the world to the other side. I
_must_ reduce the resolution in order to get a usable video call (usually
160x120 or 176x144 on both sides).
Sometimes my girlfriend on the other side of the world is on a windows machine
(rarely), unable to reduce the default resolution of the webcam (in gnu/linux,
cheese program will do). Then we must use audio only call just because she
cannot set the webcam default resolution. :(

-- 
Sylvain

**Comment by x368** [comment]
at least on Linux this is easy: (including a typo correction) this code is tested

    --- src/xlib/v4l.c.orig
    +++ src/xlib/v4l.c
    @@ -113,9 +113,24 @@
         fmt.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
     
         if (-1 == xioctl(utox_v4l_fd, VIDIOC_G_FMT, &fmt)) {
    -        debug("VIDIOC_S_FMT error %d, %s\n", errno, strerror(errno));
    +        debug("VIDIOC_G_FMT error %d, %s\n", errno, strerror(errno));
             return 0;
         }
    +/* see if we need to change the resolution */
    +    {   char *p;
    +        if((p=getenv("UTOX_VIDEO_SET_WIDTH")))
    +            fmt.fmt.pix.width = atoi(p); /* the kernel is to check anyway */
    +        if((p=getenv("UTOX_VIDEO_SET_HEIGHT")))
    +            fmt.fmt.pix.height = atoi(p); /* the kernel is to check anyway */
    +        if(-1 == xioctl(utox_v4l_fd, VIDIOC_S_FMT, &fmt)) {
    +            debug("setting %dx%d failed with error %d, %s\n", fmt.fmt.pix.width, fmt.fmt.pix.height, errno, strerror(errno));
    +/* ensure that the data is consistent despite the failure above */
    +            if(-1 == xioctl(utox_v4l_fd, VIDIOC_G_FMT, &fmt)) {
    +                debug("VIDIOC_G_FMT rerun error %d, %s\n", errno, strerror(errno));
    +                return 0;
    +            }
    +        }
    +    }
     
         /*if(fmt.fmt.pix.pixelformat != V4L2_PIX_FMT_YUYV) {
             debug("Unsupported video format: %u %u %u %u\n", fmt.fmt.pix.width, fmt.fmt.pix.height, fmt.fmt.pix.pixelformat,

**Comment by sylware** [comment]
stale and have not been a tox user for ages. Would need full re-test on recent tox.
