### ISSUE TITLE
Inconsistent behavior of the dropdown menu and the context menu

### ISSUE THREAD

**Issue by tsudoko** [uTox/uTox#232]
notsecure/uTox#233

> Basically, the context menus require two clicks, the dropdown menus require one.
> It would be more intuitive if you could just click once to get the list and either click on an item of the list or outside it to make it disappear.
> However, keeping the current behaviour as an alternative option would also be beneficial for users who may prefer it that way. It's possible to do it without having to add any additional options in the settings, like in OS X or GTK+ applications.
##

**Comment by GrayHatter** [comment]
@tsudoko how important do you think this is?

I can do it but it's a considerable amount of work. Do you want to

**Comment by tsudoko** [comment]
I don't think it matters a lot *right now*, but some less tech-savvy users might find the current behavior a bit confusing.

**Comment by redmanmale** [comment]
Fixed in #1093.
