### ISSUE TITLE
Problems in the Video Preview

### ISSUE THREAD

**Issue by dcapeletti** [uTox/uTox#251]
Hello, I have version 0.7. To preview any video source, be my camera or desktop, you can not close the preview. The dialog box display, pressing the button to close the window is completely blank.
![utox webcam previ error](https://cloud.githubusercontent.com/assets/5890886/13929697/358dffbe-ef7a-11e5-94e0-5a554177b459.png)
##

**Comment by dcapeletti** [comment]
Add. Every time I press the Close button, a message appears on the terminal:
uToxVideo:	video already stopped!
uTox:	Closing video feed

**Comment by GrayHatter** [comment]
@dcapeletti try again in v0.8.2 and then reopen this

**Comment by dcapeletti** [comment]
I'm using version 0.8.1 and the problem continues. How do I download the version 0.8.2?

**Comment by GrayHatter** [comment]
I'll take another look

**Comment by endoffile78** [comment]
This seems to have been fixed. Reopen this if you are still having problems.
