### ISSUE TITLE
Scrollbar bottom cap is garbled at certain DPI settings

### ISSUE THREAD

**Issue by flussence** [uTox/uTox#265]
Works fine: 70%, 90%, 100%, 120%, 140%
Broken: others between 60-150

I didn't test the rest but given the even/odd pattern, looks like it may be an int division truncation bug?

Am running v0.7.0-1-g9524f (but this has been around for a long time)
##

**Comment by redmanmale** [comment]
Must be fixed in #842.

**Comment by GrayHatter** [comment]
yup, thanks
