### ISSUE TITLE
Multiple forks with separate bugtrackers («Issues»).

### ISSUE THREAD

**Issue by 2a03** [uTox/uTox#27]
It'd be nice to clear things up — what's the current status of [notsecure/uTox](https://github.com/notsecure/uTox/) and which of the repos is «official» and «actively maintained» and, therefore, should get bugreports and pullrequests.

What about transferring ownership of previous repository to some community–associated account instead of forking?
##

**Comment by stal888** [comment]
This repo is the maintained one since notsecure ran away to play dota after gsoc '13. New issues and PRs go here.

**Comment by GrayHatter** [comment]
I'm still closing issues over there when they get fixed here, but only because I'm too lazy to copy them over here

**Comment by redmanmale** [comment]
I think it could be closed by now.
