### ISSUE TITLE
0.7.0 (very small) bugs

### ISSUE THREAD

**Issue by gity-up** [uTox/uTox#275]
I am extremely grateful to the devs for this program. Gracias. I observed the following:
1. Voice coming from Windows 10 users sounds like a monster is talking. I don't experience this when talking with users on Windows 7. (as a workaround I just mute my audio & use a cell phone instead)
2. The preview window will not close unless utox is closed.

None of these issues are the end of the world as 0.7.0 is delivering video proficiently. Let me know if I can provide any more useful info.
##

**Comment by GrayHatter** [comment]
I'm going to close this as stale. There's a big video change in the pipeline, and without more information about the audio. I can't fix that; either way #686 seems to be a similar issue that **should** fix this one as well.
