### ISSUE TITLE
message log should contain information on calls

### ISSUE THREAD

**Issue by cebe** [uTox/uTox#322]
Messages currently do not contain information on `Call started` and `Call ended` anymore.
it should also indicate when switching from video to audio mode and back.

**Comment by GrayHatter** [comment]
do you mean JUST in the active, or do you want that information logged to disk as well?

**Comment by cebe** [comment]
not sure about logging to disk but it should be displayed in the chat log. it may be useful in the log also sometimes things are exchanged as text while talking so in the log it would be good to see that something was written while a call was active.

**Comment by zestyr** [comment]
:+1: 
I'd like it to be in the log as well, including the duration of the call. 
Something like "Call ended: 2 hours 48 minutes"
