### ISSUE TITLE
BSOD on Surface Book running Windows 10

### ISSUE THREAD

**Issue by zoji3k** [uTox/uTox#344]
DRIVER_POWER_STATE_FAILURE

BSOD happens within 1-2 minutes of launching uTox. I'm running Windows 10 1511 with all driver and OS updates installed. The issue is present on my first (now RMA'd) Surface Book and on the replacement i just received.

**Comment by GrayHatter** [comment]
Really? uTox causes a BSOD on Win10? THAT'S AWESOME!

Are you sure it's uTox? i.e. If you run it, is there a predictable time that'll bluescreen? Is there anything that uTox does that seems to cause it?

**Comment by LittleVulpix** [comment]
That sounds very strange - but it is most likely not w10 specifically. If anything, I'd suspect the connected standby mode which tablets such as surface book have. I could test this on my w10 tablet if you're able to reproduce it again on the surface book and want more samples.

**Comment by GrayHatter** [comment]
I'd VERY much like to see the coredump, or perhaps any uTox output... not sure how you'd get that...

If you can make it happen on demand, let me know. OR if you're able or willing to troubleshoot let me know... Otherwise there's not much I can do.

uTox is developed for Windows on a Surface Pro 3, and I don't see ANYTHING like this.

**Comment by zoji3k** [comment]
And... I'm back. Sorry for the long absence. 

I am still running into the issue, but it is very intermittent. I've installed the latest round of driver updates, but the issue still persists. There doesn't seem to be anything specifically triggering it, but it happened again this afternoon. After the restart things have been fine so far.

**Comment by GrayHatter** [comment]
and it NEVER bluescreens when uTox isn't running?

**Comment by GrayHatter** [comment]
stale

**Comment by MaceWindu** [comment]
It could be an issue in driver similar to one tox have with some routers that hang when tox starts to use network (I have such crappy router).
I would recommend you contact driver developers after you identify which one crashes your system.
