### ISSUE TITLE
DPI Broken - Windows 10

### ISSUE THREAD

**Issue by gitgud-software** [uTox/uTox#351]
![2016-05-30](https://cloud.githubusercontent.com/assets/10673048/15654286/db4247cc-2660-11e6-8407-97ed6ba126b9.png)
# Pros
- Maximum Readability
# Cons
- Minimum Usability

**Comment by davidak** [comment]
The same thing happens on OS X with the latest 0.9.4 build.

I was able to maximize the window and set DPI back to 100%.
It stays at 100% after restarts.

**Comment by GrayHatter** [comment]
wow... that's big...

**Comment by A-Smile** [comment]
+1
Windows 7, 0.9.4 build.

**Comment by 2a03** [comment]
Win 7 x64, µTox (Alpha) (version : 0.9.5), from Jenkins:
![1](https://cloud.githubusercontent.com/assets/5808641/17421957/cf192c4e-5abe-11e6-860a-d2760a8b67b3.png)

Bug rarely manifests itself, no distinct steps to reproduce.
And that's how it looks in utox_save:
![2](https://cloud.githubusercontent.com/assets/5808641/17421980/fc849966-5abe-11e6-8c63-101f2af3cc0e.png)

**Comment by gitgud-software** [comment]
I get it every time the client automatically updates. I'd wager that it's some weird compatibility issue between each version. For now I just delete my utox_save every time it happens.

**Comment by Diomas** [comment]
I've got the same huge GUI issue after recent restart (not sure what was the previous version of uTox - i'm using utox_runner.exe)
![Huge GUI](http://i.imgur.com/Ej8rYJy.png)

windows 8.1

**Comment by redmanmale** [comment]
Probably stale.

**Comment by GrayHatter** [comment]
agreed
