### ISSUE TITLE
Add ability to toggle/mute sounds

### ISSUE THREAD

**Issue by hjc3000** [uTox/uTox#352]
The only option at the moment is to turn the ringtone on/off?

Ideally would be able to toggle other sounds such as contacts going online/offline.

**Comment by GrayHatter** [comment]
as a temporary work around, you can set your status to idle or do not disturb. Idle will disable messages and on/offline, DND will disable the ringtone as well

**Comment by GrayHatter** [comment]
fixed a while ago
