### ISSUE TITLE
Message queueing causes duplicate messages to be delivered

### ISSUE THREAD

**Issue by LittleVulpix** [uTox/uTox#368]
Exact same issue as in qTox: https://github.com/tux3/qTox/issues/2726

Implementation of the offline messages breaks this behavior, it seems.

Friend:

OS: 4.5.7-200.fc23.x86_64  (fedora 23)
uTox (Alpha) (version: 0.9.4)

Conversation with a friend:

> Vulpix, 20.06.2016 11:23:06:
> so I will do that
> 
> Cezi, 11:24:45:
> Ah and where is the bathroom?
> 
> Vulpix, 11:31:45:
> You don't have to list it
> 
> Cezi, 11:32:00:
> :/
> 
> Cezi, 11:32:06:
> :/
> 
> Cezi, 11:32:13:
> And the storage? Wouldn't that be 3+1
> 
> Cezi, 11:32:15:
> And the storage? Wouldn't that be 3+1
> 
> Vulpix, 11:32:18:
> Storage is also not listed
> 
> Vulpix, 11:32:24:
> Also I'm getting your messages 2x again!
> 
> Cezi, 11:32:33:
> Even now?
> 
> Cezi, 11:32:33:
> Even now?

`<he restarts utox>`

> Cezi, 11:32:56:
> It is glowing blue before it becomes black, not sure why
> 
> Cezi, 11:34:00:
> no idea why it's happening but I'm on uTox 0.9.4 alpha

`<we take a break>`

> Cezi, 13:26:47:
> O.o
> 
> Cezi, 13:26:51:
> O.o
> 
> Vulpix, 13:28:12:
> Getting it twice again :D
> 
> Cezi, 13:28:53:
> At least it's not 10x...
> 
> Cezi, 13:28:58:
> At least it's not 10x...

**Comment by GrayHatter** [comment]
I can't duplicate this at all, what can you tell me about his network -> your network?

Also, this bug is related to the network dropping, not to the qTox bug. That's a completely different issue.

**Comment by LittleVulpix** [comment]
Both of us on fibre optics, 300/30Mbit. And i've never seen this happen before with utox, hmm.

**Comment by GrayHatter** [comment]
Linux or windows for HMI?

**Comment by DraCezarus** [comment]
I'm working on Fedora, where I use uTox.
I've set up a script where I run "uTox -vvvv> utox% DATE_TIME% .txt".
I suppose to reveal the problem you need to log from the moment will duplicate texts.
When it happens again, I will present here the log from that moment.

**Comment by DraCezarus** [comment]
Here is [log](https://gist.github.com/DraCezarus/ba86ca97aad8946687c60012f988dd17#file-utox_27-06-2016_12-17-23_718576646-txt)

**Comment by LittleVulpix** [comment]
Here is what it looks like on my side. The duplicated message is highlighted.

> Vulpix, 27.06.2016 13:44:52:
> where it is
> 
> **Cezi, 14:04:36:**
> **What did you win?**
> 
> **Cezi, 14:04:38:**
> **What did you win?**
> 
> Cezi, 14:09:15:
> New avatar, saved as: Profiles\Vulpix\Avatars History\FoxyToxy\AVS-HASH-be9edd92.png
> 
> Vulpix, 14:37:15:
> what :D

**Comment by GrayHatter** [comment]
the issue seems to be uTox not getting a messages receipt for that message, but the message is still delivered by toxcore. I'm not sure where the root cause of the issue is, but I won't have a better idea until error handling is implemented in some sort when sending messages, rather than the current of assuming it'll work.

**Comment by GrayHatter** [comment]
stale, and unable to duplicate, if anyone sees this again, ping me so I can reopen this.
