### ISSUE TITLE
At low DPI "Audio/Video" tab is unclickable

### ISSUE THREAD

**Issue by hjaf23** [uTox/uTox#377]
Using Xubuntu 16.04 here. At latest uTox 64-bit client downloaded from http://tox.chat

When you go below %90 DPI "Audio/Video" settings tab becomes unclickable. The mouse icon doesn't change to hover state either.

**Comment by GrayHatter** [comment]
Hey, I can't seem to duplicate this one. I need some more info on this one. Does the tab not show up? or is it just unclickable?

Have you tried resizing the window?

Does it work at 90%, and above, and only below it's broken?

Are any of the other buttons misaligned?

**Comment by tsudoko** [comment]
For me it's unclickable for 80% and below, resizing the window doesn't seem to change anything.

**Comment by liwXO** [comment]
For me it's also unclickable at 80% and below.

**Comment by GrayHatter** [comment]
@tsudoko said he can't reproduce this anymore

Can you give me versions numbers @liwXO @HJafarli

**Comment by liwXO** [comment]
@GrayHatter My uTox version is 0.9.7 (Stable).

**Comment by redmanmale** [comment]
Confirmed on Windows 7 and 8.1 at 80% and below. At 90% and above it works fine (uTox v.0.9.7).

**Comment by redmanmale** [comment]
Fixed in v.0.11.1 on Win 8.1

**Comment by redmanmale** [comment]
Fixed in 0.12.1 on Win 7.

**Comment by robinlinden** [comment]
Works fine on 0.12.1 for all DPI settings 50% <= x <= 200% on Windows 10.
