### ISSUE TITLE
Program crashes using video with windows 10

### ISSUE THREAD

**Issue by Toxuser** [uTox/uTox#395]
On several computers (PC, Laptop, Tablet) the videofunction does not work under Windows 10 in any case. The program 0.9.4 crashes if I want to see the far person. As I tried it under Windows 7 everything works fine.

**Comment by Toxuser** [comment]
The program crashes furthermore. I tried Windows 10 german version 64bit and 32bit on several computers. I will give you feedback if the problem has been solved and the program works using the video function under windows 10.

**Comment by GrayHatter** [comment]
stale, @Toxuser if you can still make uTox v0.12.1 crash with a video call, please open a new issue.
