### ISSUE TITLE
[feature request] Ability to change «nospam» part of ToxID from µTox UI.

### ISSUE THREAD

**Issue by 2a03** [uTox/uTox#406]
### Existing behaviour

Tox ID now shown as a single line of hex digits, without distinction between _public key_, _nospam_ and _checksum_ parts.
### Intended behaviour
- [ ] Different parts of ToxID are either shown separately, separated with spaces (dashes, colons, other symbols), or highlited with different colours, while still maintaining the ability to copy ToxID as a whole.
- [ ] There is a message, that explains parts of ToxID and their intended purpose to the user, as well as the repercussions of changing _nospam_ value.
- [ ] There is a control, that lets users generate random _nospam_ in one click.
- [ ] There is a control, that lets users set their _nospam_ manually.
### For bonus points
- [ ] Ability to change _nospam_ by schedule (once in _n_ hours/days/weeks, etc.), or on every _n_ –th client start.

**Comment by GrayHatter** [comment]
Thanks for the easy to read issue!

Sure, why do you think these are needed features? (Just trying to prioritize them)

**Comment by 2a03** [comment]
Well, tox is not _that_ popular so that spam poses any significant problem _for now_. =)

However, apart from practical purposes this design also may serve as explanation to users, why toxcore doesn't store whole ID's, why there's no way to share ID's from contact list with other users, and so on.

**Comment by fcore117** [comment]
manual nospam would benefit future commercial contact too, as example: clock 10-16 i would use 710F7731 for buisness and in night i would use 8EE73FC0 to get contact requests only outside of buisness.

Developers correct if i am wrong but this way it should be possible to keep control when someone can contact or if i want i could abandon nospam(almost like taking new prepaid sim)

**Comment by GrayHatter** [comment]
@fcore117 IMO, that's the worst way to do it... You should just use separate ToxIDs

**Comment by fcore117** [comment]
It was just scenario but main idea would be make possible so friends can share my id to others until i decide i do not want that my id can be contacted by new users and change nospam. Those features would be useful in future when tox really starts to spread everywhere on this world.
