### ISSUE TITLE
Switch UI element visually broken

### ISSUE THREAD

**Issue by davidak** [uTox/uTox#421]
![bildschirmfoto 2016-08-31 um 01 43 08](https://cloud.githubusercontent.com/assets/91113/18111003/5594a624-6f1c-11e6-9ed2-44c260631745.png)

---

v0.9.8
OS X 10.10.5

**Comment by GrayHatter** [comment]
What's broken about it?

**Comment by davidak** [comment]
Well, it looks broken. White element on white background.

Maybe a design is missing or some graphic is not loaded.

**Comment by GrayHatter** [comment]
what should it look like?

**Comment by davidak** [comment]
A Designer should decide what fit's the UI of uTox.

There are a lot of designs of switches:

![](https://www.b4x.com/android/forum/proxy.php?image=http%3A%2F%2Fwww.visualnet.inf.br%2Fimagens%2Fb4a%2FUISwitchTOP.jpg&hash=25864df58e02287ccd0db3737e1beada)

If i should suggest something:

We have already this rounded buttons:

<img width="233" alt="bildschirmfoto 2016-09-01 um 12 20 54" src="https://cloud.githubusercontent.com/assets/91113/18164173/c23d9ace-703e-11e6-98b5-8d16bab51323.png">

(that are too big for the text btw)

so something like this would fit:

![serveimage](https://cloud.githubusercontent.com/assets/91113/18164199/efb52e54-703e-11e6-80de-61f98dce5d5c.jpeg)

When the setting is to activate a feature, a ✓ with green background is nice, not activated should be grey instead of red since red means danger.

**Comment by Encrypt** [comment]
The design of the switches that you are suggesting looks good @davidak!

I'll try to change them once I have time (i.e. once my MSc is over... that is to say in a few weeks).

**Comment by davidak** [comment]
@Encrypt Very good.

Can someone change the color of the white thing to dark grey until that?

**Comment by GrayHatter** [comment]
I like your suggestion ALOT A LOT! @Encrypt I hope you beat me to it, but if not I'll see if I can find time this weekend

**Comment by GrayHatter** [comment]
half fixed

**Comment by GrayHatter** [comment]
fixed a while ago by @tsudoko, and it looks awesome! thanks mate!
