### ISSUE TITLE
Displayed version numbers are not up to date

### ISSUE THREAD

**Issue by davidak** [uTox/uTox#422]
please use `VERSION` from `main.h` every time the version is displayed and update it before every release!

![bildschirmfoto 2016-08-31 um 01 45 08](https://cloud.githubusercontent.com/assets/91113/18111112/4ea5e688-6f1d-11e6-98a9-022e59c78d3f.png)

There are 3 different versions displayed in this screenshot. Also Core and ToxES and whatever follows that has no version...

(the correct version here is v0.9.8)

**Comment by GrayHatter** [comment]
that shouldn't be happening...

@stal888 what strange voodoo are you dooing?

**Comment by noplanman** [comment]
I noticed this as well. Confusing when updating 😕 It's like downgrading to a newer version or something.

Also, the versions for Core, ToxAV, ToxES, etc. are all v0.0.0.
Is that because they're still WIP or are the version strings not getting set properly?

**Comment by GrayHatter** [comment]
the toxcore versions are normal, they are all v0.0.0 but uTox should at least have the correct version.

**Comment by redmanmale** [comment]
Fixed in [this](https://github.com/uTox/uTox/commit/5951514612dae9f81f8f179a3455f4fb3bf6d38b) and several later commits.

**Comment by GrayHatter** [comment]
@redmanmale you can close issues now right?
