### ISSUE TITLE
Tox ID cannot be retrieved after transferring from q to u

### ISSUE THREAD

**Issue by derpypaws** [uTox/uTox#424]
I've been pretty messy and nonchalant with my Tox use, but hopefully the info still helps. I copied my profile after using qTox to the desktop, and renamed it to tox_save.tox before downloading uTox and putting it back in AppData/Roaming. I can get my contacts fine, but when I try to view my Tox ID to share it, the field is blank.

**Comment by GrayHatter** [comment]
@derpypaws is it still blank after restarting uTox?

What version of uTox are you using?

**Comment by derpypaws** [comment]
It was blank after a second try, yes. I was on 0.9.7. I went ahead and installed the most recent qTox and re-imported the profile so I could share my ID with a friend. Sorry if I'm not much help at this point, but I could try to re-create the issue in the near future..

**Comment by GrayHatter** [comment]
stale
