### ISSUE TITLE
Manpage gives different Git repository

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [uTox/uTox#438]
As I am new to uTox I don't know how the development of it exactly works, however in the uTox manpage from uTox `0.9.7` I got from the official Tox repository it says to report bugs and get the source code from these links:

```
CONTRIBUTORS
       Please see the list page: https://github.com/GrayHatter/uTox/graphs/contributors

BUGS
       Please report bugs on https://github.com/GrayHatter/uTox/issues

       The website for µTox can be found at http://utox.org/ and source code can be found at https://github.com/GrayHatter/uTox

```

So is that where I should report bugs rather than here? Or how does this work? As I am rather confused.

**Comment by SeventhSonOfASeventhSon** [comment]
Never mind, it seems I got confused about how this works, but I am figuring out now.

**Comment by tsudoko** [comment]
Report bugs here. I have a fix in [my `man` branch](https://github.com/tsudoko/uTox/tree/man), but it depends on some PRs which are not yet merged.
