### ISSUE TITLE
Reason to have pulse audio DONT_MOVE flag

### ISSUE THREAD

**Issue by tobiasBora** [uTox/uTox#448]
Hello,

I would like to know if there is any reason to have the pulseaudio flag DONT_MOVE, that makes impossible to change from pulseaudio the microphone input/output. It's quite annoying to always keep the same input/output, especially when I plug a new headphone...

Thank you !

**Comment by tobiasBora** [comment]
I found a solution, which is to put in the (new created) file  ```~/.alsoftrc ```

    [pulse]
    allow-moves=yes

Would it be possible to put it "by default" in the application ?

**Comment by GrayHatter** [comment]
uTox doesn't use pulseaudio by default. It uses openAL. So there's nothing I can change in code to enable that by default.

**Comment by tobiasBora** [comment]
And don't you think it would be a good idea to ask if the users wants to have "allow_move" enabled by default (for example the first time the user runs utox), and create the file if needed ? (Actually I don't even see where It would be usefull to keep allow_move disabled, so I don't think it would be too bad to create the above file by default).

Or at least, putting in the audio part a short text saying that it's possible to enable pulse audio input/output changes would be nice. I think it's somethink pretty usefull in utox to be able to change the input/outbut.
-- 
TobiasBora

**Comment by GrayHatter** [comment]
No, I don't think it would be a good idea for uTox to change settings on
software that uTox doesn't directly use. I'm sure I could come up with a
few times when you wouldn't want to allow someone to move an audio device.
Either way, this is an issue with pulse audio, not uTox.

I also don't think it would be a good idea to add a notice either. None of
the main platform used by uTox use pulse audio by default, so there's no
easy or clean way to display such a message.

**Comment by GrayHatter** [comment]
I'm going to close this, because my current plan is to replace openAL with portaudio.

If this issue still exists after that fix/change. Please open a new issue?

**Comment by tobiasBora** [comment]
All right. Do you know if you will do the change within 1 weeks, 1 month or 1 year ?

Thank you,

tobiasBora.

Le 20 octobre 2016 08:26:37 GMT+02:00, Gregory Mullen <notifications@github.com> a écrit :
>I'm going to close this, because my current plan is to replace openAL
>with portaudio.
>
>If this issue still exists after that fix/change. Please open a new
>issue?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/uTox/uTox/issues/448#issuecomment-255019934

-- 
TobiasBora

**Comment by GrayHatter** [comment]
I have no idea, more than a week or two seems likely. More than 3mo is
possible. More than a year seems VERY unlikely. But I can't give an
estimate until it gets a bit higher on my to do list.

**Comment by tobiasBora** [comment]
Ok thank you !

**Comment by praiskup** [comment]
Anything new on this?
