### ISSUE TITLE
Get Tox ID from already added friend (duplicate of #78)

### ISSUE THREAD

**Issue by matuskopo** [uTox/uTox#458]
Hi, when I want to view friend's tox ID in Friend Settings, it's trimmed in that textfield. How can I see full tox ID? bye

**Comment by redmanmale** [comment]
Textblock size depends on uTox window size.
So you could either widen uTox or select entire key via CTRL-A and copy it.

**Comment by matuskopo** [comment]
Hi. This is not true. Even if I have window size in Fullscreen or use CMD+A, last 12 chars are still missing.

**Comment by GrayHatter** [comment]
what version of utox are you using?

**Comment by matuskopo** [comment]
Oh, I'm sorry. I forgot to mention I'm using Mac OS version. In window title I have: Alpha 0.9.7. But in about window it's Version 1.0 (1)

**Comment by GrayHatter** [comment]
@stal888 ... help?

**Comment by GrayHatter** [comment]
@matuskopo are you talking about a friends ToxID, or their public key? The ToxID is longer, but uTox doesn't save it.

**Comment by matuskopo** [comment]
Oh, right. The label for that field is "Friend's Public Key", but value is the same as I had to insert when adding new contact, only it's trimmed. Simply, problem is I just can't copy this value and send it to anybody else to add this contact. I had to search for it in conversations on other services.

**Comment by robinlinden** [comment]
This is an upstreams thing. We could save the nospam you first added the contact with, but if the contact changes it you wouldn't know and the Tox ID you copied wouldn't work. There is ongoing discussion about changing the nospam system, but for now we can't fix it.
See #78 for more info.
