### ISSUE TITLE
DPI and Can't Connect

### ISSUE THREAD

**Issue by benzmiller** [uTox/uTox#459]
So for some reason now I can't connect and the DPI is messed up and said to report it. Version: 0.9.8 
![](http://puu.sh/s4R9h/bda4f61b11.png)

**Comment by GrayHatter** [comment]
@benzmiller yes, thank you for the bug report, I'm aware and I know how to fix it. (I think)

It's just going to take me a short while before I can release a new version.

You also can't connect?

**Comment by benzmiller** [comment]
No problem! Thank you for working on this.

I hadn't changed any settings, then suddenly I couldn't connect. I tried uninstalling and making sure I had the latest version downloaded, tried utox runner, most everything I could think of. That's when on the last try of downloading it the DPI issue happened.

**Comment by GrayHatter** [comment]
Try deleting the `utox_save` file in the AppData directory

It seems like the utox_save file was written incorrectly, which may have the proxy settings misconfigured. if you need help find me in #utox on freenode https://webchat.freenode.net/?channels=#utox

**Comment by GrayHatter** [comment]
be careful you don't delete the wrong file. the `tox_save.tox` file is all your profile information, meaning friend list, keys, everything

**Comment by benzmiller** [comment]
@GrayHatter That did it. I'm back online and back to regular DPI. Thanks!

**Comment by GrayHatter** [comment]
I added some an additional check to the UI code in #627
