### ISSUE TITLE
No A/V in develop branch

### ISSUE THREAD

**Issue by bonfus** [uTox/uTox#460]
Diff with fix is here: https://gist.github.com/bonfus/bbbe056486fcfdc05ad218c4ac8c453e

**Comment by GrayHatter** [comment]
this patch would likely drastically increase memory usage, ( but that's an existing bug that needs to be fixed by dynamically allocating the memory for the friends list)

**Comment by robinlinden** [comment]
@endoffile78 You fixed this when you made the friendlist dynamic, right?

**Comment by endoffile78** [comment]
@robinlinden Yeah this has been fixed. Closing.
