### ISSUE TITLE
DPI setting stuck in "BUG. PLEASE REPORT". So I'm reporting.

### ISSUE THREAD

**Issue by NatkaniecZM** [uTox/uTox#495]
![please report](https://cloud.githubusercontent.com/assets/15027589/20466894/db94ccc8-af7b-11e6-845d-24ddf981f53b.png)

Suddenly, out of nowhere, this happened. I don't know what else to add, I'm just following orders here.

**Comment by GrayHatter** [comment]
thanks for the bug report, It should be fixed in the next version (released tonight, or maybe tomorrow)

**Comment by GrayHatter** [comment]
this should be fixed already
