### ISSUE TITLE
utox won't start - Trace/breakpoint trap / Illegal instruction / Segmentation fault

### ISSUE THREAD

**Issue by svaens** [uTox/uTox#498]
After updating to "uTox version: 0.10.1"   
from version 0.9.7
uTox won't start, and reports, seemingly randomly, either

"Trace/breakpoint trap", "Illegal instruction", or "Segmentation fault" 
(see below command line run attempts)

sean@javahack ~ $ utox -v
Segmentation fault
sean@javahack ~ $ utox
Illegal instruction
sean@javahack ~ $ utox
Segmentation fault
sean@javahack ~ $ utox
Illegal instruction
sean@javahack ~ $ utox
Segmentation fault

Willing and able to troubleshoot. Please instruct how to proceed.

**Comment by robinlinden** [comment]
I'm guessing you compiled this yourself? If so, it's possible that we fixed this now. Try pulling the latest develop and build it again.

**Comment by svaens** [comment]
No, honestly I pulled it from the opensuse repo maintained by Anton Batenev. 
I'll try building it tomorrow and confirm or deny your suspicions ;)
thanks

**Comment by svaens** [comment]
actually, maybe it was a confused repo .. not sure. Uninstalled, removed the opensuse source (i'd used that to try and install qtox), re-added the source for xenial ... now 0.10.1 is working for me. 
Forget this then. Sorry!

**Comment by robinlinden** [comment]
Well, glad you got it sorted. Please get back to us if you run into problems again, and look forward to a new (more amazing) release soon(tm). :>

**Comment by GrayHatter** [comment]
For anyone watching. uTox doesn't support or endorse the opensuse repo. It's run by a developer I don't trust. But it is good to know they're shipping broken binaries :frowning_face:

Also you may have to force update in the future. v0.10.1 isn't going to be shipped. The next version is going to be v0.10.0 so I hope you package manager is okay with the downgrade.

**Comment by zetok** [comment]
cc @abbat
