### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [uTox/uTox#502]
As we all know, today more than ever before, it is crucial to be able to trust our computing environments. One of the main difficulties that package maintainers of Linux distributions face, is the difficulty to verify the authenticity and the integrity of the source code.

The Arch Linux team would appreciate it if you would provide us GPG signatures in order to verify easily and quickly of your source code releases.

**Overview of the required tasks:**
* [x] Please [create and/or use a 4096-bit RSA keypair](https://wiki.archlinux.org/index.php/GnuPG#Create_key_pair) for the file signing
* The key may be used for [email encryption](https://www.enigmail.net/index.php/en/) too
* Keep your key secret, use a strong unique passphrase for the key
* [x] Upload the public key to a key server
* [x] [Sign every new commit by default](https://help.github.com/articles/signing-commits-using-gpg/)
* [x] [Sign new tags](https://help.github.com/articles/signing-tags-using-gpg/)
* Verify the Github Release tarball download against your local source
* [x] [Sign Github Release tarballs](https://wiki.debian.org/Creating%20signed%20GitHub%20releases)

**Additional Information: **
* https://help.github.com/categories/gpg/
* https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
* https://www.qubes-os.org/doc/verifying-signatures/
* https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

Thanks.

**Comment by GrayHatter** [comment]
Hard No

**Comment by GrayHatter** [comment]
Here's what I will do. I will sign every tag. NO EXCEPTIONS. (I'm a human, and make mistakes. If I do, you should tell me and I'll correct it. Assume that I didn't make a mistake and don't trust anything unsigned.)

I do usually sign commits be default, even though this is not required (IMO).

The HEAD of master WILL ALWAYS be signed.

I can start signing and releasing tarballs too if you'd like.

@NicoHood is this acceptable?

**Comment by GrayHatter** [comment]
Assuming I'm not a total idiot. I published my key to `pgp.mit.edu` if you need something larger than 2048 Let me know

**Comment by NicoHood** [comment]
Thanks you taking the time.

A 4k key would be highly appreciated, as its obviously more secure and will last for a longer time.

Signing the tarballs is mostly the most important thing, as those are used for building the OS packages. However the rest of the software (git history) should also be signed. You may want to have a look at the gpg-agent to no need to retype your password every time.

**Comment by GrayHatter** [comment]
@NicoHood the Arch wiki you linked to disagrees with being obviously more secure. How about a nice ECC key instead?

**Comment by GrayHatter** [comment]
@NicoHood I went through and checked all the boxes. I assume there's nothing else I'm missing?

**Comment by Beast141** [comment]
Hi yes agreed about signing all packages and with 4096 key.

**Comment by NicoHood** [comment]
You check the last checkbox, but have you also uploaded the signature anywhere?
https://github.com/uTox/uTox/releases

**Comment by GrayHatter** [comment]
@NicoHood I marked that as will do. The next release should be ready in the hours to day or two range.

I can sign one now, but it's months out of date, and the next is very near release.

**Comment by NicoHood** [comment]
Hi, please also sign the release.
I've also written a script to automate the process for github. Still WIP, but fully functional.
https://github.com/NicoHood/NicoHood.github.io/wiki/Github-GPG-signed-release-script
