### ISSUE TITLE
Sending files or photos stops in the middle of transference or 'file transfer broken' Error

### ISSUE THREAD

**Issue by 2SI3NX** [uTox/uTox#509]
Very seldom will i receive an image from another user who is using Antox that the transference will complete successfully without problems.
Often its slow in downloading the photo/file and other times i get a red error when suddenly it says 'file transfer broken' in red.
I am running latest uTox with Tor.
Ubuntu 16.04

Howcome it takes so long to receive a photo/file? and why stops in middle of receiving?

Some users are getting annoyed and i tell them just be patient, this will be fixed.

**Comment by GrayHatter** [comment]
are you on the development version of uTox?

**Comment by Beast141** [comment]
I dont think its dev version. I downloaded from fdroid repo.

**Comment by GrayHatter** [comment]
we have an fdroid repo???

**Comment by Beast141** [comment]
shit im sorry, ive become very confused with all these tox clients. I meant to say i use tox ppa.
echo "deb https://pkg.tox.chat/debian stable $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/tox.list

**Comment by GrayHatter** [comment]
I'm 95% sure this is an Antox issue. I've had more than a few reports of Antox clobbering file transfers. Also could be due to Tor. Either way, I'll need you to confirm it happens between uTox -> uTox (Over Tor, or without Tor it shouldn't matter) before I'll be able to look into this.

**Comment by Beast141** [comment]
Ive had this same issue happen to me from Antox to another Antox user. but i figured now, it could be the servers it connects to, uTox or Antox. is there a difference in the servers they each connect to?  Or do you think theres a bug in Antox?
Ive used Antox without tor to another Antox user and i still have files that fail when receiving.

Im still going to check uTox from one pc to another and see if there are failures.

**Comment by GrayHatter** [comment]
the reason I think it's antox, is that through tor, you can expect connections to break... uTox how ever will resume them correctly... Antox does not :(

**Comment by robinlinden** [comment]
@Beast141 Any update on this? Had time to test uTox -> uTox file transfers via Tor?

**Comment by Beast141** [comment]
@robinlinden not as yet, i will make some tests within this week.

**Comment by Beast141** [comment]
Ok i have tested uTox -> uTox file transfers via Tor between 2 different ubuntu 16.04 pc's. With UDP disabled on both uTox's.

Test results:
1. Sending one file at a time from either side works and doesnt drop any connections.  However it transfers slowly sometimes. for example a 6mb photo took like around 3 to 4 minutes. Sometimes more.

2. Sending and receiving 2 different files/photos at the same time on both ends, takes much longer, and always the second file transfer would fail with 'broken file transfer error', But have seen that it restarts again underneath on a new line or carries on with the transfer, then it eventually finishes.

- I like the fact that it carries on with the transfer after the file transfer error occurs. But if it does carry on, then it must stay on the same line and just continue from where it started. can you make it do that rather?

- Also, i noticed - that when i am sending a file and it eventually finishes, i see that i have the option to click on it from the uTox client i sent from, which is good, but it must ALSO say 'file sent' just for clarification.   Anyone agree?

The question is, why does it break the 2nd file transfer when there is more than one file being transfered?
Why does the file transfer take so long to finish? with a simple 6mb file?

And i have noticed the error 'file transfer broken' mostly happens from or to Antox and uTox whether its 1 file or 2 at the same time. 
The file transfer on Antox seems to at some point get 'overloaded' and then my Antox client gets disconnected completely, which causes the transfer to break.

**Comment by GrayHatter** [comment]
@Beast141 what uTox version are you using? v0.11 was just released about 48h ago.

**Comment by Beast141** [comment]
well im using the ubuntu ppa
echo "deb https://pkg.tox.chat/debian stable $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/tox.list
wget -qO - https://pkg.tox.chat/debian/pkg.gpg.key | sudo apt-key add -

it still shows v 0.9.7 , i dont understand why it never updated?

**Comment by GrayHatter** [comment]
@Encrypt is working on those packages, there's a recent change in how uTox is built, so the previous build scripts we were using now need to be updated as well.

**Comment by Beast141** [comment]
oh ok so when will those packages be updated?

**Comment by GrayHatter** [comment]
if @Encrypt can't do it with in the next day or two, I'll let you know what my eta will be.

**Comment by 2SI3NX** [comment]
@GrayHatter whats your eta? ppa was not updated

**Comment by Encrypt** [comment]
Actually, the packages have been fixed but only for the nightly builds (for the moment), @2SI3NX.
@GrayHatter / @robinlinden will have to merge develop into ``master`` for the "stable" packages to be built again.

What is stopping the packages from being built right now on the ``master`` branch is an erroneous cmake configuration, which has recently been fixed in ``develop``.

**Comment by robinlinden** [comment]
This has been fixed for a few months now.
