### ISSUE TITLE
Utox it's not autoupdating ?

### ISSUE THREAD

**Issue by DjDiabolik** [uTox/uTox#520]
I use utox on windows 10 home... i have the 0.9.7 alpha and apparently there's a 0.9.8.... utox it's not autoupdate ? On Option there's no option to checks updates or somethings similar.....

**Comment by DjDiabolik** [comment]
I have download from site... when execute i obtain this:
detected 64bit system
addrinfo 0 2 0 0 16
Trying this one
Download size: 75
signed 1480214363, now 1481038565
expired signature (824202)
data is NULL
addrinfo 0 2 0 0 16
Trying this one
Download size: 75
signed 1480214363, now 1481038565
expired signature (824202)
data is NULL
addrinfo 0 2 0 0 16
Trying this one
Download size: 75
signed 1480214363, now 1481038565
expired signature (824202)
data is NULL
addrinfo 0 2 0 0 16
Trying this one
Download size: 75
signed 1480214363, now 1481038565
expired signature (824202)
data is NULL
addrinfo 0 2 0 0 16
Trying this one
Download size: 75
signed 1480214363, now 1481038566
expired signature (824203)
data is NULL
addrinfo 0 2 0 0 16
Trying this one
Download size: 75
signed 1480214363, now 1481038566
expired signature (824203)
data is NULL
version download failed

**Comment by DjDiabolik** [comment]
I have used now the uninstaller.bat.... and now i can't reinstall......

**Comment by robinlinden** [comment]
While we look into this, you can download uTox from here: https://tox.chat/download.html

**Comment by DjDiabolik** [comment]
Yeah.. i have used that...  now it's portable ?

**Comment by robinlinden** [comment]
No. If you want to make it portable you can run it with ` -p`.

**Comment by DjDiabolik** [comment]
mmmmmmmm... and how it's saved all info ? How it's saved the profile ? 
It's here:
C:\Users\MyUsername\AppData\Roaming\Tox

If yes apparently i have lost my old profile......

**Comment by robinlinden** [comment]
Yeah, your profile if you're not running it with `-p` should be stored in `%APPDATA%\tox`. If you're running uTox in portable mode, it should create a new folder where you're running it from. Switching to a newer uTox version shouldn't touch your profile.. 

If you want to drop into the utox channel on [Freenode](https://webchat.freenode.net/) I can help you have a look at what's going on. :)

**Comment by GrayHatter** [comment]
I'm gonna echo @robinlinden on this one. It's very unlikely that your profile is really gone. If you can join us on IRC http://webchat.freenode.net/?channels=#utox we should be able to help you find your uTox profile (assuming you didn't manually delete it, it's still likely somewhere)

**Comment by GrayHatter** [comment]
Meanwhile @irungentoo I saw that you pushed a new uTox version <1h ago, does that close this issue out?

**Comment by GrayHatter** [comment]
per irc `<irungentoo> should be fixed`

Please reopen this if you still can get the updater to work correctly.

**Comment by DjDiabolik** [comment]
Oh boys... it's not a big problems because i have recreated a new profile this times protected whit a password but this time i have used qtox..........

Otherwise in this newest profile i have already readd all my friends...... i have conserved all id in text files some months ago :)
