### ISSUE TITLE
compiler error on (Arch)linux

### ISSUE THREAD

**Issue by oberon2007** [uTox/uTox#525]
Build fails for me with these errors:
```
 too few arguments to function ‘tox_callback_file_recv’
     tox_callback_file_recv(tox, incoming_file_callback_request);
too few arguments to function ‘tox_callback_file_recv_control’
     tox_callback_file_recv_control(tox, file_transfer_callback_control);
too few arguments to function ‘tox_callback_file_recv_chunk’
     tox_callback_file_recv_chunk(tox, incoming_file_callback_chunk);
too few arguments to function ‘tox_callback_file_chunk_request’
     tox_callback_file_chunk_request(tox, outgoing_file_callback_chunk);
```
using and **cmake3.6.3** and **gcc 6.2.1**

**Comment by robinlinden** [comment]
Using TokTok/c-toxcore?

**Comment by oberon2007** [comment]
no. should I?

**Comment by robinlinden** [comment]
Yeah. uTox builds against [TokTok/c-toxcore](https://github.com/TokTok/c-toxcore) as irungentoo, the person maintaining [irungentoo/toxcore](https://github.com/irungentoo/toxcore/), hasn't had time to work on it lately and development continues in the non-hostile fork [TokTok/c-toxcore](https://github.com/TokTok/c-toxcore).

For links and more instructions you can look [here](https://github.com/uTox/uTox/blob/develop/docs/BUILD.md#xlib) or drop into [#utox on Freenode](http://webchat.freenode.net/?channels=#utox) where there usually are developers that can help you out if you need any help with uTox.

**Comment by oberon2007** [comment]
OK. Thank you!

**Comment by GrayHatter** [comment]
`in the new-upstream fork TokTok/c-toxcore.`

FTFY
