### ISSUE TITLE
GUI freeze when I try to change network settings 0.9.7

### ISSUE THREAD

**Issue by ghost** [uTox/uTox#544]
1. extract utox_windows_x86-64.zip
2. open utox.exe
3. GO to network tab, click IPv6's green square, next UDP, next Proxy's "disable" box, and click IPv6.
4. GUI freeze! (tested twice, happened twice)

**Comment by endoffile78** [comment]
Can you try the latest version of uTox and if see if it is fixed.

**Comment by GitHubHatesTor** [comment]
@endoffile78 Are you kidding me? I've downloaded https://build.tox.chat/view/uTox/job/uTox_build_windows_x86-64_release/lastSuccessfulBuild/artifact/utox_windows_x86-64.zip
just NOW and when I opened it, it shows 'Alpha version 0.9.7' to the window title.

**Comment by robinlinden** [comment]
Sorry about that. We just finished up 0.11.0 the other day, and there's a problem with the build servers so the downloads haven't updated. We're currently working on fixing it.

**Comment by robinlinden** [comment]
@GitHubHatesTor I compiled it for Windows just now and gave it a try and I can't recreate the freeze on the latest version, so it appears that we've fixed it. :)

**Comment by cebe** [comment]
sounds related to https://github.com/uTox/uTox/issues/54

**Comment by GrayHatter** [comment]
@cebe I'm 90% sure it's a treading issue between the gui, and the toxcore thread. Toxcore needs to be restarted, but somewhere in there it's making a call that locks the whole thing up.

**Comment by cebe** [comment]
As far as I get from debugging this, it hangs waiting for `tox_thread_init`, which does not seem to happen here: https://github.com/uTox/uTox/blob/1835eae7a96a1335f781308b0afa730ab3647483/src/tox.c#L211-L213

**Comment by cebe** [comment]
There is another issue here: When toggling the proxy settings, UDP gets disabled. This however is not reflected in the UI so the toggle button gets inversed. Checked means UDP disabled instead of enabled and vise versa.
