### ISSUE TITLE
close to tray does not work on Gnome3

### ISSUE THREAD

**Issue by cebe** [uTox/uTox#55]
Running on Debian Jessie with Gnome3. Selecting the "close to tray" option and closing uTox make it disappear. There is no icon showing up in the notification bar.

may be related to #16, not sure though.
##

**Comment by Doom032** [comment]
I don't see the tray icon at all in Xubuntu 14.04. Same experience as you with selecting "close to tray" and then closing µTox.

Debug log says
```
Close To Tray.   :: 1
Closing to tray.
```

And µTox stays running, but there's no tray icon to click to get µTox back!

**Comment by GrayHatter** [comment]
getting uTox to tray correctly is problematic... there's an issue somewhere that makes me think uTox tries to show the window before it's window actually get's INTO the tray, so it never get's it's draw/expose event... IIRC there's a way to expose on the notice that it was tray'd correctly.

**Comment by GrayHatter** [comment]
is it working now? 

pushed to https://github.com/uTox/uTox/tree/tray_fixes branch

**Comment by GrayHatter** [comment]
I think this is fixed in develop if not master
