### ISSUE TITLE
Build uTox with muslc

### ISSUE THREAD

**Issue by x368** [uTox/uTox#555]
Tested 0.11.0 and devel as of 2016 December the 19th, linked against musl libc (a highly conforming libc implementation)

The symptoms with chat logging enabled:
after restart of the program the chat window will be most probably empty
or otherwise there will be a bit of truncated and corrupted contents.
Diagnostics output says something like

Can't malloc that much, you'll probably have to move or delete your history for this peer.
                Friend number [...] count 4, actual_count 2, start at 0, error size [largedecimalnumber~10^10].

As a guess, can this depend on (an excerpt from opengroup.org documentation) "the application shall ensure that output is not directly followed by input without an intervening call to fflush() or to a file positioning function ( fseek(), fsetpos(), or rewind()), and input is not directly followed by output without an intervening call to a file positioning function, unless the input operation encounters end-of-file."?

The outcome otherwise is undefined and dependent on the details of stdio implementation.

**Comment by x368** [comment]
Another detail, packing/unpacking of the chat data is done using a raw C structure and its size, which will vary between different compilers and architectures.

src/messages.c:

            memcpy(data, &header, sizeof(header));
            memcpy(data + sizeof(header), author, author_length);
            ...
            msg->disk_offset = utox_save_chatlog(f->id_str, data, length);

src/chatlog.c:

            fwrite(data, length, 1, fp);

**Comment by robinlinden** [comment]
Can you have a look at #566 and let me know if it did anything for you? I'm not affected by the issue, but now we should be (mostly) following the opengroup.org recommendations for not having it rely on a specific stdio-implementation.

**Comment by x368** [comment]
It was just my guess that files are being updated in-place by opening them read/write and using both reading and writing. I do not actually know whether/where this is the case. I saw stdio operations to be used via callbacks, which makes it harder to see how they are combined with other operations.

The need for fflush() or fseek(), fsetpos(), or rewind() between reading and writing is only necessary when both reading and writing are being done, which is only possible/relevant when the file is opened r/w (i.e. with "+" in the mode given to fopen() or its equivalent).
Doing fflush() right before fclose() is not necessary (it is done implicitly in fclose()). I guess many cases where you added flush are redundant, but possibly not in all of them.

OTOH the whole file handling via stdio should be analyzed, given that you did not have a clear picture of the semantics and limitations of the i/o functions. Make you really familiar with the corresponding man pages (I know, this is tedious and also the API is ancient and has many flaws), then you will be in the position to realize if/where you may have used the i/o in a wrong way.

Another and serious problem in the file handling design is using raw C structures instead of reliably serializing the data. The data _is_ shared between different program versions and builds, even in parallel due to the home directories being shared, even between machines of different architectures (!)
Because of those reasons I do not expect any fix short of rethought and rewrite to be sufficient.

Unfortunately I can not help with auditing the code more than I did as a very short glimpse. 

Thank you and others for your work on uTox! I appreciate it for being compact, light and convenient - but it has to be correct and reliable. An application which is supposed to deal with security has no other choice.

**Comment by robinlinden** [comment]
I made the change before reading up on the man-pages and ended up (the 2nd commit in the PR) removing a ton of fflushes that we had right before fcloses after studying the opengroup.org docs. Most of our IO appear to be correct even after reading up on it with the exception of the fairly common `fflush(file); fclose(file);`. 

I'm still looking into the problem with the file corruption when using musl libc, but it's not the easiest task since no one on the dev team is using it. 

We recently fixed a similar problem with writing raw C structures to disk in toxcore, so don't worry. We're aware and working on it. 

Thank you for letting us know about the problems with uTox in combination with musl libc!

**Comment by x368** [comment]
Nice. Thanks Robin.
As for musl, it is an extremely productive tool for finding bugs. I would suggest to always test with musl, both for building and running. Numerous bugs in numerous packages have been hidden by glibc (and uncovered thanks to musl, there is a list of such bugs on the web, of course incomplete), some of them very harmful.

**Comment by GrayHatter** [comment]
>but it has to be correct and reliable

FWIW this is my primary goal for uTox. Especially considering the reason @x368 gave.

That said with limited time/resources, it also needs to work.

> As for musl, it is an extremely productive tool for finding bugs.

It's my eventual goal to ship uTox using musl by default. There's just been other pressing issues that I've needed to take care of first.

For anyone interested. The way uTox is doing file I/O so shitty is because Windows... Windows users are by far the largest number of users, and occasionally uTox just WON'T save random files on windows. It's interesting that with musl, the same bugs are now popping up on linux as well. Which leads me to agree with @x368 that it's glibc that's causing the bugs, and there's an ACTUAL fix we can implement in uTox instead of the hacky fixes we're using now.

**Comment by x368** [comment]
See my comment to the commit above. Apparently there are some remaining bugs which the additional fflush() happened to hide for the moment. Only an incomplete, fundamentally broken C library implementation would need a fflush() before fclose().

I might guess that the application is assuming stdio functions to be thread-safe, which is not present in the standard and possibly is the reason for the weird behavior differences you observe on different platforms. Adding extra fflush()es can then easily influence the behavior but does not make the code correct.

**Comment by robinlinden** [comment]
All stdio functions not ending in `_unlocked` are thread safe. We haven't found the reason we have to `fflush(file); fclose(file);` on musl libc yet.

**Comment by x368** [comment]
Posix implies that the stdio functions are thread-safe but I do not think that the C standard says a word about threading (before C11). This can easily lead to a behaviour difference between Posix-ish and non-Posix platforms.

As for the "fflush(file); fclose(file);" sequence, it should never be necessary for any compliant C library.
Concerning Windows, Visual Studio 2015 manual says about fclose() (https://msdn.microsoft.com/en-us/library/fxfsw25t.aspx)

"all buffers associated with the stream are flushed prior to closing."

**Comment by GrayHatter** [comment]
@x368  the msdn article states that applies to `_fcloseall`, and doesn't specifically state, that it also applies to fclose as well. And because the issues the fclose seems to fix seemingly only come from windows. I'm leaning closer to the idea the broken implementation is actually windows.

**Comment by x368** [comment]
The whole paragraph, note the word "both":

"The _fcloseall function closes all open streams except stdin, stdout, stderr (and, in MS-DOS, _stdaux and _stdprn). It also closes and deletes any temporary files created by tmpfile. In both functions, all buffers associated with the stream are flushed prior to closing. System-allocated buffers are released when the stream is closed. Buffers assigned by the user with setbuf and setvbuf are not automatically released."

**Comment by x368** [comment]
If you are assuming that Windows standard C library is non-conforming or broken in its stdio implementation in such a basic aspect, please reconsider. A fault like this would quite probably break too many programs to be able to remain unnoticed.

**Comment by GrayHatter** [comment]
My mistake, missed that it applied to both. But it doesn't refute my previous comment, that the problem only crops up within windows. Or muslc.  

Either I'm not sure what the best solution is to this issue. Calling fflush fixes the bug. It's shouldn't be a threading issue, because the chatlog is only interacted with by messages.c, and that should be wrapped by a thread mutex. Then, again, fflush, and fclose are both thread safe in posix like (linux, muslc, windows.)

Finally, this issue was closed because we're building utox against muslc from alpine linux.

**Comment by GrayHatter** [comment]
>If you are assuming that Windows standard C library is non-conforming or broken in its stdio implementation in such a basic aspect, please reconsider. A fault like this would quite probably break too many programs to be able to remain unnoticed.

Agreed, but I can't find the bug in my code. I can't even duplicate the bug from Linux. So unless you can find the bug with in uTox. What do you think is more likely, windows is using a broken libc (the os that has a STRICT bug compatibility rule?) or linux is using a broken libc?

**Comment by x368** [comment]
(windows is not posix, even if it offers some level of compatibility)

Otherwise yes we are now offtopic if utox works correctly on musl, but it would be good to really fix the portability, not hide the symptom if it still affects windows.

I bet Windows follows its documentation regarding the semantics of fclose(). Musl is one of the cleanest C library implementations I have ever used so I do not feel tempted to analyse its stdio code because of this issue (yes this is a bold heuristics, but reasonably informed). Nothing negative against uTox, but it is still young and is a complex application, relying (possibly indirectly) on multiple libraries. Some of them can do thing which we do not anticipate and break some unnoticed assumptions in the application code.

Are you sure you do not assume posix in some place where posix deviates from the classical C standard?
