### ISSUE TITLE
UI glitch with password field

### ISSUE THREAD

**Issue by cebe** [uTox/uTox#570]
Steps to reproduce:

1. have your profile encrypted, close utox
2. start utox, you see something like: 
![bildschirmfoto von 2016-12-21 17 28 22](https://cloud.githubusercontent.com/assets/189796/21397199/29f53468-c7a3-11e6-9c66-39a195153630.png)
3. enter password and you see the Profile settings page.
4. Clicking on "Show" for the Profile password gives me this: 
![bildschirmfoto von 2016-12-21 17 28 38](https://cloud.githubusercontent.com/assets/189796/21397233/4341c7ec-c7a3-11e6-907d-b3c92a937999.png)
The position of the password field is wrong.

**Comment by GrayHatter** [comment]
fixed in #627

**Comment by cebe** [comment]
yes, fixed.
