### ISSUE TITLE
Create additional debug levels

### ISSUE THREAD

**Issue by GrayHatter** [uTox/uTox#572]
current 
```
debug
debug_info
debug_notice
debug_error
```

suggested
```
log_trace
log_debug
log_info
log_notice
log_warning
log_error
log_fatal // also accepts an int, and exits with that int
```

**Comment by cebe** [comment]
not sure about the difference between info/notice  and debug/trace which each could be merged to one. but looks good to me in general.

**Comment by GrayHatter** [comment]
I've needed trace before, EG for something that SPAMS the output with information, like mouse xy positions. Very helpful to debug that ONE issue, but otherwise it'll just make it impossible to read anything else.
