### ISSUE TITLE
Wrong text when hovering on buttons

### ISSUE THREAD

**Issue by fcore117** [uTox/uTox#576]
Picture tells everything, just hover cursor on those buttons. Just a cosmetic bug nothing more.
![cosmetic2](https://cloud.githubusercontent.com/assets/1313813/21452149/826fa694-c90d-11e6-9499-8c74959234eb.png)
![cosmetic1](https://cloud.githubusercontent.com/assets/1313813/21452150/82739916-c90d-11e6-9f30-c5cdd2590fdf.png)

**Comment by cebe** [comment]
it is not cosmetic, the switch positions are wrong :)

**Comment by fcore117** [comment]
i have not used those thats why i thinked it is cosmetic, my bad.

**Comment by GrayHatter** [comment]
fixed in develop or in #627
