### ISSUE TITLE
Maximum distance for switches

### ISSUE THREAD

**Issue by cebe** [uTox/uTox#580]
I think we need a maximum distance for switches from the text, otherwise it is hard to find the switch belonging to a label. E.g. "Push to talk":

![bildschirmfoto von 2016-12-24 01 34 05](https://cloud.githubusercontent.com/assets/189796/21464299/333a34a6-c979-11e6-9dc3-ae0f1db85b44.png)

I can fix this, but I would wait for #550 to be merged into develop.

**Comment by redmanmale** [comment]
This was fixed in #835.

**Comment by GrayHatter** [comment]
@redmanmale you should be able to close issues. If you're sure they're resolved, you should feel free do close them 😁

**Comment by redmanmale** [comment]
@GrayHatter 
Err no, I can only close issues that I opened.
