### ISSUE TITLE
time display is missing the last digit

### ISSUE THREAD

**Issue by cebe** [uTox/uTox#581]
![bildschirmfoto von 2016-12-24 04 12 28](https://cloud.githubusercontent.com/assets/189796/21464995/68a4a11a-c98f-11e6-8954-c0230fcb55d3.png)

**Comment by GrayHatter** [comment]
It's being covered by the scroll bar which isn't present. 

Either way, you're supposed to be able to double click the time to display, or hide seconds. Which you're unable to do :(

**Comment by GrayHatter** [comment]
should be fixed in #627

**Comment by cebe** [comment]
it's fine without seconds but not with seconds:

![bildschirmfoto von 2017-01-20 22 49 10](https://cloud.githubusercontent.com/assets/189796/22166719/c3712382-df62-11e6-9909-dc1512cfe8ef.png)
![bildschirmfoto von 2017-01-20 22 49 29](https://cloud.githubusercontent.com/assets/189796/22166720/c376d55c-df62-11e6-8db2-81a3df590990.png)
