### ISSUE TITLE
Could not paste non-ASCII characters into chat

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#583]
How to reproduce: copy any text (with any non-ASCII characters, for example `ça a été une longue journée`) and paste it into uTox chat window.
All non-ASCII characters will not show up.

Win 7, 8.1 x64, uTox v.0.11.1;

tags: unicode support

P.S. Thanks for fixing utox_runner!

**Comment by cebe** [comment]
Same on Debian Linux using Gnome3. Seems copy/paste does not support non-ascii characters.

**Comment by GrayHatter** [comment]
Run it  with `-vvvvv` and paste the XLIB support lines there should be a list of paste types, I think we're just selecting the wrong one

**Comment by cebe** [comment]
```
SelectionNotify
Type: ATOM
Property: ATOM
Supported type: TIMESTAMP
Supported type: TARGETS
Supported type: MULTIPLE
Supported type: SAVE_TARGETS
Supported type: text/html
Supported type: text/_moz_htmlcontext
Supported type: text/_moz_htmlinfo
Supported type: UTF8_STRING
Supported type: COMPOUND_TEXT
Supported type: TEXT
Supported type: STRING
Supported type: text/x-moz-url-priv
SelectionNotify
Type: UTF8_STRING
Property: TARGETS
```

**Comment by GrayHatter** [comment]
damn, there's nothing obviously wrong there...

**Comment by grinapo** [comment]
But nothing happens. Or rather if I have a buffer of "ⱫaⱮeⱴ" the result of paste is "ae".
Everything above 0x7f is gone.
this is debian/sid x64, pretty latest version.

```
/tmp/buildd/utox-0.12.2/src/xlib/event.c: SelectionNotify
/tmp/buildd/utox-0.12.2/src/xlib/event.c: Type: UTF8_STRING
/tmp/buildd/utox-0.12.2/src/xlib/event.c: Property: TARGETS
```

**Comment by robinlinden** [comment]
Can replicate on Windows 10, but it seems that utf8 has more problems. Even typing it does weird things. 
E.g.:
1. Paste `ça a été une longue journée`
2. Ctrl+a -> delete
3. Type `æ`.
The text you just deleted is now back. 

Typing `æ` always deletes the last character you entered. 
Typing `Á` deletes all text in the text entry box.

**Comment by cebe** [comment]
That seems to be specific to windows, typing russian characters works fine on debian.

**Comment by redmanmale** [comment]
Could not reproduce this behavior (with æ) on Win 8.1.
