### ISSUE TITLE
Add checkums to releases.

### ISSUE THREAD

**Issue by bltnkl** [uTox/uTox#588]
Hi. Could you please add checksums to your releases? Thanks.

**Comment by GrayHatter** [comment]
All releases should be pgp signed, this is a cryptographically secure checksum.

Did you have a different one in mind?

**Comment by bltnkl** [comment]
Could you please post a link? I didn't find, thanks.

**Comment by endoffile78** [comment]
Heres all of our releases: https://github.com/uTox/uTox/releases. In the download sections there are the signatutes. I also have added checksums to the latest releases.

**Comment by GrayHatter** [comment]
done and done! thanks @endoffile78 

@bltnkl reopen this if we missed something

**Comment by bltnkl** [comment]
And what about checksums for downloads(Linux) on links that are posted on main page?
It offers just a link, no mention of checksum
https://github.com/uTox/uTox/releases - there're now separate Linux releases with checksums too.

**Comment by GrayHatter** [comment]
If you can replace a file, you can replace a checksum. You're not going to get better security than HTTPS, which everything from utox.io should already be.

If you'd like I can start signing the binaries as well. But again, if you can replace download via https with your own, you can also replace the key signature as well.
