### ISSUE TITLE
Drag and drop for files do not work, 0.11.1

### ISSUE THREAD

**Issue by fcore117** [uTox/uTox#600]
Windows x64

If any more info is needed let me know.

**Comment by fcore117** [comment]
Just now tested on both Win 8 and Win 10, same.

**Comment by cebe** [comment]
On Debian Linux: Drag and Drop in the friendlist works for sorting, however dragging friends into groups does not.

**Comment by fcore117** [comment]
Sorry i forgot to add that drag n drop files
