### ISSUE TITLE
filetransfer rejected if illegal characters in filename on windows

### ISSUE THREAD

**Issue by zoff99** [uTox/uTox#611]
if i send a file to uTox on windows, with filename "blabla:blabla.txt" uTox will automatically reject the file when autoaccept is on.
convert all illegal chars to "_" and allow saving of such files

**Comment by GrayHatter** [comment]
anyone who plans to fix this https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

**Comment by redmanmale** [comment]
Fixed in #919.
