### ISSUE TITLE
Close to tray option setting will not be remembered.

### ISSUE THREAD

**Issue by MartinX3** [uTox/uTox#614]
Linux mint 18.1 x64 Mate Edition.
I'm using the PPA.

I enable the option, i close uTox. (No minimize to tray, it's really closed).
Next time, i start uTox, the option is disabled again.

PS:
The close to tray option itself worked for me, but this bug occur #612 !

**Comment by GrayHatter** [comment]
I can't duplicate this, is it still happening?

**Comment by MartinX3** [comment]
Sorry, I can't test it.
I removed my tox account, because no one I know use it :(
