### ISSUE TITLE
filetransfer resume has UI errors

### ISSUE THREAD

**Issue by zoff99** [uTox/uTox#620]
start utox for windows v0.9.7 end receive a large file.
now in the middle of the FT totally shutdown utox.
now restart utox.
if the sender supports resuming utox will resume the FT but the UI will show size=0 bytes
and arival time does not work also.

but it seems the FT finishes ok though.

**Comment by endoffile78** [comment]
uTox v0.9.7 is not the latest version can you try with version 0.11.1. Go to http://utox.org and click on download uTox for windows, this should donwload utox_runner which will then install the latest version of utox.

**Comment by GrayHatter** [comment]
Nah, we talked on IRC, he's looking for auto resume, that's not working in uTox in v0.11

**Comment by GrayHatter** [comment]
It's fixed in #627
