### ISSUE TITLE
uTox is prevented from starting on windows with some McAffee thingy installed

### ISSUE THREAD

**Issue by zoff99** [uTox/uTox#621]
uTox for windows is scanned before starting and the user is prevented from running the app.
something in the binary triggers it.
strange because qTox works.

i try to make a screenshot if i can ...

**Comment by GrayHatter** [comment]
Probably because McAfee is broken.

wont fix

**Comment by zoff99** [comment]
qtox is working. i wonder if its just a static String that triggers it?

**Comment by cebe** [comment]
Could be, we don't know. If you can provide more info and the fix does not have any drawbacks, we might fix it. Otherwise, report it as false positive to McAffee. Its clearly their fault.

**Comment by GrayHatter** [comment]
My guess, is that uTox starts up, and connects to the network. Where qTox has to do a LOT of other shit inbetween. qTox Looks a lot more like a huge app, that spends a lot of extra cycles for [reasons], uTox being light weight makes it look more like a virus; it only has to do the one thing.
