### ISSUE TITLE
Can't connect from restricted network (port 443)

### ISSUE THREAD

**Issue by palikacska** [uTox/uTox#625]
I use Tox in a restricted network environment. This means that the only way out from the network is through TCP port 443. No other port is allowed for outbound connections. Tox seems to have at least two [bootstrap nodes](https://wiki.tox.chat/users/nodes) (46.101.197.175, 185.14.30.213) that accept connections on port 443 but I don't know how to make uTox explicitly use them.

I tried to leave Tox for an hour to make it try all existing bootstrap nodes. No success. I also tried setting up iptables to REJECT all outbound connections where destination port is not 443. This would result in a **refused** connection instead of a **timeout**, so it would get to the node with port 443 faster, while trying to access inaccessible non-443 nodes one after the other.

I tried to connect to the nodes mentioned above with telnet and it was successful. So the mentioned 443 nodes are available from my restricted network.

How could I make uTox to forcibly use the nodes that accept connections on port 443? If I could specify the IP addresses, that would be great.

If there is no such option, could you please implement it? A command line option would do.

**Comment by cebe** [comment]
This would be something for the "advanced settings tab".

**Comment by GrayHatter** [comment]
This is nearly the same issue https://github.com/TokTok/c-toxcore/issues/283

Give this as shot, and let me know if it works. I'll consider adding support for this into uTox.

**Comment by palikacska** [comment]
It would be really nice if one of the following could get into the next subversion.

- A simple **Prefer port 443 for bootstrap** checkbox into Settings -> Network that would put the 443 nodes first when connecting.
- A command line option that would tell uTox which custom bootstrap nodes to use. For example... `  -b --bootstrap=<ip:port,...>      Use specified bootstrap nodes to connect to the Tox network.\n");`

I think this is valid for a lot of users using workplace network or public Wi-Fis.

**Comment by fcore117** [comment]
palikacska: do you have windows machine to test? i could try to make binary with 443 nodes.

**Comment by palikacska** [comment]
I managed to build uTox on a Debian Jessie system with 443 hardcoded nodes as mentioned at [TokTok/c-toxcore#283](https://github.com/TokTok/c-toxcore/issues/283).

I used to have version 0.9.7 using the repository for Jessie, so I thought I would base my modification in file `tox_bootstrap.h` on this version. I did a `git checkout v0.9.7`, installed all *-dev package dependencies - which you could have included in **BUILD.md**, it gave me a hard time to track them all down - then compiled uTox from source. It created me a binary with hardcoded 443 bootstrap nodes.

It worked.

It connected to a bootstrap node from the restricted network. Then I started the old uTox, the one that had been installed onto my Debian Jessie (via apt-get). It worked as well. Weird. It never worked before starting my own build. It seems uTox saves the IP address of working bootstrap nodes to its config. Btw. I could not view the config, because it's in binary format. Another reason why I don't really understand why this configuration option for preferring 443 bootstrap nodes hasn't been added yet.

**Comment by fcore117** [comment]
palikacska: very good test that you made and now can use on limited firewalled network. 

Port 80 nodes would be useful addon for future to bypass firewalls even better like Skype did.

**Comment by robinlinden** [comment]
We've updated the list of bootstrap nodes that uTox uses and placed a few 443 nodes at the top of the list, so this should be fixed as of the merging of https://gitlab.com/uTox/uTox/merge_requests/787/.

Feel free to give it a go if you're able to compile uTox yourself. Otherwise you'll have this fix in 0.14.0 which is due in 9 days now.

**Comment by palikacska** [comment]
Great job. Thank you.
