### ISSUE TITLE
alignment of buttons in advanced settings should be language depentent

### ISSUE THREAD

**Issue by cebe** [uTox/uTox#639]
otherwise they will overlap in some languages:

![bildschirmfoto von 2017-01-22 14 04 53](https://cloud.githubusercontent.com/assets/189796/22182689/f01b1e66-e0ab-11e6-8aa4-7fe4f15b8489.png)

**Comment by GrayHatter** [comment]
...I KNEW I was going to regret putting them on the same line.

We need a macro that'll get the width of buttons

**Comment by redmanmale** [comment]
Exactly this issue was fixed in #835 (right buttons were moved further to the right so they are no longer overlap each other), but we still need (in general) this macro to make things looks pretty.
