### ISSUE TITLE
Updater must update

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#641]
It's not the first time when new release comes up, but updater does not update uTox (0.11.1). 
Or am I jumping the gun?

Win x64.

**Comment by GrayHatter** [comment]
@redmanmale windows auto update is usually lagged out a few weeks intentionally. Just to give us, and testers a few extra days to catch any serious bugs.

I'm planning to start releasing a development version to the updater, that'll update to development versions. But not until I make sure the new updater code is working flawlessly.

**Comment by redmanmale** [comment]
OK, I got it.

**Comment by GrayHatter** [comment]
@irungentoo was supposed to push v0.12 today, but something came up.
