### ISSUE TITLE
Publish GPG key

### ISSUE THREAD

**Issue by NicoHood** [uTox/uTox#653]
The gpg keys for the release signatures are not published in the readme. Please add those with the *full** fingerprints + name and email. Or with a simple link to the keyserver.

Also please give the signatures normal names, without the signer if possible. Since all of them are trust, it should not matter who created the signature (as it can be read by gpg anyways). And we cannot validate more than one signature.

Feel free to simplify the release via [gpgit](https://github.com/NicoHood/gpgit)

**Comment by robinlinden** [comment]
This was done in https://gitlab.com/uTox/uTox/merge_requests/821

**Comment by NicoHood** [comment]
I need to sign in to view this link.

**Comment by robinlinden** [comment]
Sorry. Grayhatter hid the GitLab repo, so all links to it are dead now.
Here's the commit on GitHub: https://github.com/uTox/uTox/commit/527ee221

**Comment by NicoHood** [comment]
And what about grayhatters old gpg key? 4C4E8E7E23A85F2474DC2F1A0558CBEA7BE857DD
Why do you guys all generate new keys?
