### ISSUE TITLE
File transfers sometimes miss updates

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#655]
New version crashed after several minutes without any warnings.
There were no unusual actions, just some chatting.

Crash log is [there](https://gist.github.com/redmanmale/974d6a72ff36266178dcc8169d1b13d8).

I'll try to reproduce it and tell if I get any concrete steps.

Win 8.1 x64, uTox 0.12.1.

**Comment by GrayHatter** [comment]
@redmanmale that's for the report, there were some issues with filetransfers in v0.12.0, but all of them should have been fixed. in v0.12.1 If you're willing to do some debugging, see if you can't get a friend to change their avatar, then send an inline image back and forth, then a regular file back and forth.

If uTox doesn't crash, try adding random disconnects.

If you STILL can't make it crash when you want it to. But it does crash again randomly, let me know and I'll get you a debugging build.

**Comment by redmanmale** [comment]
I've made some experimenting and that's what I've got. Maybe we should separate it into several issues.

I have two uTox v.0.12.1 (one x64, one x86) and Windows (one x64, one x86) on the both sides respectively.

1. Chatting without any problem.

2. If I select file via button **nothing happens**; file doesn't show up in the chat window, nothing.

3. If I drag'n'drop file it shows up in the chat window also the other side gets notification and if I accept file uTox creates empty file in selected folder, but **transferring doesn't start**.
It just hangs until I cancel transfer **OR** after accepting the file uTox crashes (**only on x64 side**).
I tried with or without avatars, different files and could find any pattern. Sometimes it crashed, sometimes not. But transferring always doesn't work. Only uTox x64 on Windows x64 crashes, on the other side x86 on x86 has never crashed.

4. Avatar could not be removed. If I remove avatar and close uTox after start it set up again.
5. Another crash situation. And here are some concrete steps (it still can be tricky, sorry about this): 
* open uTox on one side (1)
* type couple of messages to friend (2) who is offline
* open uTox on the other side (2)
* keep typing messages from (1) to this friend (2) until he goes online
* in moment he (2) goes online uTox (1) hangs forever.

**Comment by redmanmale** [comment]
Another crash. It seems unrelated with previous.
No file transferring, even no chatting. Just standby for a couple of hours.

[Crashlog](https://gist.github.com/redmanmale/83459694103febfcf5d428033f12e9e6)

**Comment by redmanmale** [comment]
Also crashed after ~1 hour on Win 8.1
No filetransfers, no chatting.

**Comment by robinlinden** [comment]
We would appreciate it if you could help us out just a bit more by getting us a debug log from uTox.

Open a command prompt: 
WIN+R `cmd` ENTER
Navigate to the uTox folder: 
`cd %appdata%\utox` ENTER
Run uTox with the maximum debug level and pipe it to a log file: 
`uTox.exe -vvvvvv > utox_debug.txt` ENTER

Just handing us the bit before a crash should be enough to help us narrow down where it happens.

**Please be aware that this log will contain Tox IDs and public keys and other things that you might want to censor before posting it somewhere.**

**Comment by ElLamparto** [comment]
v0.12.1: Me too had a crash on Win7, 32bit while doing nothing. If it happens again, I'll run uTox to a log, as described by @robinlinden.

**Comment by redmanmale** [comment]
Here's the crash log, described in part 3. [Log](https://gist.github.com/redmanmale/6c9d31e24744f094bf8cf4ba12ca9045)
And here's uTox hangs log, described in part 5. [Log](https://gist.github.com/redmanmale/dd91c61e0dd2d5fc59402333f33747d0)

Only init part skipped, if it's important I could send uncensored version.

**Comment by GrayHatter** [comment]
I'm 90% sure I've found the issue

**Comment by GrayHatter** [comment]
https://downloads.utox.io/testing/

Let me know if these builds still crash or hang for you.

**Comment by redmanmale** [comment]
x64 crashes when I accept file before select folder.

**Comment by redmanmale** [comment]
One more thing: with this version after restart there's no history for today.

**Comment by GrayHatter** [comment]
files updated again, now on 2428b35f

**Comment by redmanmale** [comment]
Still the same.

**Comment by GrayHatter** [comment]
a lot of additional fixes have been added to the testing version at -> https://downloads.utox.io/testing/

Give it a try again please.

**Comment by redmanmale** [comment]
I checked this last version and that's what I've got (parts from [here](https://github.com/uTox/uTox/issues/655#issuecomment-274771413)).

### Fixed
* part 2. Send file via button works fine.
* part 3. Send file via drag'n'drop also works fine.

### Not fixed
* part 4. Avatar still could not be removed.
* part 5. uTox still hangs. [Log](https://gist.github.com/redmanmale/98f29b5e4f02151bd8ce3ef7dc36d9dd)

**Comment by redmanmale** [comment]
After file was received (transfer complete, I check the file) message about it still hangs and looks like in the middle of transferring (but it's not) and buttons cancel and pause are still active.
![pic](https://puu.sh/tCkZQ/b8f87ffbd4.png)

**Comment by GrayHatter** [comment]
Updated again https://downloads.utox.io/testing/

I'm going to make the avatar issues out of scope for this issue, and they'll need an additional issue

**Comment by redmanmale** [comment]
I'll check the transferring related part and write results down here and create new issue for the avatars bug.

**Comment by redmanmale** [comment]
So it's getting better, now not all transferring hangs, but only a half!

**Comment by GrayHatter** [comment]
When / where is it hanging?

**Comment by redmanmale** [comment]
All transfers complete.

One side:

![pic](https://puu.sh/tDPLi/88ab2678e6.png)

Other side:

![pic](https://puu.sh/tDPQI/273af3d198.png)

**Comment by GrayHatter** [comment]
@redmanmale are these files auto accepted?

**Comment by redmanmale** [comment]
No. All files accepted manually.

**Comment by GrayHatter** [comment]
And none of them are broken or failed right?

**Comment by redmanmale** [comment]
Yes. All transfers complete from the receiver side and all files are OK.
