### ISSUE TITLE
Chat window doesn't redraw when scrolling using pgup/pgdn

### ISSUE THREAD

**Issue by robinlinden** [uTox/uTox#661]
It scrolls, but doesn't redraw to show this. Hit pgup or pgdn a few times and then click in the chat window to see that it scrolled but didn't redraw.
Tested on Windows 10.

**Comment by redmanmale** [comment]
Also on Win 7.

**Comment by GrayHatter** [comment]
every time the user presses a key, or button, the UI should redraw (if we want to be lazy)

or

the messages panel should catch pgup pgdn and return true to signal  redraw needed (if you want to me smart)

**Comment by robinlinden** [comment]
Fixed in #707
