### ISSUE TITLE
Min window size limit

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#663]
uTox window's minimum size is limited depending on DPI and it's OK, but imo it limited too much, because now at my normal DPI 110% it consumes almost whole my screen, which is nearly unusable in non-fullscreen mode.

![tox](https://cloud.githubusercontent.com/assets/6782721/22263478/a67bd850-e285-11e6-8a22-7d0db55f2cf2.jpg)

I don't know this is bug or feature (or it's fix for #581), but it really frustrates me.

**Comment by robinlinden** [comment]
I didn't like the change either, so there you go. :) I use an even smaller minimum width locally, but I don't think cutting off parts of the Tox ID display box is a good idea for users who don't know about that.

**Comment by redmanmale** [comment]
We could replace several last symbols by "..." to show users that there is more?
And by clicking button "copy" or ctrl-c put **entire** value into buffer.

**Comment by robinlinden** [comment]
I agree with you on replacing the last few symbols if the window is too small. 
Using the copy button or double clicking on the Tox ID and pressing ctrl+c already copies the full thing. 
If we add in the ellipses thing I'd be fine with lowering the minimum width a bit more. (~50px or so more is still fine.)

**Comment by redmanmale** [comment]
Theoretically minimum width is something like that:
![tox-2](https://cloud.githubusercontent.com/assets/6782721/22265491/5568ba34-e28d-11e6-9b18-3ebc9f238a31.jpg)

Only without truncating info labels.

**Comment by GrayHatter** [comment]
#666
