### ISSUE TITLE
Not sure how to create a groupchat

### ISSUE THREAD

**Issue by fling-** [uTox/uTox#680]
Clicking on 'Create Groupchat' contact wipes chat window part.
Clicking on any other contact restores it back.
I discovered from https://github.com/uTox/uTox/issues/336 that I cound drag and drop something somewhere to create a groupchat. What exactly should I drag and where sould I drop it?

**Comment by GrayHatter** [comment]
Groupchats are in dire need of LTC. I stripped a good about of code waiting for new groupchats code. Before I knew that it was going to require a net_crypto rewrite.

**Comment by redmanmale** [comment]
@fling- 
You need to right click on 'Create Groupchat' contact.
![pic](https://puu.sh/tAJ5v/f88cbfc6f0.png)

After that you might be able to drag your other contact (online-only) onto that 'Groupchat' contact.
![pic](https://puu.sh/tAJIv/6f72e19f3d.png)

In groupchat you'll see
`YOUR_CONTACT <- has joined the chat! `
