### ISSUE TITLE
uTox doesn't save chat history even though the option is on

### ISSUE THREAD

**Issue by erejnion** [uTox/uTox#682]
Ever since I updated uTox to 0.12.1 it doesn't save chat history. Tried turning the option off and on again, but to no avail. The chat history up to the moment it updated from 0.11.1 to 0.12.1 shows on startup, but nothing since that moment. 
Files in the Roaming/Tox folders show Date Modified at 24.01.2017 too. If I try to export the chatlog, it either crashes (the save file in Roaming/Tox for this user is like 1MB, so eh), or it exports an empty file. 
If I remove the files from Roaming/Tox, it does create a new save file for the user, but it stays empty and again export chat log returns an empty file. 
Running uTox with administrator privileges doesn't change anything. 
Options save after closing uTox, it's just the chat history that doesn't. It just shows the chat history up to 24.01.2017. 

However, my brother doesn't have such problems, even though he's also on uTox 0.12.1. 
System is up-to-date Windows 7 Professional 64bit on a Thinkpad E560. My brother same, but E540. 

Also it seems uTox 0.12.1 can't accept file transfers, but can send such. That one is true for both me and my brother. There was a problem with the file transfers under 0.11.1 too, but I didn't bother testing too much.

**Comment by robinlinden** [comment]
I have this too, running the latest develop build on Windows 10 x86-64.

**Comment by redmanmale** [comment]
Me too, Win 7, 8.1 x64.
