### ISSUE TITLE
Segfault on network disconnect.

### ISSUE THREAD

**Issue by fling-** [uTox/uTox#684]
uTox 0.12.1 segfaulted when the box got disconnected from the network.
A single debug line was produced between the disconnect and segfault events:
```
uTox:   Disconnected from DHT!
```

**Comment by GrayHatter** [comment]
what debug level?

**Comment by fling-** [comment]
@GrayHatter ```-vvvvv```

**Comment by GrayHatter** [comment]
Can't Dx without more information.
