### ISSUE TITLE
Deleting messages functionality

### ISSUE THREAD

**Issue by Ygarr** [uTox/uTox#711]
ability to:
1. delete message including Recipient(Sender) and Receiver.
2. delete message by timer (Viber-like feature)

**Comment by GrayHatter** [comment]
@Ygarr are you asking for deleting only the local copy? Or are you asking to be able to delete the remote copy as well?

**Comment by GrayHatter** [comment]
stale NOS

**Comment by Ygarr** [comment]
Both separate abilities. First of all  delete remote copy: from local chat and recipient chat .

**Comment by redmanmale** [comment]
I think removing messages is a bad idea.
Just like you cannot 'unsend' a letter that have already sent.

**Comment by Ygarr** [comment]
Yes, may be because there is no servers to delete message from. With "Unsend" functionality the result would be the same. The sent message will disappear from receiver chat(and from sender)

**Comment by redmanmale** [comment]
I don't want other side could remove their message from **my history**, because it's my history on my device.

**Comment by Ygarr** [comment]
offtop: what NOS means?:
http://acronyms.thefreedictionary.com/NOS

Remove or not from history is obviously must be user-specified additional possibility.
It is not primary and  ASAP task issue, but also strictly regarding to security.

**Comment by GrayHatter** [comment]
NOS not otherwise specified

**Comment by GrayHatter** [comment]
But deleting messages from a remote device isn't a feature we can enforce, so it makes no sense to add it to begin with.

Not to mention, I agree with @redmanmale I don't want someone else deleting my messages

**Comment by Ygarr** [comment]
>other side could remove their message from my history
Seems behavior must be like "send/receive keyboard actions - typing indicator - to user"

**Comment by Ygarr** [comment]
Recall: the fact of removal usually remains with analogues, as a compromise;and your personal sent messages will disappear without a trace for you local but not for recevier.

**Comment by Ygarr** [comment]
Some thoughts about cases for this:

1 case : I removed message for ALL: 
	 a:  Receiver and ME(SEnder) see "Message deleted at {Time}"
	 b:  Receiver see {empty as before sending} ME(SEnder): "You can only delete message for you"

2 case : I removed message for Receiver:
        a: ME(Sender) see message(marked as "invisible for receiver") with ability to delete later for ME.
        b: message at Receiver disappears/erases from Receiver 's chat" {empty as before sending} 
        c: message at Receiver becomes as "Message deleted at {Time}"
        d: message at Receiver leaves as before with mark deleted by Sender "Message deleted at {Time}"(i.e.: message becomes c̶r̶o̶s̶s̶e̶d̶t̶h̶r̶o̶u̶g̶h̶ for Receiver)

3 case : I edited text. 
	subcase a: Receiver see edited text marked as edited
	subcase b: Receiver see edited text as initial/original
	subcase c: Receiver see original and edited text

4 case : I uncheckbox "Remove locally cancelled by ANY sender messages"
        subcase a: Receiver knows about this MY option
	subcase b: Receiver don't know about this MY option

5 case : I checkbox specified user to log all activity("all-seeing eye")(include deleting/editing message history) 
	subcase a: without user knowledge about it.
	subcase b: with user knowledge about it.

6 case : Offer to create with Receiver a mandatory non-logged chat

7 case : Offer to create with Receiver a logged(i.e. for Brainstorm) chat

8 case : I removed ANY(sender/or/receiver) message for ME local(sender): 
	ME(Sender) see {empty as before sending}. Receiver see usual message.

**Comment by Ygarr** [comment]
By the way, you need to make an amendment 
that you or you opponent can use third-part technical tools to log mandatory all deleted messages in any secured messengers. This is meant by default.
