### ISSUE TITLE
Avatars not loading since 0.11.x

### ISSUE THREAD

**Issue by flussence** [uTox/uTox#713]
`fread(3)` returns the number of chunks read, not bytes. Before 28e3b5d58302f the check here always succeeded by accident (so the error branch never would have been taken) but afterwards it always fails (and the error message got misplaced too).

Here's a patch to fix both.

```diff --git a/src/avatar.c b/src/avatar.c
index f3ee05868c50..6ef6ae030483 100644
--- a/src/avatar.c
+++ b/src/avatar.c
@@ -54,8 +54,7 @@ static uint8_t *load_img_data(char hexid[TOX_PUBLIC_KEY_SIZE * 2], size_t *out_s
         return NULL;
     }

-    if (fread(data, size, 1, fp) == size) {
-        LOG_WARN("Avatar", "Could not read from open file: %s\n", name);
+    if (fread(data, size, 1, fp) == 1) {
         fclose(fp);
         if (out_size) {
             *out_size = size;
@@ -63,6 +62,7 @@ static uint8_t *load_img_data(char hexid[TOX_PUBLIC_KEY_SIZE * 2], size_t *out_s
         return data;
     }

+    LOG_WARN("Avatar", "Could not read from open file: %s\n", name);
     fclose(fp);
     free(data);
     return NULL;
```

**Comment by robinlinden** [comment]
You're right, and I see that the same problem exists elsewhere in the code too.. Well, thank you very much for noticing and the patch. We appreciate it. :) 

Want to open a PR or should I do it on your behalf?

**Comment by flussence** [comment]
Go ahead and do it - I was going to try earlier but Github's being a PITA and telling me my ssh key's invalid for whatever reason.

**Comment by robinlinden** [comment]
Yeah, GitHub does that.. I submitted a patch on your behalf in #714 and gave you credit in like 2-3 different places. :P (Thank you again, it's always really awesome when people submit bug reports and patches.)
