### ISSUE TITLE
Clicks apply to multiple layers

### ISSUE THREAD

**Issue by robinlinden** [uTox/uTox#718]
"xdg-open is run if behind Paste there is a link already, as if the user clicked twice"

"if in the buffer behind the selection in the context menu is a clickable url, xdg-open will run
it will be as if the user clicked twice instead of once"

Reported on Arch x86-64 running uTox 0.9.8. Possibly Linux-only or fixed issue. 
(Unable to reproduce on 0.12.2 on Windows 10 x86-64.)

![image](https://cloud.githubusercontent.com/assets/8304462/22626454/d594b982-ebad-11e6-90b3-a0694786d9b4.png)

**Comment by GrayHatter** [comment]
I think this is fixed @robinlinden
