### ISSUE TITLE
msys2 (windows) build report

### ISSUE THREAD

**Issue by Axaprj** [uTox/uTox#720]
compilation error with    -DGIT_VERSION=\"$GIT_V\" 

>src/ui/draw_helpers.c:305:25: error: 'w' undeclared (first use in this function)
>     drawtextwidth_right(w + SIDEBAR_WIDTH - textwidth(ver_string, count), textwidth(ver_string, count)

scripts:
https://github.com/Axaprj/MSYS2/tree/master/utox

**Comment by robinlinden** [comment]
That file has gone away in #550, so this should work after that's merged. I think.

I like the scripts, but I think you'd have an easier time using cmake for the uTox script too.
I am able to build it on Windows like so:
```
cmake . -DCMAKE_BUILD_TYPE=Release -DTOXCORE_STATIC=True -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain-win64.cmake
make
```
Where the available build types are as follow: `Release`, `Debug`, `MinSizeRel`, or `RelWithDebInfo`.

You can also pull pre-built dependencies from https://build.tox.chat/ if that's something you'd want.

**Comment by Axaprj** [comment]
cmake revision of uTox build (windows msys2 32 64) is ready: 
https://github.com/Axaprj/MSYS2/tree/master/utox

some questions:
1) openal library name. See update CMakeLists.txt #731
2) -DTOXCORE_STATIC=True issue.
IMHO, the toxcore linked statically in any case. But when TOXCORE_STATIC=True it requires not existing libraries set: 
> The static windows libs need all of these... because REASONS!
>    set(TOX_LIBS  toxencryptsave  toxav  toxdns   toxcore toxgroup  toxmessenger   toxfriends   toxdht  toxnetcrypto  toxcrypto  toxnetwork)

I cannot understand how to build them...

**Comment by GrayHatter** [comment]
The are the current toxcore libs that are generated by https://github.com/TokTok/c-toxcore/ you should consult the TokTok build documentation for instruction on building a static version of toxcore.

Or you can grab copies from https://build.tox.chat
