### ISSUE TITLE
v0.12.1: Windows7/Windows10: Send File issue 

### ISSUE THREAD

**Issue by Axaprj** [uTox/uTox#721]
Windows7, Windows10
v0.9.7: Ok
v0.12.1: Send File dialog opens but selected file is not sent.
Moreover, the application failures was observed (like not respond)

**Comment by robinlinden** [comment]
I'm 97% sure that we fixed this in 0.12.2. Would you mind updating and trying again?

**Comment by Axaprj** [comment]
thanks! looks like is ok  in 0.12.2

**Comment by robinlinden** [comment]
Awesome! Glad that's sorted and thank you for the bug report. :)
