### ISSUE TITLE
Desktop notifications on X11 stopped working

### ISSUE THREAD

**Issue by flussence** [uTox/uTox#728]
It looks like the Shiny New CMake Stuff has no way whatsoever to pass dbus flags down to the compiler (the old build system just had `make DBUS=1`). I'm hopeless at cmake so I'd rather leave this to someone who knows what they're doing.

tl;dr - please add a switch that appends `-DHAVE_DBUS $(pkg-config --cflags --libs dbus-1)` to cflags

**Comment by GrayHatter** [comment]
@flussence can you test #690 ?

**Comment by flussence** [comment]
#690 works for me: compiles fine, notifications work again too. CMake complained about a "FindDBUS.cmake" not found (case-sensitivity? There's a FindDBus.cmake in there), but it seems to work regardless.

**Comment by GrayHatter** [comment]
And notifications worked at you expected?

**Comment by flussence** [comment]
Yeah, I have a build of c53269b6a installed (where it wasn't working) and sent messages between it and this version; this one displays them fine.

**Comment by GrayHatter** [comment]
should be fixed now.

Let me know if it's not
