### ISSUE TITLE
Video issues uTox 0.9.7 -> 0.12.2

### ISSUE THREAD

**Issue by ismaell** [uTox/uTox#752]
I see on both ends the message: "uToxAV: Change state with an error, this should never happen. Please send bug report!"

There seems to be some packet loss after it, not sure if related...

Both sides seem to exchange audio just fine, and 0.12.2 sends video to 0.9.7, but doesn't receive it.

To be more specific:
0.12.2 was built from commit 2ef71d7596902051487d5d1b62473d7cc04e36db, while 0.9.7 came from https://build.tox.chat/view/uTox/job/uTox_build_linux_x86-64_release/lastSuccessfulBuild/artifact/utox_linux_x86-64.tar.xz (MD5: f0437ea6a580d964e06ff0bf7be62996).

**Comment by cebe** [comment]
Is the problem reproduceable or did this just happen once? If you can reproduce it, please run utox with debug output (`utox -vvvvvvvv`) and paste the output here.

**Comment by ismaell** [comment]
And now for some reason video works, after running it under gdb...

**Comment by GrayHatter** [comment]
those bugs are the "best" bugs

**Comment by ismaell** [comment]
After some testing, it turned out to be unreliable, yet the message remains, so it must be unrelated. I'll try to figure what it's about later.
