### ISSUE TITLE
Notification icon is red forever

### ISSUE THREAD

**Issue by fcore117** [uTox/uTox#769]
After getting first notification then icon is red forever.
![notification](https://cloud.githubusercontent.com/assets/1313813/23164184/935003d6-f83e-11e6-9366-4af211f94a5b.PNG)

Tested on lastest uTox dda9e3c

**Comment by GrayHatter** [comment]
makes sense, red is a power color, and uTox is the most powerful client :D

**Comment by uname2p** [comment]
@GrayHatter  Hope to restore the original default color, only when new message shows red

**Comment by robinlinden** [comment]
@uname2p Ignore grayhatter. :P We'll fix this.

**Comment by uname2p** [comment]
@robinlinden Thank you so much

**Comment by robinlinden** [comment]
Fixed in https://gitlab.com/uTox/uTox/merge_requests/788
