### ISSUE TITLE
uTox lost chat history

### ISSUE THREAD

**Issue by uname2p** [uTox/uTox#770]
Systeom: Widnows 10
Client: uTox v0.12.2

uTox not write chat history into file when exit app. Open the path (%appdata%\Tox), history files always 0KB.

Previously used version(0.9.7) does not have this problem

![utox_bug](https://cloud.githubusercontent.com/assets/19523804/23201332/19ab6d5a-f914-11e6-9798-61e35ef963c1.jpg)

**Comment by uname2p** [comment]
Previously used version(0.9.7) does not have this problem

**Comment by cebe** [comment]
Can you try that with the latest version? v0.13.0

**Comment by robinlinden** [comment]
This is an issue I fixed a few weeks ago in 56b9fff79ca6afd28b0ece0634a62cbc80c26301, so it should work now.

**Comment by uname2p** [comment]
@cebe @robinlinden  Yes, it was fixed. Thank you
