### ISSUE TITLE
The screenshot status is not updated

### ISSUE THREAD

**Issue by uname2p** [uTox/uTox#771]
System: Windows 10
Version: 0.13.0 
The other side of the client automatically received a screenshot, but my utox did not update the state here.
The other version of uTox will show the progress and change the status.
![2017-02-23_091927](https://cloud.githubusercontent.com/assets/19523804/23240840/a1ceab5c-f9aa-11e6-8721-79958872a914.jpg)

Thank you.

**Comment by redmanmale** [comment]
See also #655

**Comment by uname2p** [comment]
@redmanmale  Thanks for your help

**Comment by fcore117** [comment]
uname2p: what version is other utox?

**Comment by fcore117** [comment]
I confirm, happens quite a lot, for some contact it shows ok but for another no feedback.

**Comment by cebe** [comment]
reproduced on v0.13.0 on Debian Linux.

**Comment by uname2p** [comment]
@fcore117 other uTox v0.12.2 on Windows 7, my uTox v0.13.0 on Windows 10

**Comment by uname2p** [comment]
@cebe the bug not fixed on v0.13.0 on Widnows 10(64bit). Sorry, i'm not work on Debian Linux

**Comment by cebe** [comment]
@uname2p "reproduced" means, that I am also able to see the bug if I follow the same steps, the comment was to mention that the problem exists not only on windows but also on Linux.
