### ISSUE TITLE
Can't send or receive more than one inline image still.

### ISSUE THREAD

**Issue by raisingw** [uTox/uTox#775]
Current nightly. Tested sending to an old version (0.9.7) from the current, works fine. Replacing the old version with 0.13.0 nightly prevents more than one inline image going through without restarting the receiving end after each image sent.

**Comment by cebe** [comment]
this should be fixed by https://gitlab.com/uTox/uTox/merge_requests/773

**Comment by robinlinden** [comment]
Fixed in https://gitlab.com/uTox/uTox/merge_requests/773
