### ISSUE TITLE
GitLab?

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#778]
As I can see a lot of development discussions (almost all of them) move to GitLab. And I've got a couple of questions.

Is it permanent or temporary or some kind of experiment?
All issues were copied from here, do you plan a backward sync?
What is the reason for that move? Is it some conceptual problem with GitHub, licensing or political issue?
Or Gitlab is more useful? What are the killer features?

I'm just curious.

**Comment by robinlinden** [comment]
Most dev discussions have always and will probably always happen on IRC. What's on Git{Hub,Lab} is what we've talked about on IRC most of the time.

Is this permanent or temporary?
Right now, it's an experiment to see if GitLab is "ready" to be used full-time without any loss of features.

We don't currently have a solution for syncing issues across and from what I can tell, there isn't really one. We might be able to adapt https://gist.github.com/jakimowicz/4079496 if we do switch to GitLab permanently.

The reason for the move is lack of transparency from GitHub's side, GitLab's CI being way better, GitHub not being open-source while GitLab is. GitLab just looks a lot like the future. A problem we've run into is that GitLab lacks a lot of the nice integration with things like e.g. Reviewable.

**Comment by redmanmale** [comment]
@robinlinden 
Thank you for explanation!

We're using on-site GitLab installation at my work, and we're happy with it (in general).
Also I noticed that our GitLab much faster than site, gitlab.com is really slow. Or I'm just spoiled.

**Comment by robinlinden** [comment]
Heh. You're right about gitlab.com being **really** slow every now and then. 
Might be a bug or something, but I pushed to a branch on a repo there ~9h ago and GitLab hasn't changed the number of branches displayed on the repo even though I can look at the new branch.. It won't let me open a PR either, so I'm not sure what's up with that.

**Comment by cebe** [comment]
> Might be a bug or something, but I pushed to a branch on a repo there ~9h ago and GitLab hasn't changed the number of branches displayed on the repo even though I can look at the new branch.. It won't let me open a PR either, so I'm not sure what's up with that.

I had a similar issue with a commit that did not show up in a PR... We might open a bug report for these.

**Comment by robinlinden** [comment]
Reopening this issue to make it more visible for now.

**Comment by redmanmale** [comment]
Are you really back (https://github.com/uTox/uTox/pull/792)?

**Comment by robinlinden** [comment]
Yeah, we're transitioning back after releasing 0.14.0 (which should happen today or so.)

**Comment by GrayHatter** [comment]
RIP @Gitlab I'd still rather use them. But until they add some way to do code review. We're stuck on github.

(Their code diffs are worst I've ever used)
