### ISSUE TITLE
Doesn't launch at all with OS X Sierra

### ISSUE THREAD

**Issue by kangasbros** [uTox/uTox#780]
Downloaded the binaries, didn't work at all. Can send crash report on request.

qTox experimental build works like a charm though.

Process:               utox [81588]
Path:                  /Applications/uTox.app/Contents/MacOS/utox
Identifier:            future.utox
Version:               1.0 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           utox [81588]
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** Can't add a nil AVCaptureInput'
terminating with uncaught exception of type NSException
abort() called

**Comment by GrayHatter** [comment]
@kangasbros we just released v0.14 if that still crashes let me know and I'll invistage this a bit more and see if we can't get it working for you.

Sadly, we're missing an OSX dev so it's a very difficult platform to develop for.

**Comment by publicarray** [comment]
@kangasbros Sorry for the long wait. The latest binary version is quite old (v0.9.8) but we are working on updating the build scripts for mac. I've made a build but it not release ready just yet. Are you willing to test the this build (v0.15.1)? Your feedback would be appreciated. Thanks

https://drive.google.com/open?id=0B25hJXEzaTIFR2hXU3NzNmxLMlU
```
$ gsha256sum uTox\ 0.15.1.dmg 
e211acf91c563edb7605ff75ef0553c8ac311d18276ad864f7f65d1f45fa2d2d  uTox 0.15.1.dmg

**Comment by GrayHatter** [comment]
closing as stale and in favor of #419
