### ISSUE TITLE
Error 2 compiling on ubuntu 16.04

### ISSUE THREAD

**Issue by mariarti** [uTox/uTox#782]
Do
```
sudo apt-get install build-essential libtool autotools-dev automake checkinstall check git yasm libopus-dev libvpx-dev pkg-config libfontconfig1-dev libdbus-1-dev libv4l-dev libxrender-dev libopenal-dev libxext-dev cmake
git clone git://github.com/uTox/uTox.git
cd uTox/
mkdir build
cd build
cmake ..
make
```
and got
```
:~/uTox/build$ make
Scanning dependencies of target utoxAV
[  1%] Building C object src/av/CMakeFiles/utoxAV.dir/utox_av.c.o
In file included from /home/tt/uTox/src/av/utox_av.c:1:0:
/home/tt/uTox/src/av/utox_av.h:5:92: fatal error: tox/toxav.h: No such file or directory
compilation terminated.
src/av/CMakeFiles/utoxAV.dir/build.make:62: recipe for target 'src/av/CMakeFiles/utoxAV.dir/utox_av.c.o' failed
make[2]: *** [src/av/CMakeFiles/utoxAV.dir/utox_av.c.o] Error 1
CMakeFiles/Makefile2:274: recipe for target 'src/av/CMakeFiles/utoxAV.dir/all' failed
make[1]: *** [src/av/CMakeFiles/utoxAV.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by robinlinden** [comment]
I'm not sure why those instructions are listed first. You need to get a few dependencies and stuff like that before you can compile uTox.

Try following the instructions at https://github.com/uTox/uTox/blob/develop/docs/BUILD.md#tested-on-ubuntu-1510 and let me know if that works any better.

**Comment by mariarti** [comment]
i do exactly how it was described, but it does not work.
what i've done wrong?

**Comment by robinlinden** [comment]
Your error message is that the Toxcore libraries are missing. You need to follow all the steps in the section I linked to above before you can compile uTox.

**Comment by mariarti** [comment]
I started from that link before i post here.
Ok, my fault - i didn't compile other parts: 

```
git://github.com/jedisct1/libsodium.git
git://github.com/irungentoo/filter_audio.git 
git://github.com/TokTok/c-toxcore.git

```
omg, why it so complicated? 
why not to includ  to 'all in one' ?

so, thats is not an issue.

**Comment by robinlinden** [comment]
I know it's complicated, but sadly not all parts that are required are packaged so you can't just `apt install` them. 

If you need any help with any step of the process, you're more than welcome to join [#uTox on Freenode](https://webchat.freenode.net/?channels=utox) and we'll do our best to help you out.

**Comment by cebe** [comment]
I am planning to provide packages for Debian and Ubuntu in April. Ideally they should be built directly in the gitlab-CI stage.
