### ISSUE TITLE
official sources

### ISSUE THREAD

**Issue by oberon2007** [uTox/uTox#787]
Some discussion is going on about which source is now the official one
Here on github or the one on [gitlab](https://gitlab.com/uTox/uTox/commits/develop)
They look almost the same, yet there are one or two newer commits on gitlab.
Can you please carify, thank you.

**Comment by robinlinden** [comment]
Per #778, the GitLab repo is currently the most up to date one. We'll be making a decision on whether to stay there or not in a few days. Our .deb builds are still based off of this repo, so that's why this is almost in sync with the GitLab one.

**Comment by GrayHatter** [comment]
we're back to github, at least until gitlab offers some sort of review system that doesn't suck
