### ISSUE TITLE
Click to open doesn't work with auto accept enabled

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#794]
**Steps to reproduce**
* enable auto accept files for a friend
* receive a file from this friend
* click on it to open

**Expected behavior**
The file should open.

**Actual behavior**
Folder with uTox.exe is opened.

**Notes**
This is only happen when auto accept is enabled. If it's not and you choose folder for incoming file, it opens by click just fine.

[Log](https://gist.github.com/redmanmale/9fe7c2e90d5bc362327266430406b08f).

P.S. I have to use system-wide search to find this file.
I know there's already issue about selecting folder for auto accepted files (#740), but why is there no info about default folder location? At least I cound not find any.

**Comment by robinlinden** [comment]
The default folder is (or should be) `%USERPROFILE%\Downloads\Tox_Auto_Accept\` in normal mode and `%UTOX_ROOT%\Tox_Auto_Accept` in portable mode.
^ is for Vista onwards. For XP I think it saves the file on your desktop in normal mode and same as Vista onwards in portable mode.

**Comment by redmanmale** [comment]
Fixed in #923.
