### ISSUE TITLE
Updates (no new version on site)

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#795]
I consider https://downloads.utox.io/stable/ as a main source for uTox bins.

Latest update for win64 was at 22-Feb-2017 and it's v.0.13.0.
Latest update for win32 was at 07-Feb-2017 and it's v.0.12.2 (which doesn't save history).

However there's 0.13.1 since february, and there's no way to get.

**Comment by robinlinden** [comment]
That win32 hasn't been updated is a bit of a problem.. Oh well, we're releasing 0.14.0 ~today, or at least this weekend. 
0.13.1 doesn't really affect anyone not compiling uTox with the address sanitiser enabled, so it wouldn't have made a difference for our Windows binaries.

**Comment by GrayHatter** [comment]
It'll go within the next 2h, unless there's a hangup

**Comment by GrayHatter** [comment]
v0.14 is now live!

Windows users can use the old updater, which will include the new version of the updater.

The automatic Debs will be updated once our packager gets online.

Other distros will update as they see fit
