### ISSUE TITLE
Interface glitches after changing DPI

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#810]
**Steps to reproduce**
* Open uTox
* Change DPI

**Notes**
No matter increase or decrease DPI, it reproduces anyway. It looks like this:
![pic](https://puu.sh/vfpCh/23f298eaa2.png)

After window resize or move (when it's redrawn) everything is OK.

**Env**
Win 7 x86, x64, uTox v.0.14.0

**Comment by GrayHatter** [comment]
exists in master

**Comment by GrayHatter** [comment]
should be fixed in magic branch, about to be merged #842
