### ISSUE TITLE
Crash when receiving file with auto accept enabled

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#811]
**Steps to reproduce**
* open uTox
* receive a file

**Notes**
Only occures on x86 and with auto accept enabled, on x64 everything is good anyway.

[Log](https://gist.github.com/redmanmale/9f677a56cdbd56f1ea587e17fc02dcf7).

**Env**
Win 7 x86, uTox v.0.14.0

**Comment by GrayHatter** [comment]
@robinlinden are there any noticeable differences between x32/x64 you saw?

**Comment by robinlinden** [comment]
https://github.com/uTox/uTox/blob/develop/src/windows/main.7.c#L83
We were using the pointer size to decide how long the string we allocate for should be allowed to be.

**Comment by robinlinden** [comment]
#806 should fix this. @redmanmale, would you mind trying it?

**Comment by redmanmale** [comment]
@robinlinden 
I'll check in couple of hours.

**Comment by redmanmale** [comment]
I need compiled binaries from this sources (ad8c9905f1c25a2fe3dba1a017c46cb3e697172d) or some instructions how to cross-compile for windows on Ubuntu.

**Comment by redmanmale** [comment]
OK, this is fixed.

**Comment by robinlinden** [comment]
Awesome. Thanks for having a look!
