### ISSUE TITLE
message icon not refresh

### ISSUE THREAD

**Issue by uname2p** [uTox/uTox#812]
System：Windows 7
Version：uTox 64bit 0.14.0
You and me are chatting,  you new message is viewed, but the message prompts icon not to refresh, I
need to switch friends or click it to close the new message prompt icon
![bad](https://cloud.githubusercontent.com/assets/19523804/24854240/456f413e-1e10-11e7-8384-5e314bcd91ce.jpg)

**Comment by redmanmale** [comment]
Also on Win 7 (x86).

**Comment by fcore117** [comment]
yes and if sound is enabled then even if you are in same chat window then you still get sound notification.

**Comment by endoffile78** [comment]
This is probably because of this commit: https://github.com/uTox/uTox/commit/4ffbc7e36d31baf473ab320c4ae19030eff3a7ef. Changed because of #717

**Comment by GrayHatter** [comment]
The real issue is uTox doesn't keep a global state if the window has focus or not

This is a shame because every platform offers an easy way to track this as a bool.

**Comment by GrayHatter** [comment]
should be fixed by #899
