### ISSUE TITLE
Missing a lot of translations

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#818]
In the last releases in uTox UI was added a lot new stuff, and some of new functions are missing translations.

I wrote down a small [script](https://gist.github.com/redmanmale/18748ca46ac15e2ec41cad53257a8c96#file-getmissingtranslations-py) (in Python 3) to get all missing translations and I was surprised to see how many (25 langs and ~2.5k fields).

Also I noticed, that danish lang file is the only one which named unlike the others.

Full list of missing translations is [here](https://gist.github.com/redmanmale/18748ca46ac15e2ec41cad53257a8c96#file-utox_missing_translations_report_for_0-14-0-txt).

**Comment by GrayHatter** [comment]
Some of these are false positives, but I really like the script. You should open a pull request adding it to the extra/ folder
