### ISSUE TITLE
no tray icon in LXDE

### ISSUE THREAD

**Issue by vasisualiy** [uTox/uTox#822]
Regression in 0.13.0. No trayicon shown in LXDE.

**Comment by GrayHatter** [comment]
how about in v0.14?

**Comment by GrayHatter** [comment]
and you said regression in v0.13.0 is that when it last worked, or when it stopped working?

**Comment by vasisualiy** [comment]
I mean in 0.13.0 (or 0.13.1? the name in the window-header is 0.13.0, the name of arch-package is 0.13.1-1)   its stop to work.

**Comment by GrayHatter** [comment]
Ahh the package for uTox is out of date @NicoHood must be busy, but I'd suspect it'll get fixed soon.

you can try the utox-git package on the AUR, or build from source if you know how... or just wait for @NicoHood .

**Comment by vasisualiy** [comment]
just tried git version from aur. The tray icon is back now :)

Just of interest: why tray icon is so complicated to do, I mean, that it was a long way till tray icon was working, and then it was broken relatively often? Is there no standard for it?

**Comment by GrayHatter** [comment]
There's a standard, but there's many, and shit window managers/desktop
environments follow different, and non applicable for other systems/uses.

I'm not sure if lxde is good or not, there's a chance I did something
stupid in v0.13. But the tray has worked in i3 from the first day I added
the tray code. Where GDM support is new to v0.14

**Comment by NicoHood** [comment]
working in 0.15.0 for me.
