### ISSUE TITLE
Some redesign proposal

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#823]
Now we've got:
![now](https://puu.sh/vjiog/714e5c6247.png)

As you can see, controls are not aligned, large offsets between labels and switchs make it hard to keep track which switch for which (yeah, I know about tooltips on hover, and it helps, but still).

I propose to swap labels and swtiches, it'll make a lot easier to understand what they do and make interface more compact (as a bonus).

What I want to do:
![proposal](https://puu.sh/vjiph/a8c3030b4e.png)

Of course I'll change it for all tabs, not just for advanced.

Or I'll just fix alignment if all of this is a bad idea.

**Comment by GrayHatter** [comment]
I think it looks better on the left, clearly easier to read that way.

But I think it'd be a mistake to just one page, all the settings pages should be moved, if you going to move any.

**Comment by GrayHatter** [comment]
Also, if you want to, you could create new files for each setting page in the `layout/` directory so eg

```
layout/settings/profile.c/h
layout/settings/interface.c/h
layout/settings/audio_video.c/h
layout/settings/notifications.c/h
```
etc...  If I recall correctly, they're all in a mess inside `layout/settings.c/h` and all of them are disorganised.

**Comment by GrayHatter** [comment]
If you're willing to do all of that, let me know and once you open a pull request. I'll add you as a developer so you can work on uTox a bit easier.

**Comment by fcore117** [comment]
Maybe some futuristic but same time simple underline or line that points to button? so eyes can quickly see what is what and where.

Idea basis like this:
https://image.shutterstock.com/z/stock-vector-vector-abstract-background-shows-the-innovation-of-technology-concepts-603768815.jpg
https://image.shutterstock.com/z/stock-vector-vector-abstract-futuristic-stripe-line-circuit-board-pattern-with-gear-wheel-and-arrow-symbol-297757619.jpg
https://www.google.ee/search?q=futuristic+line+circuit+board&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjVwtbEnqTTAhUBGywKHexpDtEQ_AUICCgB&biw=1592&bih=804#tbm=isch&q=futuristic+ui+vector
