### ISSUE TITLE
Could not set password on Ubuntu

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#824]
I'll check it on different system later, but for now this bug is here.

```
Toxcore:
WARNING UTOX WAS UNABLE TO ENCRYPT DATA!
DATA WRITTEN IN CLEAR TEXT!
```

**Env**
Ubuntu 16.04, uTox v.0.14.0 + develop (b07c290).

**Comment by redmanmale** [comment]
Damn.
I tried three-symbols password, but minimum [is four](https://github.com/uTox/uTox/blob/b07c290e1d2e42c37d39206215b6323ad4a025d0/src/layout/settings.c#L558).
No info about min length, no messages, even no warnings in log!

**Comment by endoffile78** [comment]
Opened an issue about adding a warning #825.

**Comment by GrayHatter** [comment]
lol oops, sorry guys... good catch @endoffile78 @redmanmale
