### ISSUE TITLE
Add a configure-time switch to disable LTO

### ISSUE THREAD

**Issue by flussence** [uTox/uTox#844]
Please? Having `-flto` hardcoded makes it kind of hard to compile on less than 4GB RAM.

**Comment by GrayHatter** [comment]
worksforme; wontfix

**Comment by flussence** [comment]
Alright, but could you at least document how much RAM *is* required? 2GB + 2 swap evidently isn't enough and throwing more at it won't help, this is on i686.

**Comment by GrayHatter** [comment]
nah, I' was just kidding, I was hoping to push a fix before anyone saw this

**Comment by GrayHatter** [comment]
I'm testing the compile options now... sorry mate!

**Comment by flussence** [comment]
Okay... had me going for a minute there.

**Comment by GrayHatter** [comment]
I think it's working now, but `shrugs`

try `cmake src/dir/ -DENABLE_LTO=OFF`

**Comment by flussence** [comment]
That worked, thanks!

(not your fault GCC can't link a pretty straightforward C/X11 program without OOM'ing, but oh well)

**Comment by redmanmale** [comment]
> 2GB + 2 swap evidently isn't enough

That's strange. I compile uTox on VM with 1Gb RAM and 1Gb (or 2Gb) swap.

**Comment by flussence** [comment]
I think I figured it out (the OOM came back, even without LTO). `src/ui_i18n.c` plus all the files it includes adds up to nearly 2MB of C code in a single compilation unit.

It's fine with no flags, but trying to use my system-level `$CFLAGS` breaks it. Even `gcc -O2 -march=i686` takes forever with this one file, several times longer than the rest of the codebase combined.

**Comment by GrayHatter** [comment]
@flussence yeah I've come across this myself more than once. it's the gratuitous use of macros.

It's somewhat complicated as it is, so a refactor won't be trivial. Which is why it's not too high on my priority list.
