### ISSUE TITLE
Status and name overlaps with the status change button.

### ISSUE THREAD

**Issue by robinlinden** [uTox/uTox#850]
Regression in #842 

The amount of overlap depends on which characters you've used in your status and name.

![image](https://cloud.githubusercontent.com/assets/8304462/25304272/57428116-2764-11e7-9838-7c0e27838438.png)

**Comment by redmanmale** [comment]
Should be fixed in #835.

**Comment by GrayHatter** [comment]
confirmed fixed in develop on xlib

@robinlinden

**Comment by robinlinden** [comment]
Fixed in #835
