### ISSUE TITLE
make Xcode project

### ISSUE THREAD

**Issue by wellkwen** [uTox/uTox#851]
Hello everybody! Tell me please how to run it in Xcode? I'm new, and I do not understand a bit!

**Comment by robinlinden** [comment]
That might be a bit hard to do since we have literally 0 OS X devs. :(

This comment might help you though: https://github.com/uTox/uTox/issues/841#issuecomment-295961978

If you do get it working, instructions or anything to help other users compile uTox on OS X would be greatly appreciated. :)

**Comment by publicarray** [comment]
Hi @wellkwen 

You can install the dependencies with homebrew by following the instructions at [COCOA.md](https://github.com/uTox/uTox/blob/develop/docs/COCOA.md)

> 
```
brew install --HEAD libtoxcore
mkdir build
cd build
cmake -G Xcode ..
```

It is very likely that the search paths do not include libtoxcore (there is a pull request underway to fix this) so you have to add them to your project settings.

possible Header Search Paths:
* `/usr/local/include/`
* `/usr/local/opt/libtoxcore/include/`

possible Library Search Paths: 
* `/usr/local/lib/`
* `/usr/local/opt/libtoxcore/lib/`

If you want debug symbols you need to change the Debug Information Format to DWARF with dSYM File.
At the moment the bundle identifier in the Info.plist is missing so before you open the app you need to add it.
Hope that helps.

**Comment by publicarray** [comment]
On second thought It might be best to wait until #854 PR is merged.

**Comment by wellkwen** [comment]
hi @publicarray !
I'm so sorry, but its don't worked, 
when I try do this, I see that: 

> MacBook-Pro-Nikki:~ nikki$ brew install --HEAD libtoxcore
> Error: No available formula with the name "libtoxcore" 
> ==> Searching for a previously deleted formula...
> Error: No previously deleted formula found.
> ==> Searching for similarly named formulae...
> Error: No similarly named formulae found.
> ==> Searching taps...
> Error: No formulae found in taps.
> MacBook-Pro-Nikki:~ nikki$ mkdir build
> mkdir: build: File exists
> MacBook-Pro-Nikki:~ nikki$

Tell me please, maybe I'm doing something wrong? I really want to understand how this happens, and what is my mistake

**Comment by robinlinden** [comment]
@publicarray You wouldn't by any chance happen to be interested in being uTox's official OS X dev? :P

**Comment by robinlinden** [comment]
@wellkwen Looking at the instructions at https://github.com/Tox/homebrew-tox, it sounds like you have to run `brew tap Tox/tox` before running the brew install command.

No idea if this will work though. I don't run OS X. :x

**Comment by wellkwen** [comment]
@robinlinden thank you for help!
I try to understand

**Comment by publicarray** [comment]
Sorry I missed that part. Unfortunately the formula in https://github.com/Tox/homebrew-tox/blob/master/Formula/libtoxcore.rb is outdate and references a older version of libtoxcore.
you can do `brew install --HEAD https://raw.githubusercontent.com/xsleonard/homebrew-tox/c23a8ecfc909eb983f1dc3c085190a052abb2f9e/Formula/libtoxcore.rb` until https://github.com/Tox/homebrew-tox/pull/37 is merged

**Comment by publicarray** [comment]
@wellkwen How are you going with the xcode build? The formula has been updated and should make it easier. I've updated the instructions [here](https://github.com/uTox/uTox/blob/cocoa-instructions/docs/COCOA.md#how-to-create-an-xcode-project)

**Comment by wellkwen** [comment]
@publicarray ooo thank you so much!! its work!!
