### ISSUE TITLE
uTox assembly info (on Windows)

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#869]
Could we patch uTox assembly information (version, name, etc) into its resources?

![pic](https://puu.sh/vuGhQ/6648b5dd48.jpg)

On OSX it's done (probably, I found this screenshot in the old issue):

![pic2](https://cloud.githubusercontent.com/assets/91113/18111112/4ea5e688-6f1d-11e6-98a9-022e59c78d3f.png)

**Comment by GrayHatter** [comment]
http://stackoverflow.com/a/35429430 and https://msdn.microsoft.com/en-us/library/windows/desktop/aa381018(v=vs.85).aspx and https://msdn.microsoft.com/en-us/library/windows/desktop/aa381058(v=vs.85).aspx

finally https://github.com/uTox/uTox/blob/develop/icons/icon.rc which should be moved, and renamed if you add the additional information.

**Comment by robinlinden** [comment]
Fixed in #880
