### ISSUE TITLE
Preview call never ends uTox 0.15.0

### ISSUE THREAD

**Issue by WPFilmmaker** [uTox/uTox#874]
As per title whenever I click on the preview calls the icon becomes red, but it never stops, IMHO it should end after a certain amount of time (like it happens with skype when you do a test call). If I click preview it is because I would like to test if everything works fine, therefore I suggest to make the test call more similar to skype.

**Comment by GrayHatter** [comment]
I'm not 100% sure what you mean... the preview in the AV settings page?

**Comment by GrayHatter** [comment]
I don't think we're gonna fix this one. If you'd like to open a more descriptive issue, one explaining how you'd expect everything to work. I'll be happy to take another look at it.
