### ISSUE TITLE
User Interface Issues

### ISSUE THREAD

**Issue by DexterMcKinnery** [uTox/uTox#893]
Hello, I'd like to report a couple of bugs and a request

- First of all, this bug has been happening for a long time and is very easy to reproduce. If you have a link in the chat log on screen, then right click and go to paste something into the text box, it's possible to click THROUGH the context menu as you paste (or copy) and click the link underneath which will open whatever that link is in your browser. This happens on Windows AND Linux.

- Second, I've noticed that the ring around the contact's status circle now shows up whilst you are looking at that tab and won't go away until you change tab or window. Not a program breaking bug, just sometimes annoying.

- Third, the UI seems to have... shrunk. I've found that what is now "110%" DPI is what used to be the default and is the DPI that everything lines up right and looks good at. The 100% that is sets to now causes things to be misaligned.

- Finally, just a request; since another tab was added to the uTox settings section, it has forced the window's minimum width wider. This is frustrating because it now takes up even more of my screen than it did already and makes taking screenshots of the screen to my contacts even more awkward than it was before due to the position of the screenshot button and the fact that the window is now so wide and I can't make it thinner... I was wondering if it was possible to give more lenience with the window width dimensions so I can make the window thinner again, even if this means some of the settings tabs disappear off the side until the window is widened again? Considering that the setting section is looked at far far less than the rest of the program, I feel that IT restricting the minimum width of everything else isn't all that useful.

Thank-you for reading! I hope this is helpful.

<hr>

- [x] Click through on context menu
- [x] Notification bug (#894)
- [x] DPI scale (not a bug)
- [x] Window min width (#899)

-- added by @grayhatter

**Comment by robinlinden** [comment]
- 2: I was looking at earlier today but ran out of time. It's a regression from 4ffbc7e and would easily be fixed if we exposed a way to check if uTox is in focus or not.

- 4: I'd be happy to reduce the minimum width. The new minimum is too wide for me too, even after I allowed for it to be less wide.

**Comment by DexterMcKinnery** [comment]
Thank-you, haha! I'm glad I'm not the only one who finds it too wide! I appreciate your help.

**Comment by robinlinden** [comment]
Sorry, edited my message after you replied. :x

**Comment by DexterMcKinnery** [comment]
On the DPI thing, this is what I mean by misaligned/looking less nice! This is the same on Windows and Linux! Not program breaking, but good to know I think!

![100dpivs110dpi](https://cloud.githubusercontent.com/assets/15704583/25558450/f2698346-2d1e-11e7-83ca-c54696daff96.png)

**Comment by GrayHatter** [comment]
We can likely fix the sidebar alignment issues now by setting the x,y of the status icons to a negative value. Which now should be the right alignment of the sidebar, instead of right alignment of the whole window

**Comment by DexterMcKinnery** [comment]
I just wanted to add another bug that has been happening to my partner and I for a while... Tox will crash sometimes if one of the other people online fall offline. It did it to me just now because my partner logged out. It's been doing it to my partner for quite some time, but we thought it was because I was using an older version of Tox (because I wanted to keep the thinner window, haha!), but I was testing out the latest version today and it's now happened to me too, suggesting it would be a problem with the client, not that I was using an older version (that wasn't effected).

I think it might have something to do with image inline transfers as my partner mentioned something about that when they dumped a log of the crash on Linux. I'm not sure if they posted about it, but if they didn't, I will ask them about it tomorrow.

**Comment by robinlinden** [comment]
I know what crash you're talking about. It's in `break_file`/`ft_update_resumable` and occurs when one of your contacts go offline. We try to fseek a file pointer that isn't set to anything. It's basically the only crash that occurs with any frequency in uTox nowadays.

**Comment by redmanmale** [comment]
> sidebar alignment issues

I think this fixed in #870. I'm not sure, though.

**Comment by robinlinden** [comment]
`2.` was fixed in #899 
`4.` will be fixed whenever #894 is merged.

**Comment by GrayHatter** [comment]
should be fixed now

**Comment by GrayHatter** [comment]
nevermind @robinlinden can recreate it
