### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by nazar-pc** [uTox/uTox#901]
First of all, on Linux I do not see how to properly close an app (no context menu on the tray icon to do so). Killing an app results in settings not being saved.
The most I can do is to save all settings besides "Close to tray", since closing to tray means that I can't close an app "normally".

Some settings (language) are not saved at all regardless how I close uTox.

Would be nice if settings are saved immediately as they are changed, so that the way I close application doesn't matter anymore.

uTox 0.15.0 (static x86-64)

**Comment by GrayHatter** [comment]
...why would you ever went to close uTox?

**Comment by GrayHatter** [comment]
Only kidding, does your window manager/desktop environment not expose a way to close the window?

It should be saving when it gets the close signal from the window manager.

**Comment by nazar-pc** [comment]
I have close button with window decoration (Compiz), but when I select "Close to tray" uTox only really closes on system reboot, which apparently doesn't send a signal you're talking about. And when closing to tray absence of menu on uTox icon makes it impossible to close it in any other way than with terminal.

Does uTox support SIGTERM? Anyway, saving settings as they are changed seems simpler and more reliable.
