### ISSUE TITLE
Friend settings are not saved unless you change the alias too

### ISSUE THREAD

**Issue by erejnion** [uTox/uTox#905]
Trying to deactivate autoaccepting file transfers does nothing, unless you set the alias simultaneously with deactivating it (like, by focusing on the alias field and hitting enter). 

This way you can properly set the friend settings, but even with autoaccept showing as deactivated, tox still crashes because of one file transfer... but we'll write an issue about that when my friend tries debugging it on his end too.

**Comment by robinlinden** [comment]
I fixed that in #891 :>
