### ISSUE TITLE
Custom bootstrap node 

### ISSUE THREAD

**Issue by loskiq** [uTox/uTox#939]
How to use a custom bootstrap node?

**Comment by GrayHatter** [comment]
You'll need to edit src/tox_bootstrap.h before you compile

**Comment by loskiq** [comment]
@GrayHatter why is this option turned off by default?

**Comment by GrayHatter** [comment]
Why do you think you need to add a custom bootstrap node?

**Comment by loskiq** [comment]
@GrayHatter because we want to organize a local chat, but we do not have one segment of this network. There is no single broadcast IP address. Therefore, we want to use a custom bootstrap node. For example, this possibility exists in the mobile application Antox.

**Comment by GrayHatter** [comment]
The feature isn't turned off. It just doesn't exist.

The only way is to edit the list before you compile.

But this is an interesting use, I'll give it some thought.

**Comment by loskiq** [comment]
@GrayHatter thanks! :)
