### ISSUE TITLE
File Transfer issues 

### ISSUE THREAD

**Issue by Axaprj** [uTox/uTox#946]
uTox 0.15.0
Platform: msys2 x64 windows

1. Attempt to send file "тест.dat" (size: 2204272640)
2. Wrong not-ascii file name displayed in the file transfer control. Stored filename is Ok.
3. Wrong file size displayed: 15EiB
4. The file transfer failed: "тест.dat" (size: 2198170914), file transfer cancelled

Such behavior was reproduced several times

**Comment by redmanmale** [comment]
See #324.
Non-ASCII filename related part should be fixed in #923.

**Comment by redmanmale** [comment]
Looks like the same error #1298, which is more detailed.
