### ISSUE TITLE
Language settings don't save after changing

### ISSUE THREAD

**Issue by redmanmale** [uTox/uTox#96]
How to reproduce:
- open Tox;
- change language to another;
- close Tox;
- open again: language will be the same before changing.

This happens only with language, other settings save correctly.

Win 7 x64, Win 8.1 x64. v.0.4.4.
##

**Comment by tsudoko** [comment]
I think there would need to be an additional "System (*language name*)" language to make it possible to go back to the auto-detected one.

**Comment by redmanmale** [comment]
System language and uTox Interface language could be different.

I described specific bug: lang settings aren't saved.

**Comment by davidak** [comment]
this still happens with latest **uTox-nightly_build_linux_x86-64_debug**, Build 252 (23.07.2016 20:46:54).

**Comment by redmanmale** [comment]
Any chance of fix?

**Comment by GrayHatter** [comment]
I can include a fix for this in develop but develop is a bit buggy right now

Either way, I'm it may take until this weekend

**Comment by redmanmale** [comment]
Still the same on 0.11.1

**Comment by redmanmale** [comment]
Still here in 0.12.1
