### ISSUE TITLE
Instructions for Trisquel 8 installation.

### ISSUE THREAD

**Issue by im-grey** [uTox/uTox#964]
To install uTox on Trisquel 8 you only need a slight tweak of the default Debian/Ubuntu instructions that the Tox website tells you to do. I figured this should be public knowledge. Someone in IRC helped me through it. Basically, do everything else the same, but change this:

`> echo "deb https://pkg.tox.chat/debian stable $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/tox.list`

To this

`echo "deb https://pkg.tox.chat/debian stable xenial" | sudo tee /etc/apt/sources.list.d/tox.list`

This might also work in Trisquel 7.

**Comment by redmanmale** [comment]
The difference from Ubuntu is minimal.
