### ISSUE TITLE
Crash when trying to send a screenshot after sending an empty screenshot

### ISSUE THREAD

**Issue by Kakise** [uTox/uTox#982]
This happened when I was testing uTox (latest available Mac release for me and nightly build (Linux 64) for my friend).

What happened:
-> After sending an empty screenshot (just click somewhere on the screen) and clicking on the screenshot button, my friend and I both crashed (when he was using nightly)
-> After sending an empty screenshot (just click somewhere on the screen) and clicking on the screenshot button I, alone, crashed (after he switched to a "stable" build)

**Comment by dkmoz** [comment]
Are you able to provide a stack trace?

**Comment by redmanmale** [comment]
Could not reproduce with latest version (0.16.1) on Windows and Linux both.
Please try latest version and confirm if this still occur.

**Comment by redmanmale** [comment]
If you are still able to reproduce I'll reopen.
