### ISSUE TITLE
how can I change my tox ID ?

### ISSUE THREAD

**Issue by arnauldb** [uTox/uTox#985]
Hello,

how can I change my tox ID for one I used before ?
Thank you.

**Comment by publicarray** [comment]
I'm not entirely sure but all of the user settings are stored in ` ~/.config/tox/` on posix systems. You could try \%APPDATA%\tox\ on windows. If you still have access to the folder it you could just copy the data. If the you no longer have access to the private key (I think it in the folder) than recovery is impossible. Someone can correct me if I'm wrong.

**Comment by Emily7777** [comment]
Where is that file located on OSX?

**Comment by publicarray** [comment]
In Finder press `Shift + Command + G` 

![finder](https://user-images.githubusercontent.com/5497998/29234597-7f1258cc-7f3b-11e7-8ea0-cbfa54930392.png)

**Comment by arnauldb** [comment]
thanks publicarray. But when I open "tox_save.tox" I can't find what to change...

**Comment by zoff99** [comment]
@arnauldb you need to have your old "tox_save.tox" file saved already.
if you do not have it anymore, then your old ToxID is lost forever.

otherwise copy your old "tox_save.tox" over the new one, and restart your Tox client

**Comment by arnauldb** [comment]
thks zoff99, I understand now.
