### ISSUE TITLE
Can we get sha256sums for the windows downloads?

### ISSUE THREAD

**Issue by snifflezak** [uTox/uTox#986]
Can we get sha256sums for the windows downloads linked to on the main page? eg "utox_windows_x86-64.zip" thanks.

**Comment by GrayHatter** [comment]
is this from tox.chat?

**Comment by robinlinden** [comment]
@snifflezak Which downloads? utox.io? tox.chat? the ones linked in the github readme?

**Comment by redmanmale** [comment]
There's no more Windows downloads anyway.
